syntax = "proto3";

package hypershell.v1;

option go_package = "github.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1";

import "hypershell/v1/common.proto";

message Fleet {
  ObjectReference metadata = 1;
  string name = 2;
  optional string description = 3;
  optional string status = 4;
}

message CreateFleetRequest {
  string name = 1;
  optional string description = 2;
  optional string status = 3;
}

message CreateFleetResponse {
  Fleet fleet = 1;
}

message GetFleetRequest {
  string id = 1;
}

message GetFleetResponse {
  Fleet fleet = 1;
}

message UpdateFleetRequest {
  string id = 1;
  optional string name = 2;
  optional string description = 3;
  optional string status = 4;
}

message UpdateFleetResponse {
  Fleet fleet = 1;
}

message DeleteFleetRequest {
  string id = 1;
}

message ListFleetsRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListFleetsResponse {
  repeated Fleet items = 1;
  ListMeta metadata = 2;
}

message DeleteFleetResponse {}

message WatchFleetsRequest {}

message WatchFleetsResponse {
  EventType type = 1;
  Fleet fleet = 2;
  string resource_id = 3;
}

service FleetService {
  rpc GetFleet(GetFleetRequest) returns (GetFleetResponse);
  rpc CreateFleet(CreateFleetRequest) returns (CreateFleetResponse);
  rpc UpdateFleet(UpdateFleetRequest) returns (UpdateFleetResponse);
  rpc DeleteFleet(DeleteFleetRequest) returns (DeleteFleetResponse);
  rpc ListFleets(ListFleetsRequest) returns (ListFleetsResponse);
  rpc WatchFleets(WatchFleetsRequest) returns (stream WatchFleetsResponse);
}
