syntax = "proto3";

package hypershell.v1;

option go_package = "github.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1";

import "hypershell/v1/common.proto";

message GatewayRelease {
  ObjectReference metadata = 1;
  string name = 2;
  string fleet_id = 3;
  string image = 4;
  optional string rollout_strategy = 5;
  optional int32 canary_percent = 6;
  optional string canary_duration = 7;
  optional string status = 8;
}

message CreateGatewayReleaseRequest {
  string name = 1;
  string fleet_id = 2;
  string image = 3;
  optional string rollout_strategy = 4;
  optional int32 canary_percent = 5;
  optional string canary_duration = 6;
  optional string status = 7;
}

message CreateGatewayReleaseResponse {
  GatewayRelease gateway_release = 1;
}

message GetGatewayReleaseRequest {
  string id = 1;
}

message GetGatewayReleaseResponse {
  GatewayRelease gateway_release = 1;
}

message UpdateGatewayReleaseRequest {
  string id = 1;
  optional string name = 2;
  optional string fleet_id = 3;
  optional string image = 4;
  optional string rollout_strategy = 5;
  optional int32 canary_percent = 6;
  optional string canary_duration = 7;
  optional string status = 8;
}

message UpdateGatewayReleaseResponse {
  GatewayRelease gateway_release = 1;
}

message DeleteGatewayReleaseRequest {
  string id = 1;
}

message ListGatewayReleasesRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListGatewayReleasesResponse {
  repeated GatewayRelease items = 1;
  ListMeta metadata = 2;
}

message DeleteGatewayReleaseResponse {}

message WatchGatewayReleasesRequest {}

message WatchGatewayReleasesResponse {
  EventType type = 1;
  GatewayRelease gateway_release = 2;
  string resource_id = 3;
}

service GatewayReleaseService {
  rpc GetGatewayRelease(GetGatewayReleaseRequest) returns (GetGatewayReleaseResponse);
  rpc CreateGatewayRelease(CreateGatewayReleaseRequest) returns (CreateGatewayReleaseResponse);
  rpc UpdateGatewayRelease(UpdateGatewayReleaseRequest) returns (UpdateGatewayReleaseResponse);
  rpc DeleteGatewayRelease(DeleteGatewayReleaseRequest) returns (DeleteGatewayReleaseResponse);
  rpc ListGatewayReleases(ListGatewayReleasesRequest) returns (ListGatewayReleasesResponse);
  rpc WatchGatewayReleases(WatchGatewayReleasesRequest) returns (stream WatchGatewayReleasesResponse);
}
