syntax = "proto3";

package hypershell.v1;

option go_package = "github.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1";

import "hypershell/v1/common.proto";

message GatewayNetwork {
  ObjectReference metadata = 1;
  string name = 2;
  string fleet_id = 3;
  optional string topology = 4;
  optional string tunnel_mode = 5;
  optional string hub_gateway_id = 6;
  optional string status = 7;
}

message CreateGatewayNetworkRequest {
  string name = 1;
  string fleet_id = 2;
  optional string topology = 3;
  optional string tunnel_mode = 4;
  optional string hub_gateway_id = 5;
  optional string status = 6;
}

message CreateGatewayNetworkResponse {
  GatewayNetwork gateway_network = 1;
}

message GetGatewayNetworkRequest {
  string id = 1;
}

message GetGatewayNetworkResponse {
  GatewayNetwork gateway_network = 1;
}

message UpdateGatewayNetworkRequest {
  string id = 1;
  optional string name = 2;
  optional string fleet_id = 3;
  optional string topology = 4;
  optional string tunnel_mode = 5;
  optional string hub_gateway_id = 6;
  optional string status = 7;
}

message UpdateGatewayNetworkResponse {
  GatewayNetwork gateway_network = 1;
}

message DeleteGatewayNetworkRequest {
  string id = 1;
}

message ListGatewayNetworksRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListGatewayNetworksResponse {
  repeated GatewayNetwork items = 1;
  ListMeta metadata = 2;
}

message DeleteGatewayNetworkResponse {}

message WatchGatewayNetworksRequest {}

message WatchGatewayNetworksResponse {
  EventType type = 1;
  GatewayNetwork gateway_network = 2;
  string resource_id = 3;
}

service GatewayNetworkService {
  rpc GetGatewayNetwork(GetGatewayNetworkRequest) returns (GetGatewayNetworkResponse);
  rpc CreateGatewayNetwork(CreateGatewayNetworkRequest) returns (CreateGatewayNetworkResponse);
  rpc UpdateGatewayNetwork(UpdateGatewayNetworkRequest) returns (UpdateGatewayNetworkResponse);
  rpc DeleteGatewayNetwork(DeleteGatewayNetworkRequest) returns (DeleteGatewayNetworkResponse);
  rpc ListGatewayNetworks(ListGatewayNetworksRequest) returns (ListGatewayNetworksResponse);
  rpc WatchGatewayNetworks(WatchGatewayNetworksRequest) returns (stream WatchGatewayNetworksResponse);
}
