syntax = "proto3";

package hypershell.v1;

option go_package = "github.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1";

import "hypershell/v1/common.proto";

message ManagedCluster {
  ObjectReference metadata = 1;
  string name = 2;
  reserved 3;
  reserved "fleet_id";
  string provider = 4;
  optional string region = 5;
  string kubeconfig_secret = 6;
  optional string status = 7;
  optional string api_server_url = 8;
  optional string profile_id = 9;
  optional string database_id = 10;
}

message CreateManagedClusterRequest {
  string name = 1;
  reserved 2;
  reserved "fleet_id";
  string provider = 3;
  optional string region = 4;
  string kubeconfig_secret = 5;
  optional string status = 6;
  optional string api_server_url = 7;
  optional string profile_id = 8;
  optional string database_id = 9;
}

message CreateManagedClusterResponse {
  ManagedCluster managed_cluster = 1;
}

message GetManagedClusterRequest {
  string id = 1;
}

message GetManagedClusterResponse {
  ManagedCluster managed_cluster = 1;
}

message UpdateManagedClusterRequest {
  string id = 1;
  optional string name = 2;
  reserved 3;
  reserved "fleet_id";
  optional string provider = 4;
  optional string region = 5;
  optional string kubeconfig_secret = 6;
  optional string status = 7;
  optional string api_server_url = 8;
  optional string profile_id = 9;
  optional string database_id = 10;
}

message UpdateManagedClusterResponse {
  ManagedCluster managed_cluster = 1;
}

message DeleteManagedClusterRequest {
  string id = 1;
}

message ListManagedClustersRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListManagedClustersResponse {
  repeated ManagedCluster items = 1;
  ListMeta metadata = 2;
}

message DeleteManagedClusterResponse {}

message WatchManagedClustersRequest {}

message WatchManagedClustersResponse {
  EventType type = 1;
  ManagedCluster managed_cluster = 2;
  string resource_id = 3;
}

service ManagedClusterService {
  rpc GetManagedCluster(GetManagedClusterRequest) returns (GetManagedClusterResponse);
  rpc CreateManagedCluster(CreateManagedClusterRequest) returns (CreateManagedClusterResponse);
  rpc UpdateManagedCluster(UpdateManagedClusterRequest) returns (UpdateManagedClusterResponse);
  rpc DeleteManagedCluster(DeleteManagedClusterRequest) returns (DeleteManagedClusterResponse);
  rpc ListManagedClusters(ListManagedClustersRequest) returns (ListManagedClustersResponse);
  rpc WatchManagedClusters(WatchManagedClustersRequest) returns (stream WatchManagedClustersResponse);
}
