syntax = "proto3";

package hypershell.v1;

option go_package = "github.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1";

import "hypershell/v1/common.proto";

message ManagedDatabase {
  ObjectReference metadata = 1;
  string name = 2;
  string fleet_id = 3;
  string provider = 4;
  optional string region = 5;
  optional string engine = 6;
  optional string engine_version = 7;
  optional string instance_class = 8;
  optional string connection_secret = 9;
  optional string status = 10;
  string namespace = 11;
}

message CreateManagedDatabaseRequest {
  string name = 1;
  string fleet_id = 2;
  string provider = 3;
  optional string region = 4;
  optional string engine = 5;
  optional string engine_version = 6;
  optional string instance_class = 7;
  optional string connection_secret = 8;
  optional string status = 9;
}

message CreateManagedDatabaseResponse {
  ManagedDatabase managed_database = 1;
}

message GetManagedDatabaseRequest {
  string id = 1;
}

message GetManagedDatabaseResponse {
  ManagedDatabase managed_database = 1;
}

message UpdateManagedDatabaseRequest {
  string id = 1;
  optional string name = 2;
  optional string fleet_id = 3;
  optional string provider = 4;
  optional string region = 5;
  optional string engine = 6;
  optional string engine_version = 7;
  optional string instance_class = 8;
  optional string connection_secret = 9;
  optional string status = 10;
}

message UpdateManagedDatabaseResponse {
  ManagedDatabase managed_database = 1;
}

message DeleteManagedDatabaseRequest {
  string id = 1;
}

message ListManagedDatabasesRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListManagedDatabasesResponse {
  repeated ManagedDatabase items = 1;
  ListMeta metadata = 2;
}

message DeleteManagedDatabaseResponse {}

message WatchManagedDatabasesRequest {}

message WatchManagedDatabasesResponse {
  EventType type = 1;
  ManagedDatabase managed_database = 2;
  string resource_id = 3;
}

service ManagedDatabaseService {
  rpc GetManagedDatabase(GetManagedDatabaseRequest) returns (GetManagedDatabaseResponse);
  rpc CreateManagedDatabase(CreateManagedDatabaseRequest) returns (CreateManagedDatabaseResponse);
  rpc UpdateManagedDatabase(UpdateManagedDatabaseRequest) returns (UpdateManagedDatabaseResponse);
  rpc DeleteManagedDatabase(DeleteManagedDatabaseRequest) returns (DeleteManagedDatabaseResponse);
  rpc ListManagedDatabases(ListManagedDatabasesRequest) returns (ListManagedDatabasesResponse);
  rpc WatchManagedDatabases(WatchManagedDatabasesRequest) returns (stream WatchManagedDatabasesResponse);
}
