// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: bdd81ace10ada1fc8d991b81deba36cb2ba1446202ad6da7dc0e8559396bcf68

import type { ObjectReference, ListMeta } from './base.js';

export type AgentRuntime = ObjectReference & {
  cluster_id: string;
  concurrency_policy: string;
  coordinator_image: string;
  cron: string;
  description: string;
  gateway_id: string;
  login_refresh_seconds: number;
  name: string;
  parameters: string;
  sandbox_template_id: string;
  status: string;
};

export type AgentRuntimeList = ListMeta & {
  items: AgentRuntime[];
};

export type AgentRuntimeCreateRequest = {
  cluster_id: string;
  concurrency_policy?: string;
  coordinator_image?: string;
  cron?: string;
  description?: string;
  gateway_id: string;
  login_refresh_seconds?: number;
  name: string;
  parameters?: string;
  sandbox_template_id?: string;
};

export type AgentRuntimePatchRequest = {
  concurrency_policy?: string;
  coordinator_image?: string;
  cron?: string;
  description?: string;
  login_refresh_seconds?: number;
  name?: string;
  parameters?: string;
  sandbox_template_id?: string;
};

export class AgentRuntimeBuilder {
  private data: Record<string, unknown> = {};


  clusterId(value: string): this {
    this.data['cluster_id'] = value;
    return this;
  }

  concurrencyPolicy(value: string): this {
    this.data['concurrency_policy'] = value;
    return this;
  }

  coordinatorImage(value: string): this {
    this.data['coordinator_image'] = value;
    return this;
  }

  cron(value: string): this {
    this.data['cron'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  gatewayId(value: string): this {
    this.data['gateway_id'] = value;
    return this;
  }

  loginRefreshSeconds(value: number): this {
    this.data['login_refresh_seconds'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  parameters(value: string): this {
    this.data['parameters'] = value;
    return this;
  }

  sandboxTemplateId(value: string): this {
    this.data['sandbox_template_id'] = value;
    return this;
  }

  build(): AgentRuntimeCreateRequest {
    if (!this.data['cluster_id']) {
      throw new Error('cluster_id is required');
    }
    if (!this.data['gateway_id']) {
      throw new Error('gateway_id is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as AgentRuntimeCreateRequest;
  }
}

export class AgentRuntimePatchBuilder {
  private data: Record<string, unknown> = {};


  concurrencyPolicy(value: string): this {
    this.data['concurrency_policy'] = value;
    return this;
  }

  coordinatorImage(value: string): this {
    this.data['coordinator_image'] = value;
    return this;
  }

  cron(value: string): this {
    this.data['cron'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  loginRefreshSeconds(value: number): this {
    this.data['login_refresh_seconds'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  parameters(value: string): this {
    this.data['parameters'] = value;
    return this;
  }

  sandboxTemplateId(value: string): this {
    this.data['sandbox_template_id'] = value;
    return this;
  }

  build(): AgentRuntimePatchRequest {
    return this.data as AgentRuntimePatchRequest;
  }
}
