// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 37bf7852f6962f87a1713717ae6e1880188293af803882fe018779408f5f888d

import type { SDKClientConfig } from './base.js';
import { GatewayAPI } from './gateway_api.js';
import { GatewayNetworkAPI } from './gateway_network_api.js';
import { GatewayReleaseAPI } from './gateway_release_api.js';
import { ManagedClusterAPI } from './managed_cluster_api.js';
import { ManagedDatabaseAPI } from './managed_database_api.js';
import { OpenShellGatewayServiceAccountAPI } from './open_shell_gateway_service_account_api.js';
import { RoleAPI } from './role_api.js';
import { RoleBindingAPI } from './role_binding_api.js';


export class SDKClient {
  private readonly config: SDKClientConfig;

  readonly gateways: GatewayAPI;
  readonly gatewayNetworks: GatewayNetworkAPI;
  readonly gatewayReleases: GatewayReleaseAPI;
  readonly managedClusters: ManagedClusterAPI;
  readonly managedDatabases: ManagedDatabaseAPI;
  readonly openShellGatewayServiceAccounts: OpenShellGatewayServiceAccountAPI;
  readonly roles: RoleAPI;
  readonly roleBindings: RoleBindingAPI;

  constructor(config: SDKClientConfig = {}) {
    if (config.token !== undefined && config.getToken !== undefined) {
      throw new Error('token and getToken are mutually exclusive');
    }

    this.config = {
      ...config,
      baseUrl: (config.baseUrl ?? '').replace(/\/+$/, ''),
    };

    this.gateways = new GatewayAPI(this.config);
    this.gatewayNetworks = new GatewayNetworkAPI(this.config);
    this.gatewayReleases = new GatewayReleaseAPI(this.config);
    this.managedClusters = new ManagedClusterAPI(this.config);
    this.managedDatabases = new ManagedDatabaseAPI(this.config);
    this.openShellGatewayServiceAccounts = new OpenShellGatewayServiceAccountAPI(this.config);
    this.roles = new RoleAPI(this.config);
    this.roleBindings = new RoleBindingAPI(this.config);
  }

  static fromEnv(): SDKClient {
    const env = (typeof globalThis !== 'undefined' && 'process' in globalThis
      ? (globalThis as Record<string, unknown>).process as { env: Record<string, string | undefined> }
      : { env: {} as Record<string, string | undefined> }).env;
    const baseUrl = env.API_URL || 'https://localhost:8000';
    const token = env.API_TOKEN;

    if (!token) {
      throw new Error('API_TOKEN environment variable is required');
    }

    return new SDKClient({ baseUrl, token });
  }
}
