// Code generated by trex-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 72699f542b3925de30a231f8bd80d1098cfb9a891065307d9c4649a7144337ce

import type { SDKClientConfig } from './base';
import { FleetAPI } from './fleet_api';
import { GatewayAPI } from './gateway_api';
import { GatewayNetworkAPI } from './gateway_network_api';
import { GatewayReleaseAPI } from './gateway_release_api';
import { ManagedClusterAPI } from './managed_cluster_api';
import { ManagedDatabaseAPI } from './managed_database_api';


export class SDKClient {
  private readonly config: SDKClientConfig;

  readonly fleets: FleetAPI;
  readonly gateways: GatewayAPI;
  readonly gatewayNetworks: GatewayNetworkAPI;
  readonly gatewayReleases: GatewayReleaseAPI;
  readonly managedClusters: ManagedClusterAPI;
  readonly managedDatabases: ManagedDatabaseAPI;

  constructor(config: SDKClientConfig) {
    if (!config.baseUrl) {
      throw new Error('baseUrl is required');
    }
    if (!config.token) {
      throw new Error('token is required');
    }

    this.config = {
      ...config,
      baseUrl: config.baseUrl.replace(/\/+$/, ''),
    };

    this.fleets = new FleetAPI(this.config);
    this.gateways = new GatewayAPI(this.config);
    this.gatewayNetworks = new GatewayNetworkAPI(this.config);
    this.gatewayReleases = new GatewayReleaseAPI(this.config);
    this.managedClusters = new ManagedClusterAPI(this.config);
    this.managedDatabases = new ManagedDatabaseAPI(this.config);
  }

  static fromEnv(): SDKClient {
    const baseUrl = process.env.API_URL || 'https://localhost:8000';
    const token = process.env.API_TOKEN;

    if (!token) {
      throw new Error('API_TOKEN environment variable is required');
    }

    return new SDKClient({ baseUrl, token });
  }
}
