// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 2729bb434158cd2fcd889ae589ced55e74740af810b6d4fd5b506123a2738d24

import type { SDKClientConfig } from './base.js';
import { FleetAPI } from './fleet_api.js';
import { GatewayAPI } from './gateway_api.js';
import { GatewayNetworkAPI } from './gateway_network_api.js';
import { GatewayReleaseAPI } from './gateway_release_api.js';
import { ManagedClusterAPI } from './managed_cluster_api.js';
import { ManagedDatabaseAPI } from './managed_database_api.js';
import { RoleAPI } from './role_api.js';
import { RoleBindingAPI } from './role_binding_api.js';


export class SDKClient {
  private readonly config: SDKClientConfig;

  readonly fleets: FleetAPI;
  readonly gateways: GatewayAPI;
  readonly gatewayNetworks: GatewayNetworkAPI;
  readonly gatewayReleases: GatewayReleaseAPI;
  readonly managedClusters: ManagedClusterAPI;
  readonly managedDatabases: ManagedDatabaseAPI;
  readonly roles: RoleAPI;
  readonly roleBindings: RoleBindingAPI;

  constructor(config: SDKClientConfig = {}) {
    if (config.token !== undefined && config.getToken !== undefined) {
      throw new Error('token and getToken are mutually exclusive');
    }

    this.config = {
      ...config,
      baseUrl: (config.baseUrl ?? '').replace(/\/+$/, ''),
    };

    this.fleets = new FleetAPI(this.config);
    this.gateways = new GatewayAPI(this.config);
    this.gatewayNetworks = new GatewayNetworkAPI(this.config);
    this.gatewayReleases = new GatewayReleaseAPI(this.config);
    this.managedClusters = new ManagedClusterAPI(this.config);
    this.managedDatabases = new ManagedDatabaseAPI(this.config);
    this.roles = new RoleAPI(this.config);
    this.roleBindings = new RoleBindingAPI(this.config);
  }

}
