// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: be8c162d67d99436a594d76babf7153b25120d483b905d6f3ae078cc64f3738c

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { Fleet, FleetList, FleetCreateRequest, FleetPatchRequest } from './fleet.js';

export class FleetAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: FleetCreateRequest, opts?: RequestOptions): Promise<Fleet> {
    return sdkFetch<Fleet>(this.config, 'POST', '/fleets', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Fleet> {
    return sdkFetch<Fleet>(this.config, 'GET', `/fleets/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<FleetList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<FleetList>(this.config, 'GET', `/fleets${qs}`, undefined, opts);
  }

  async update(id: string, patch: FleetPatchRequest, opts?: RequestOptions): Promise<Fleet> {
    return sdkFetch<Fleet>(this.config, 'PATCH', `/fleets/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/fleets/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Fleet> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
