// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 8f15132df91b8d925bbcc3d67a27060ae71b8acd018010232c596cb3c08d9937

import type { ObjectReference, ListMeta } from './base.js';

export type Fleet = ObjectReference & {
  description: string;
  name: string;
  status: string;
};

export type FleetList = ListMeta & {
  items: Fleet[];
};

export type FleetCreateRequest = {
  description?: string;
  name: string;
  status?: string;
};

export type FleetPatchRequest = {
  description?: string;
  name?: string;
  status?: string;
};

export class FleetBuilder {
  private data: Record<string, unknown> = {};


  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): FleetCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as FleetCreateRequest;
  }
}

export class FleetPatchBuilder {
  private data: Record<string, unknown> = {};


  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): FleetPatchRequest {
    return this.data as FleetPatchRequest;
  }
}

