// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 8f15132df91b8d925bbcc3d67a27060ae71b8acd018010232c596cb3c08d9937

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { Gateway, GatewayList, GatewayCreateRequest, GatewayPatchRequest } from './gateway.js';

export class GatewayAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: GatewayCreateRequest, opts?: RequestOptions): Promise<Gateway> {
    return sdkFetch<Gateway>(this.config, 'POST', '/gateways', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Gateway> {
    return sdkFetch<Gateway>(this.config, 'GET', `/gateways/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<GatewayList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<GatewayList>(this.config, 'GET', `/gateways${qs}`, undefined, opts);
  }

  async update(id: string, patch: GatewayPatchRequest, opts?: RequestOptions): Promise<Gateway> {
    return sdkFetch<Gateway>(this.config, 'PATCH', `/gateways/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/gateways/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Gateway> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
