// Code generated by trex-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 72699f542b3925de30a231f8bd80d1098cfb9a891065307d9c4649a7144337ce

import type { ObjectReference, ListMeta } from './base';

export type Gateway = ObjectReference & {
  cluster_id: string;
  database_id: string;
  external_dns: string;
  fleet_id: string;
  name: string;
  namespace: string;
  phase: string;
  release_id: string;
  service_type: string;
  status: string;
  tls_mode: string;
};

export type GatewayList = ListMeta & {
  items: Gateway[];
};

export type GatewayCreateRequest = {
  cluster_id: string;
  database_id: string;
  external_dns?: string;
  fleet_id: string;
  name: string;
  namespace: string;
  phase?: string;
  release_id: string;
  service_type?: string;
  status?: string;
  tls_mode?: string;
};

export type GatewayPatchRequest = {
  cluster_id?: string;
  database_id?: string;
  external_dns?: string;
  fleet_id?: string;
  name?: string;
  namespace?: string;
  phase?: string;
  release_id?: string;
  service_type?: string;
  status?: string;
  tls_mode?: string;
};

export class GatewayBuilder {
  private data: Record<string, unknown> = {};


  clusterId(value: string): this {
    this.data['cluster_id'] = value;
    return this;
  }

  databaseId(value: string): this {
    this.data['database_id'] = value;
    return this;
  }

  externalDns(value: string): this {
    this.data['external_dns'] = value;
    return this;
  }

  fleetId(value: string): this {
    this.data['fleet_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  releaseId(value: string): this {
    this.data['release_id'] = value;
    return this;
  }

  serviceType(value: string): this {
    this.data['service_type'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  tlsMode(value: string): this {
    this.data['tls_mode'] = value;
    return this;
  }

  build(): GatewayCreateRequest {
    if (!this.data['cluster_id']) {
      throw new Error('cluster_id is required');
    }
    if (!this.data['database_id']) {
      throw new Error('database_id is required');
    }
    if (!this.data['fleet_id']) {
      throw new Error('fleet_id is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['namespace']) {
      throw new Error('namespace is required');
    }
    if (!this.data['release_id']) {
      throw new Error('release_id is required');
    }
    return this.data as GatewayCreateRequest;
  }
}

export class GatewayPatchBuilder {
  private data: Record<string, unknown> = {};


  clusterId(value: string): this {
    this.data['cluster_id'] = value;
    return this;
  }

  databaseId(value: string): this {
    this.data['database_id'] = value;
    return this;
  }

  externalDns(value: string): this {
    this.data['external_dns'] = value;
    return this;
  }

  fleetId(value: string): this {
    this.data['fleet_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  namespace(value: string): this {
    this.data['namespace'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  releaseId(value: string): this {
    this.data['release_id'] = value;
    return this;
  }

  serviceType(value: string): this {
    this.data['service_type'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  tlsMode(value: string): this {
    this.data['tls_mode'] = value;
    return this;
  }

  build(): GatewayPatchRequest {
    return this.data as GatewayPatchRequest;
  }
}
