// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: f9a7f9e6f68c4c50cda14c134b406761756e203747912d4e457dee64d0a3f082

import type { SDKClientConfig, RequestOptions } from './base.js';
import { sdkFetch } from './base.js';
import type {
  GatewayAccessGrantRequest,
  GatewayAccessGrantResponse,
  GatewayAccessListItem,
  GatewayAccessList,
  GatewayAccessChangeRoleRequest,
  GatewayDirectoryUserList,
  GatewayAccessListOptions,
} from './gateway_access.js';

export class GatewayAccessAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(gatewayId: string, data: GatewayAccessGrantRequest, opts?: RequestOptions): Promise<GatewayAccessGrantResponse> {
    return sdkFetch<GatewayAccessGrantResponse>(this.config, 'POST', `/api/hypershell/v1/gateways/${encodeURIComponent(gatewayId)}/access`, data, opts);
  }

  async list(gatewayId: string, listOpts?: GatewayAccessListOptions, opts?: RequestOptions): Promise<GatewayAccessList> {
    const params = new URLSearchParams();
    if (listOpts?.page !== undefined) {
      params.set('page', String(listOpts.page));
    }
    if (listOpts?.size !== undefined) {
      params.set('size', String(Math.min(listOpts.size, 100)));
    }
    if (listOpts?.role !== undefined) {
      params.set('role', String(listOpts.role));
    }
    if (listOpts?.search !== undefined && listOpts.search !== '') {
      params.set('search', String(listOpts.search));
    }
    if (listOpts?.sort !== undefined) {
      params.set('sort', String(listOpts.sort));
    }
    if (listOpts?.order !== undefined) {
      params.set('order', String(listOpts.order));
    }
    const query = params.toString();
    const path = `/api/hypershell/v1/gateways/${encodeURIComponent(gatewayId)}/access` + (query ? `?${query}` : '');
    return sdkFetch<GatewayAccessList>(this.config, 'GET', path, undefined, opts);
  }

  async delete(gatewayId: string, userId: string, opts?: RequestOptions): Promise<GatewayAccessListItem | undefined> {
    return sdkFetch<GatewayAccessListItem | undefined>(this.config, 'DELETE', `/api/hypershell/v1/gateways/${encodeURIComponent(gatewayId)}/access/${encodeURIComponent(userId)}`, undefined, opts);
  }

  async update(gatewayId: string, userId: string, data: GatewayAccessChangeRoleRequest, opts?: RequestOptions): Promise<GatewayAccessGrantResponse> {
    return sdkFetch<GatewayAccessGrantResponse>(this.config, 'PATCH', `/api/hypershell/v1/gateways/${encodeURIComponent(gatewayId)}/access/${encodeURIComponent(userId)}`, data, opts);
  }

  async searchDirectory(gatewayId: string, search?: string, opts?: RequestOptions): Promise<GatewayDirectoryUserList> {
    const params = new URLSearchParams();
    if (search !== undefined && search !== '') {
      params.set('search', search);
    }
    const query = params.toString();
    const path = `/api/hypershell/v1/gateways/${encodeURIComponent(gatewayId)}/access/directory` + (query ? `?${query}` : '');
    return sdkFetch<GatewayDirectoryUserList>(this.config, 'GET', path, undefined, opts);
  }

  async *listAll(gatewayId: string, size: number = 20, opts?: RequestOptions): AsyncGenerator<GatewayAccessListItem> {
    let page = 1;
    while (true) {
      const result = await this.list(gatewayId, { page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
