// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: f167deec2ad52601ab466f825250c536e29bab9f99ad0d3c4cb69cfe4c554028


export type GatewayAccessCapabilities = {
  caller_role?: GatewayAccessRole;
  can_manage_access: boolean;
  can_manage_owners: boolean;
};



export type GatewayAccessChangeRoleRequest = {
  role: GatewayAccessRole;
};



export type GatewayAccessGrantRequest = {
  role: GatewayAccessRole;
  subject?: string;
  username: string;
};



export type GatewayAccessGrantResponse = {
  email?: string | null;
  granted_at: string;
  is_creator: boolean;
  name?: string | null;
  role: GatewayAccessRole;
  role_binding_id: string;
  user_id: string;
  username: string;
};



export type GatewayAccessList = {
  capabilities: GatewayAccessCapabilities;
  items: GatewayAccessListItem[];
  page: number;
  size: number;
  total: number;
};



export type GatewayAccessListItem = {
  email?: string | null;
  granted_at: string;
  is_creator: boolean;
  name?: string | null;
  role: GatewayAccessRole;
  role_binding_id: string;
  user_id: string;
  username: string;
};



export type GatewayAccessRole = 'owner' | 'admin' | 'user';



export type GatewayDirectoryUser = {
  email?: string | null;
  name?: string | null;
  subject?: string | null;
  username: string;
};



export type GatewayDirectoryUserList = {
  items: GatewayDirectoryUser[];
};


export type GatewayAccessListOptions = {
  page?: number;
  size?: number;
  role?: GatewayAccessRole;
  search?: string;
  sort?: "username" | "name" | "role" | "granted_at";
  order?: "asc" | "desc";
};
