// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 3357e5c6c174a2027a1d481b0639adec25327496e1b3fceaaeb4c98ede728f30

import type { ObjectReference, ListMeta } from './base.js';

export type GatewayNetwork = ObjectReference & {
  fleet_id: string;
  hub_gateway_id: string;
  name: string;
  status: string;
  topology: string;
  tunnel_mode: string;
};

export type GatewayNetworkList = ListMeta & {
  items: GatewayNetwork[];
};

export type GatewayNetworkCreateRequest = {
  fleet_id: string;
  hub_gateway_id?: string;
  name: string;
  status?: string;
  topology?: string;
  tunnel_mode?: string;
};

export type GatewayNetworkPatchRequest = {
  fleet_id?: string;
  hub_gateway_id?: string;
  name?: string;
  status?: string;
  topology?: string;
  tunnel_mode?: string;
};

export class GatewayNetworkBuilder {
  private data: Record<string, unknown> = {};


  fleetId(value: string): this {
    this.data['fleet_id'] = value;
    return this;
  }

  hubGatewayId(value: string): this {
    this.data['hub_gateway_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  topology(value: string): this {
    this.data['topology'] = value;
    return this;
  }

  tunnelMode(value: string): this {
    this.data['tunnel_mode'] = value;
    return this;
  }

  build(): GatewayNetworkCreateRequest {
    if (!this.data['fleet_id']) {
      throw new Error('fleet_id is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as GatewayNetworkCreateRequest;
  }
}

export class GatewayNetworkPatchBuilder {
  private data: Record<string, unknown> = {};


  fleetId(value: string): this {
    this.data['fleet_id'] = value;
    return this;
  }

  hubGatewayId(value: string): this {
    this.data['hub_gateway_id'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  topology(value: string): this {
    this.data['topology'] = value;
    return this;
  }

  tunnelMode(value: string): this {
    this.data['tunnel_mode'] = value;
    return this;
  }

  build(): GatewayNetworkPatchRequest {
    return this.data as GatewayNetworkPatchRequest;
  }
}
