// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: c680d033b0f6ae56d5d8a6b7d3deed318b1c775ebea67a5d637d75a87caa6dab

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { GatewayProfile, GatewayProfileList, GatewayProfileCreateRequest, GatewayProfilePatchRequest } from './gateway_profile.js';

export class GatewayProfileAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: GatewayProfileCreateRequest, opts?: RequestOptions): Promise<GatewayProfile> {
    return sdkFetch<GatewayProfile>(this.config, 'POST', '/gateway_profiles', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<GatewayProfile> {
    return sdkFetch<GatewayProfile>(this.config, 'GET', `/gateway_profiles/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<GatewayProfileList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<GatewayProfileList>(this.config, 'GET', `/gateway_profiles${qs}`, undefined, opts);
  }

  async update(id: string, patch: GatewayProfilePatchRequest, opts?: RequestOptions): Promise<GatewayProfile> {
    return sdkFetch<GatewayProfile>(this.config, 'PATCH', `/gateway_profiles/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/gateway_profiles/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<GatewayProfile> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
