// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: b7d72550ecb9d1e0bb7cbfc9cf368c8d64b932e3be2eb8cc12b95d81f08f9405

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { InferenceRoute, InferenceRouteList, InferenceRouteCreateRequest } from './inference_route.js';

export class InferenceRouteAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: InferenceRouteCreateRequest, opts?: RequestOptions): Promise<InferenceRoute> {
    return sdkFetch<InferenceRoute>(this.config, 'POST', '/inference_routes', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<InferenceRoute> {
    return sdkFetch<InferenceRoute>(this.config, 'GET', `/inference_routes/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<InferenceRouteList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<InferenceRouteList>(this.config, 'GET', `/inference_routes${qs}`, undefined, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/inference_routes/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<InferenceRoute> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
