// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: e6bcd9eeb2b0f1844ca3cefb9576ac8b1acb78c6d19e0a83166f2a3c8acfdbd2

import type { ObjectReference, ListMeta } from './base.js';

export type InferenceRoute = ObjectReference & {
  model: string;
  provider_binding_id: string;
  workspace_id: string;
};

export type InferenceRouteList = ListMeta & {
  items: InferenceRoute[];
};

export type InferenceRouteCreateRequest = {
  model: string;
  provider_binding_id: string;
  workspace_id: string;
};

export type InferenceRoutePatchRequest = {
};

export class InferenceRouteBuilder {
  private data: Record<string, unknown> = {};


  model(value: string): this {
    this.data['model'] = value;
    return this;
  }

  providerBindingId(value: string): this {
    this.data['provider_binding_id'] = value;
    return this;
  }

  workspaceId(value: string): this {
    this.data['workspace_id'] = value;
    return this;
  }

  build(): InferenceRouteCreateRequest {
    if (!this.data['model']) {
      throw new Error('model is required');
    }
    if (!this.data['provider_binding_id']) {
      throw new Error('provider_binding_id is required');
    }
    if (!this.data['workspace_id']) {
      throw new Error('workspace_id is required');
    }
    return this.data as InferenceRouteCreateRequest;
  }
}

export class InferenceRoutePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): InferenceRoutePatchRequest {
    return this.data as InferenceRoutePatchRequest;
  }
}
