// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 8f15132df91b8d925bbcc3d67a27060ae71b8acd018010232c596cb3c08d9937

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { ManagedDatabase, ManagedDatabaseList, ManagedDatabaseCreateRequest, ManagedDatabasePatchRequest } from './managed_database.js';

export class ManagedDatabaseAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: ManagedDatabaseCreateRequest, opts?: RequestOptions): Promise<ManagedDatabase> {
    return sdkFetch<ManagedDatabase>(this.config, 'POST', '/managed_databases', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ManagedDatabase> {
    return sdkFetch<ManagedDatabase>(this.config, 'GET', `/managed_databases/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ManagedDatabaseList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<ManagedDatabaseList>(this.config, 'GET', `/managed_databases${qs}`, undefined, opts);
  }

  async update(id: string, patch: ManagedDatabasePatchRequest, opts?: RequestOptions): Promise<ManagedDatabase> {
    return sdkFetch<ManagedDatabase>(this.config, 'PATCH', `/managed_databases/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/managed_databases/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ManagedDatabase> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
