// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: c680d033b0f6ae56d5d8a6b7d3deed318b1c775ebea67a5d637d75a87caa6dab

import type { ObjectReference, ListMeta } from './base.js';

export type ManagedDatabase = ObjectReference & {
  connection_secret: string;
  engine: string;
  engine_version: string;
  instance_class: string;
  name: string;
  namespace: string;
  provider: string;
  region: string;
  status: string;
};

export type ManagedDatabaseList = ListMeta & {
  items: ManagedDatabase[];
};

export type ManagedDatabaseCreateRequest = {
  connection_secret?: string;
  engine?: string;
  engine_version?: string;
  instance_class?: string;
  name: string;
  provider: string;
  region?: string;
  status?: string;
};

export type ManagedDatabasePatchRequest = {
  connection_secret?: string;
  engine?: string;
  engine_version?: string;
  instance_class?: string;
  name?: string;
  provider?: string;
  region?: string;
  status?: string;
};

export class ManagedDatabaseBuilder {
  private data: Record<string, unknown> = {};


  connectionSecret(value: string): this {
    this.data['connection_secret'] = value;
    return this;
  }

  engine(value: string): this {
    this.data['engine'] = value;
    return this;
  }

  engineVersion(value: string): this {
    this.data['engine_version'] = value;
    return this;
  }

  instanceClass(value: string): this {
    this.data['instance_class'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  region(value: string): this {
    this.data['region'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ManagedDatabaseCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['provider']) {
      throw new Error('provider is required');
    }
    return this.data as ManagedDatabaseCreateRequest;
  }
}

export class ManagedDatabasePatchBuilder {
  private data: Record<string, unknown> = {};


  connectionSecret(value: string): this {
    this.data['connection_secret'] = value;
    return this;
  }

  engine(value: string): this {
    this.data['engine'] = value;
    return this;
  }

  engineVersion(value: string): this {
    this.data['engine_version'] = value;
    return this;
  }

  instanceClass(value: string): this {
    this.data['instance_class'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  region(value: string): this {
    this.data['region'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ManagedDatabasePatchRequest {
    return this.data as ManagedDatabasePatchRequest;
  }
}
