// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 362a6e78860ff6da7343d12732c5e76e48d2bf479e176535f39bf8bb8fc4d389

import type { ObjectReference, ListMeta } from './base.js';

export type ProviderBinding = ObjectReference & {
  name: string;
  provider_spec_id: string;
  refresh_strategy: string;
  secret_source_id: string;
  status: string;
  workspace_id: string;
};

export type ProviderBindingList = ListMeta & {
  items: ProviderBinding[];
};

export type ProviderBindingCreateRequest = {
  name: string;
  provider_spec_id: string;
  refresh_strategy?: string;
  secret_source_id?: string;
  workspace_id: string;
};

export type ProviderBindingPatchRequest = {
  name?: string;
  refresh_strategy?: string;
  secret_source_id?: string;
};

export class ProviderBindingBuilder {
  private data: Record<string, unknown> = {};


  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  providerSpecId(value: string): this {
    this.data['provider_spec_id'] = value;
    return this;
  }

  refreshStrategy(value: string): this {
    this.data['refresh_strategy'] = value;
    return this;
  }

  secretSourceId(value: string): this {
    this.data['secret_source_id'] = value;
    return this;
  }

  workspaceId(value: string): this {
    this.data['workspace_id'] = value;
    return this;
  }

  build(): ProviderBindingCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['provider_spec_id']) {
      throw new Error('provider_spec_id is required');
    }
    if (!this.data['workspace_id']) {
      throw new Error('workspace_id is required');
    }
    return this.data as ProviderBindingCreateRequest;
  }
}

export class ProviderBindingPatchBuilder {
  private data: Record<string, unknown> = {};


  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  refreshStrategy(value: string): this {
    this.data['refresh_strategy'] = value;
    return this;
  }

  secretSourceId(value: string): this {
    this.data['secret_source_id'] = value;
    return this;
  }

  build(): ProviderBindingPatchRequest {
    return this.data as ProviderBindingPatchRequest;
  }
}
