// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: e6bcd9eeb2b0f1844ca3cefb9576ac8b1acb78c6d19e0a83166f2a3c8acfdbd2

import type { ObjectReference, ListMeta } from './base.js';

export type ProviderSpec = ObjectReference & {
  capability: string;
  category: string;
  name: string;
  profile: string;
  status: string;
};

export type ProviderSpecList = ListMeta & {
  items: ProviderSpec[];
};

export type ProviderSpecCreateRequest = {
  capability?: string;
  category: string;
  name: string;
  profile?: string;
};

export type ProviderSpecPatchRequest = {
  capability?: string;
  name?: string;
  profile?: string;
};

export class ProviderSpecBuilder {
  private data: Record<string, unknown> = {};


  capability(value: string): this {
    this.data['capability'] = value;
    return this;
  }

  category(value: string): this {
    this.data['category'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  profile(value: string): this {
    this.data['profile'] = value;
    return this;
  }

  build(): ProviderSpecCreateRequest {
    if (!this.data['category']) {
      throw new Error('category is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as ProviderSpecCreateRequest;
  }
}

export class ProviderSpecPatchBuilder {
  private data: Record<string, unknown> = {};


  capability(value: string): this {
    this.data['capability'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  profile(value: string): this {
    this.data['profile'] = value;
    return this;
  }

  build(): ProviderSpecPatchRequest {
    return this.data as ProviderSpecPatchRequest;
  }
}
