// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: f167deec2ad52601ab466f825250c536e29bab9f99ad0d3c4cb69cfe4c554028

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { ProviderSpec, ProviderSpecList, ProviderSpecCreateRequest, ProviderSpecPatchRequest } from './provider_spec.js';

export class ProviderSpecAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: ProviderSpecCreateRequest, opts?: RequestOptions): Promise<ProviderSpec> {
    return sdkFetch<ProviderSpec>(this.config, 'POST', '/provider_specs', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ProviderSpec> {
    return sdkFetch<ProviderSpec>(this.config, 'GET', `/provider_specs/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ProviderSpecList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<ProviderSpecList>(this.config, 'GET', `/provider_specs${qs}`, undefined, opts);
  }

  async update(id: string, patch: ProviderSpecPatchRequest, opts?: RequestOptions): Promise<ProviderSpec> {
    return sdkFetch<ProviderSpec>(this.config, 'PATCH', `/provider_specs/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/provider_specs/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ProviderSpec> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
