// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: ../../components/api-server/openapi/openapi.yaml
// Spec SHA256: be86b44c08b00541e20c5a4ad8d96ee165589b8470705f045174af08d44865c1
// Generated: 1970-01-01T00:00:00Z

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { Role, RoleList, RoleCreateRequest } from './role.js';

export class RoleAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: RoleCreateRequest, opts?: RequestOptions): Promise<Role> {
    return sdkFetch<Role>(this.config, 'POST', '/roles', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Role> {
    return sdkFetch<Role>(this.config, 'GET', `/roles/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<RoleList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<RoleList>(this.config, 'GET', `/roles${qs}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Role> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
