// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: b7d72550ecb9d1e0bb7cbfc9cf368c8d64b932e3be2eb8cc12b95d81f08f9405

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { SecretSource, SecretSourceList, SecretSourceCreateRequest, SecretSourcePatchRequest } from './secret_source.js';

export class SecretSourceAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: SecretSourceCreateRequest, opts?: RequestOptions): Promise<SecretSource> {
    return sdkFetch<SecretSource>(this.config, 'POST', '/secret_sources', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<SecretSource> {
    return sdkFetch<SecretSource>(this.config, 'GET', `/secret_sources/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SecretSourceList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<SecretSourceList>(this.config, 'GET', `/secret_sources${qs}`, undefined, opts);
  }

  async update(id: string, patch: SecretSourcePatchRequest, opts?: RequestOptions): Promise<SecretSource> {
    return sdkFetch<SecretSource>(this.config, 'PATCH', `/secret_sources/${id}`, patch, opts);
  }


  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return sdkFetch<void>(this.config, 'DELETE', `/secret_sources/${id}`, undefined, opts);
  }


  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<SecretSource> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
