// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: e6bcd9eeb2b0f1844ca3cefb9576ac8b1acb78c6d19e0a83166f2a3c8acfdbd2

import type { SDKClientConfig, ListOptions, RequestOptions } from './base.js';
import { sdkFetch, buildQueryString } from './base.js';
import type { User, UserList, UserCreateRequest } from './user.js';

export class UserAPI {
  constructor(private readonly config: SDKClientConfig) {}

  async create(data: UserCreateRequest, opts?: RequestOptions): Promise<User> {
    return sdkFetch<User>(this.config, 'POST', '/api/hypershell/v1/users', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<User> {
    return sdkFetch<User>(this.config, 'GET', `/api/hypershell/v1/users/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<UserList> {
    const qs = buildQueryString(listOpts);
    return sdkFetch<UserList>(this.config, 'GET', `/api/hypershell/v1/users${qs}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<User> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
