FROM registry.access.redhat.com/hi/go:1.26.5-builder@sha256:aef155087940a9221c59ca48ad8af371a4c1a46b05f0283737149cb00ef484b3 AS go-toolchain

FROM openapitools/openapi-generator-cli:v7.24.0@sha256:5bf3dc75f764c584da8e3344c51b2f3f1e74703461d46a035b5ac1d31515cc88

COPY --from=go-toolchain /usr/lib/golang/bin/gofmt /usr/local/bin/gofmt

RUN mkdir -p /local
COPY . /local

ENV CGO_ENABLED=0

WORKDIR /local

RUN bash /usr/local/bin/docker-entrypoint.sh generate -i /local/openapi/openapi.yaml -g go -o /local/pkg/api/openapi
RUN rm /local/pkg/api/openapi/go.mod /local/pkg/api/openapi/go.sum
RUN rm -rf /local/pkg/api/openapi/test
RUN gofmt -w /local/pkg/api/openapi
