FROM golang:1.26.5-bookworm@sha256:1ecb7edf62a0408027bd5729dfd6b1b8766e578e8df93995b225dfd0944eb651 AS go-toolchain

FROM openapitools/openapi-generator-cli:v7.16.0@sha256:e56372add5e038753fb91aa1bbb470724ef58382fdfc35082bf1b3e079ce353c

COPY --from=go-toolchain /usr/local/go/bin/gofmt /usr/local/bin/gofmt

RUN mkdir -p /local
COPY . /local

ENV CGO_ENABLED=0

WORKDIR /local

RUN bash /usr/local/bin/docker-entrypoint.sh generate -i /local/openapi/openapi.yaml -g go -o /local/pkg/api/openapi
RUN rm /local/pkg/api/openapi/go.mod /local/pkg/api/openapi/go.sum
RUN rm -rf /local/pkg/api/openapi/test
RUN gofmt -w /local/pkg/api/openapi
