apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-database-admin
  namespace: hypershell-system
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gateway-databases
  target:
    name: gateway-database-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        sslmode: verify-full
  dataFrom:
    - extract:
        key: hypershell/production/gateway-database
