/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedClusterRegistrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedClusterRegistrationRequest{}

// ManagedClusterRegistrationRequest struct for ManagedClusterRegistrationRequest
type ManagedClusterRegistrationRequest struct {
	// Human-readable spoke name, unique per fleet (e.g. hyp0-mc1). Must match on every subsequent call.
	Name string `json:"name"`
	// Optional description of the spoke.
	Description *string `json:"description,omitempty"`
}

type _ManagedClusterRegistrationRequest ManagedClusterRegistrationRequest

// NewManagedClusterRegistrationRequest instantiates a new ManagedClusterRegistrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedClusterRegistrationRequest(name string) *ManagedClusterRegistrationRequest {
	this := ManagedClusterRegistrationRequest{}
	this.Name = name
	return &this
}

// NewManagedClusterRegistrationRequestWithDefaults instantiates a new ManagedClusterRegistrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedClusterRegistrationRequestWithDefaults() *ManagedClusterRegistrationRequest {
	this := ManagedClusterRegistrationRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ManagedClusterRegistrationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ManagedClusterRegistrationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ManagedClusterRegistrationRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ManagedClusterRegistrationRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedClusterRegistrationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ManagedClusterRegistrationRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ManagedClusterRegistrationRequest) SetDescription(v string) {
	o.Description = &v
}

func (o ManagedClusterRegistrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedClusterRegistrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *ManagedClusterRegistrationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedClusterRegistrationRequest := _ManagedClusterRegistrationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedClusterRegistrationRequest)

	if err != nil {
		return err
	}

	*o = ManagedClusterRegistrationRequest(varManagedClusterRegistrationRequest)

	return err
}

type NullableManagedClusterRegistrationRequest struct {
	value *ManagedClusterRegistrationRequest
	isSet bool
}

func (v NullableManagedClusterRegistrationRequest) Get() *ManagedClusterRegistrationRequest {
	return v.value
}

func (v *NullableManagedClusterRegistrationRequest) Set(val *ManagedClusterRegistrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedClusterRegistrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedClusterRegistrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedClusterRegistrationRequest(val *ManagedClusterRegistrationRequest) *NullableManagedClusterRegistrationRequest {
	return &NullableManagedClusterRegistrationRequest{value: val, isSet: true}
}

func (v NullableManagedClusterRegistrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedClusterRegistrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
