/*
HyperShell API

HyperShell fleet management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OpenShellGatewayServiceAccountCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenShellGatewayServiceAccountCapabilities{}

// OpenShellGatewayServiceAccountCapabilities struct for OpenShellGatewayServiceAccountCapabilities
type OpenShellGatewayServiceAccountCapabilities struct {
	CanCreate        bool                                           `json:"can_create"`
	AllowedRoles     []OpenShellGatewayServiceAccountRole           `json:"allowed_roles"`
	CanManageAll     bool                                           `json:"can_manage_all"`
	ExpirationPolicy OpenShellGatewayServiceAccountExpirationPolicy `json:"expiration_policy"`
}

type _OpenShellGatewayServiceAccountCapabilities OpenShellGatewayServiceAccountCapabilities

// NewOpenShellGatewayServiceAccountCapabilities instantiates a new OpenShellGatewayServiceAccountCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenShellGatewayServiceAccountCapabilities(canCreate bool, allowedRoles []OpenShellGatewayServiceAccountRole, canManageAll bool, expirationPolicy OpenShellGatewayServiceAccountExpirationPolicy) *OpenShellGatewayServiceAccountCapabilities {
	this := OpenShellGatewayServiceAccountCapabilities{}
	this.CanCreate = canCreate
	this.AllowedRoles = allowedRoles
	this.CanManageAll = canManageAll
	this.ExpirationPolicy = expirationPolicy
	return &this
}

// NewOpenShellGatewayServiceAccountCapabilitiesWithDefaults instantiates a new OpenShellGatewayServiceAccountCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenShellGatewayServiceAccountCapabilitiesWithDefaults() *OpenShellGatewayServiceAccountCapabilities {
	this := OpenShellGatewayServiceAccountCapabilities{}
	return &this
}

// GetCanCreate returns the CanCreate field value
func (o *OpenShellGatewayServiceAccountCapabilities) GetCanCreate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCreate
}

// GetCanCreateOk returns a tuple with the CanCreate field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCapabilities) GetCanCreateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCreate, true
}

// SetCanCreate sets field value
func (o *OpenShellGatewayServiceAccountCapabilities) SetCanCreate(v bool) {
	o.CanCreate = v
}

// GetAllowedRoles returns the AllowedRoles field value
func (o *OpenShellGatewayServiceAccountCapabilities) GetAllowedRoles() []OpenShellGatewayServiceAccountRole {
	if o == nil {
		var ret []OpenShellGatewayServiceAccountRole
		return ret
	}

	return o.AllowedRoles
}

// GetAllowedRolesOk returns a tuple with the AllowedRoles field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCapabilities) GetAllowedRolesOk() ([]OpenShellGatewayServiceAccountRole, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedRoles, true
}

// SetAllowedRoles sets field value
func (o *OpenShellGatewayServiceAccountCapabilities) SetAllowedRoles(v []OpenShellGatewayServiceAccountRole) {
	o.AllowedRoles = v
}

// GetCanManageAll returns the CanManageAll field value
func (o *OpenShellGatewayServiceAccountCapabilities) GetCanManageAll() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanManageAll
}

// GetCanManageAllOk returns a tuple with the CanManageAll field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCapabilities) GetCanManageAllOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanManageAll, true
}

// SetCanManageAll sets field value
func (o *OpenShellGatewayServiceAccountCapabilities) SetCanManageAll(v bool) {
	o.CanManageAll = v
}

// GetExpirationPolicy returns the ExpirationPolicy field value
func (o *OpenShellGatewayServiceAccountCapabilities) GetExpirationPolicy() OpenShellGatewayServiceAccountExpirationPolicy {
	if o == nil {
		var ret OpenShellGatewayServiceAccountExpirationPolicy
		return ret
	}

	return o.ExpirationPolicy
}

// GetExpirationPolicyOk returns a tuple with the ExpirationPolicy field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCapabilities) GetExpirationPolicyOk() (*OpenShellGatewayServiceAccountExpirationPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationPolicy, true
}

// SetExpirationPolicy sets field value
func (o *OpenShellGatewayServiceAccountCapabilities) SetExpirationPolicy(v OpenShellGatewayServiceAccountExpirationPolicy) {
	o.ExpirationPolicy = v
}

func (o OpenShellGatewayServiceAccountCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenShellGatewayServiceAccountCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["can_create"] = o.CanCreate
	toSerialize["allowed_roles"] = o.AllowedRoles
	toSerialize["can_manage_all"] = o.CanManageAll
	toSerialize["expiration_policy"] = o.ExpirationPolicy
	return toSerialize, nil
}

func (o *OpenShellGatewayServiceAccountCapabilities) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"can_create",
		"allowed_roles",
		"can_manage_all",
		"expiration_policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenShellGatewayServiceAccountCapabilities := _OpenShellGatewayServiceAccountCapabilities{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenShellGatewayServiceAccountCapabilities)

	if err != nil {
		return err
	}

	*o = OpenShellGatewayServiceAccountCapabilities(varOpenShellGatewayServiceAccountCapabilities)

	return err
}

type NullableOpenShellGatewayServiceAccountCapabilities struct {
	value *OpenShellGatewayServiceAccountCapabilities
	isSet bool
}

func (v NullableOpenShellGatewayServiceAccountCapabilities) Get() *OpenShellGatewayServiceAccountCapabilities {
	return v.value
}

func (v *NullableOpenShellGatewayServiceAccountCapabilities) Set(val *OpenShellGatewayServiceAccountCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenShellGatewayServiceAccountCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenShellGatewayServiceAccountCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenShellGatewayServiceAccountCapabilities(val *OpenShellGatewayServiceAccountCapabilities) *NullableOpenShellGatewayServiceAccountCapabilities {
	return &NullableOpenShellGatewayServiceAccountCapabilities{value: val, isSet: true}
}

func (v NullableOpenShellGatewayServiceAccountCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenShellGatewayServiceAccountCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
