/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentRuntimePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRuntimePatchRequest{}

// AgentRuntimePatchRequest struct for AgentRuntimePatchRequest
type AgentRuntimePatchRequest struct {
	Name                *string `json:"name,omitempty"`
	SandboxTemplateId   *string `json:"sandbox_template_id,omitempty"`
	Description         *string `json:"description,omitempty"`
	Cron                *string `json:"cron,omitempty"`
	CoordinatorImage    *string `json:"coordinator_image,omitempty"`
	ConcurrencyPolicy   *string `json:"concurrency_policy,omitempty"`
	LoginRefreshSeconds *int32  `json:"login_refresh_seconds,omitempty"`
	Parameters          *string `json:"parameters,omitempty"`
}

// NewAgentRuntimePatchRequest instantiates a new AgentRuntimePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRuntimePatchRequest() *AgentRuntimePatchRequest {
	this := AgentRuntimePatchRequest{}
	return &this
}

// NewAgentRuntimePatchRequestWithDefaults instantiates a new AgentRuntimePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentRuntimePatchRequestWithDefaults() *AgentRuntimePatchRequest {
	this := AgentRuntimePatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentRuntimePatchRequest) SetName(v string) {
	o.Name = &v
}

// GetSandboxTemplateId returns the SandboxTemplateId field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetSandboxTemplateId() string {
	if o == nil || IsNil(o.SandboxTemplateId) {
		var ret string
		return ret
	}
	return *o.SandboxTemplateId
}

// GetSandboxTemplateIdOk returns a tuple with the SandboxTemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetSandboxTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxTemplateId) {
		return nil, false
	}
	return o.SandboxTemplateId, true
}

// HasSandboxTemplateId returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasSandboxTemplateId() bool {
	if o != nil && !IsNil(o.SandboxTemplateId) {
		return true
	}

	return false
}

// SetSandboxTemplateId gets a reference to the given string and assigns it to the SandboxTemplateId field.
func (o *AgentRuntimePatchRequest) SetSandboxTemplateId(v string) {
	o.SandboxTemplateId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentRuntimePatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCron returns the Cron field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetCron() string {
	if o == nil || IsNil(o.Cron) {
		var ret string
		return ret
	}
	return *o.Cron
}

// GetCronOk returns a tuple with the Cron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetCronOk() (*string, bool) {
	if o == nil || IsNil(o.Cron) {
		return nil, false
	}
	return o.Cron, true
}

// HasCron returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasCron() bool {
	if o != nil && !IsNil(o.Cron) {
		return true
	}

	return false
}

// SetCron gets a reference to the given string and assigns it to the Cron field.
func (o *AgentRuntimePatchRequest) SetCron(v string) {
	o.Cron = &v
}

// GetCoordinatorImage returns the CoordinatorImage field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetCoordinatorImage() string {
	if o == nil || IsNil(o.CoordinatorImage) {
		var ret string
		return ret
	}
	return *o.CoordinatorImage
}

// GetCoordinatorImageOk returns a tuple with the CoordinatorImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetCoordinatorImageOk() (*string, bool) {
	if o == nil || IsNil(o.CoordinatorImage) {
		return nil, false
	}
	return o.CoordinatorImage, true
}

// HasCoordinatorImage returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasCoordinatorImage() bool {
	if o != nil && !IsNil(o.CoordinatorImage) {
		return true
	}

	return false
}

// SetCoordinatorImage gets a reference to the given string and assigns it to the CoordinatorImage field.
func (o *AgentRuntimePatchRequest) SetCoordinatorImage(v string) {
	o.CoordinatorImage = &v
}

// GetConcurrencyPolicy returns the ConcurrencyPolicy field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetConcurrencyPolicy() string {
	if o == nil || IsNil(o.ConcurrencyPolicy) {
		var ret string
		return ret
	}
	return *o.ConcurrencyPolicy
}

// GetConcurrencyPolicyOk returns a tuple with the ConcurrencyPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetConcurrencyPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.ConcurrencyPolicy) {
		return nil, false
	}
	return o.ConcurrencyPolicy, true
}

// HasConcurrencyPolicy returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasConcurrencyPolicy() bool {
	if o != nil && !IsNil(o.ConcurrencyPolicy) {
		return true
	}

	return false
}

// SetConcurrencyPolicy gets a reference to the given string and assigns it to the ConcurrencyPolicy field.
func (o *AgentRuntimePatchRequest) SetConcurrencyPolicy(v string) {
	o.ConcurrencyPolicy = &v
}

// GetLoginRefreshSeconds returns the LoginRefreshSeconds field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetLoginRefreshSeconds() int32 {
	if o == nil || IsNil(o.LoginRefreshSeconds) {
		var ret int32
		return ret
	}
	return *o.LoginRefreshSeconds
}

// GetLoginRefreshSecondsOk returns a tuple with the LoginRefreshSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetLoginRefreshSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.LoginRefreshSeconds) {
		return nil, false
	}
	return o.LoginRefreshSeconds, true
}

// HasLoginRefreshSeconds returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasLoginRefreshSeconds() bool {
	if o != nil && !IsNil(o.LoginRefreshSeconds) {
		return true
	}

	return false
}

// SetLoginRefreshSeconds gets a reference to the given int32 and assigns it to the LoginRefreshSeconds field.
func (o *AgentRuntimePatchRequest) SetLoginRefreshSeconds(v int32) {
	o.LoginRefreshSeconds = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *AgentRuntimePatchRequest) GetParameters() string {
	if o == nil || IsNil(o.Parameters) {
		var ret string
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRuntimePatchRequest) GetParametersOk() (*string, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *AgentRuntimePatchRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given string and assigns it to the Parameters field.
func (o *AgentRuntimePatchRequest) SetParameters(v string) {
	o.Parameters = &v
}

func (o AgentRuntimePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRuntimePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SandboxTemplateId) {
		toSerialize["sandbox_template_id"] = o.SandboxTemplateId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Cron) {
		toSerialize["cron"] = o.Cron
	}
	if !IsNil(o.CoordinatorImage) {
		toSerialize["coordinator_image"] = o.CoordinatorImage
	}
	if !IsNil(o.ConcurrencyPolicy) {
		toSerialize["concurrency_policy"] = o.ConcurrencyPolicy
	}
	if !IsNil(o.LoginRefreshSeconds) {
		toSerialize["login_refresh_seconds"] = o.LoginRefreshSeconds
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

type NullableAgentRuntimePatchRequest struct {
	value *AgentRuntimePatchRequest
	isSet bool
}

func (v NullableAgentRuntimePatchRequest) Get() *AgentRuntimePatchRequest {
	return v.value
}

func (v *NullableAgentRuntimePatchRequest) Set(val *AgentRuntimePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRuntimePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRuntimePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRuntimePatchRequest(val *AgentRuntimePatchRequest) *NullableAgentRuntimePatchRequest {
	return &NullableAgentRuntimePatchRequest{value: val, isSet: true}
}

func (v NullableAgentRuntimePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRuntimePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
