/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ManagedClusterRegistrationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedClusterRegistrationResponse{}

// ManagedClusterRegistrationResponse struct for ManagedClusterRegistrationResponse
type ManagedClusterRegistrationResponse struct {
	// Stable KSUID assigned to this managed cluster. Use as the cluster filter for WatchGateways.
	ClusterId string `json:"cluster_id"`
}

type _ManagedClusterRegistrationResponse ManagedClusterRegistrationResponse

// NewManagedClusterRegistrationResponse instantiates a new ManagedClusterRegistrationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedClusterRegistrationResponse(clusterId string) *ManagedClusterRegistrationResponse {
	this := ManagedClusterRegistrationResponse{}
	this.ClusterId = clusterId
	return &this
}

// NewManagedClusterRegistrationResponseWithDefaults instantiates a new ManagedClusterRegistrationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedClusterRegistrationResponseWithDefaults() *ManagedClusterRegistrationResponse {
	this := ManagedClusterRegistrationResponse{}
	return &this
}

// GetClusterId returns the ClusterId field value
func (o *ManagedClusterRegistrationResponse) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *ManagedClusterRegistrationResponse) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *ManagedClusterRegistrationResponse) SetClusterId(v string) {
	o.ClusterId = v
}

func (o ManagedClusterRegistrationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedClusterRegistrationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster_id"] = o.ClusterId
	return toSerialize, nil
}

func (o *ManagedClusterRegistrationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cluster_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedClusterRegistrationResponse := _ManagedClusterRegistrationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedClusterRegistrationResponse)

	if err != nil {
		return err
	}

	*o = ManagedClusterRegistrationResponse(varManagedClusterRegistrationResponse)

	return err
}

type NullableManagedClusterRegistrationResponse struct {
	value *ManagedClusterRegistrationResponse
	isSet bool
}

func (v NullableManagedClusterRegistrationResponse) Get() *ManagedClusterRegistrationResponse {
	return v.value
}

func (v *NullableManagedClusterRegistrationResponse) Set(val *ManagedClusterRegistrationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedClusterRegistrationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedClusterRegistrationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedClusterRegistrationResponse(val *ManagedClusterRegistrationResponse) *NullableManagedClusterRegistrationResponse {
	return &NullableManagedClusterRegistrationResponse{value: val, isSet: true}
}

func (v NullableManagedClusterRegistrationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedClusterRegistrationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
