/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GatewayDeletionStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayDeletionStatus{}

// GatewayDeletionStatus struct for GatewayDeletionStatus
type GatewayDeletionStatus struct {
	GatewayId         string `json:"gateway_id"`
	ExternalReference string `json:"external_reference"`
	// active, requested, or completed
	State               string     `json:"state"`
	DeletionRequestedAt *time.Time `json:"deletion_requested_at,omitempty"`
	DeletionCompletedAt *time.Time `json:"deletion_completed_at,omitempty"`
}

type _GatewayDeletionStatus GatewayDeletionStatus

// NewGatewayDeletionStatus instantiates a new GatewayDeletionStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayDeletionStatus(gatewayId string, externalReference string, state string) *GatewayDeletionStatus {
	this := GatewayDeletionStatus{}
	this.GatewayId = gatewayId
	this.ExternalReference = externalReference
	this.State = state
	return &this
}

// NewGatewayDeletionStatusWithDefaults instantiates a new GatewayDeletionStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayDeletionStatusWithDefaults() *GatewayDeletionStatus {
	this := GatewayDeletionStatus{}
	return &this
}

// GetGatewayId returns the GatewayId field value
func (o *GatewayDeletionStatus) GetGatewayId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value
// and a boolean to check if the value has been set.
func (o *GatewayDeletionStatus) GetGatewayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayId, true
}

// SetGatewayId sets field value
func (o *GatewayDeletionStatus) SetGatewayId(v string) {
	o.GatewayId = v
}

// GetExternalReference returns the ExternalReference field value
func (o *GatewayDeletionStatus) GetExternalReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalReference
}

// GetExternalReferenceOk returns a tuple with the ExternalReference field value
// and a boolean to check if the value has been set.
func (o *GatewayDeletionStatus) GetExternalReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalReference, true
}

// SetExternalReference sets field value
func (o *GatewayDeletionStatus) SetExternalReference(v string) {
	o.ExternalReference = v
}

// GetState returns the State field value
func (o *GatewayDeletionStatus) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *GatewayDeletionStatus) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *GatewayDeletionStatus) SetState(v string) {
	o.State = v
}

// GetDeletionRequestedAt returns the DeletionRequestedAt field value if set, zero value otherwise.
func (o *GatewayDeletionStatus) GetDeletionRequestedAt() time.Time {
	if o == nil || IsNil(o.DeletionRequestedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletionRequestedAt
}

// GetDeletionRequestedAtOk returns a tuple with the DeletionRequestedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayDeletionStatus) GetDeletionRequestedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletionRequestedAt) {
		return nil, false
	}
	return o.DeletionRequestedAt, true
}

// HasDeletionRequestedAt returns a boolean if a field has been set.
func (o *GatewayDeletionStatus) HasDeletionRequestedAt() bool {
	if o != nil && !IsNil(o.DeletionRequestedAt) {
		return true
	}

	return false
}

// SetDeletionRequestedAt gets a reference to the given time.Time and assigns it to the DeletionRequestedAt field.
func (o *GatewayDeletionStatus) SetDeletionRequestedAt(v time.Time) {
	o.DeletionRequestedAt = &v
}

// GetDeletionCompletedAt returns the DeletionCompletedAt field value if set, zero value otherwise.
func (o *GatewayDeletionStatus) GetDeletionCompletedAt() time.Time {
	if o == nil || IsNil(o.DeletionCompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletionCompletedAt
}

// GetDeletionCompletedAtOk returns a tuple with the DeletionCompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayDeletionStatus) GetDeletionCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletionCompletedAt) {
		return nil, false
	}
	return o.DeletionCompletedAt, true
}

// HasDeletionCompletedAt returns a boolean if a field has been set.
func (o *GatewayDeletionStatus) HasDeletionCompletedAt() bool {
	if o != nil && !IsNil(o.DeletionCompletedAt) {
		return true
	}

	return false
}

// SetDeletionCompletedAt gets a reference to the given time.Time and assigns it to the DeletionCompletedAt field.
func (o *GatewayDeletionStatus) SetDeletionCompletedAt(v time.Time) {
	o.DeletionCompletedAt = &v
}

func (o GatewayDeletionStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayDeletionStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gateway_id"] = o.GatewayId
	toSerialize["external_reference"] = o.ExternalReference
	toSerialize["state"] = o.State
	if !IsNil(o.DeletionRequestedAt) {
		toSerialize["deletion_requested_at"] = o.DeletionRequestedAt
	}
	if !IsNil(o.DeletionCompletedAt) {
		toSerialize["deletion_completed_at"] = o.DeletionCompletedAt
	}
	return toSerialize, nil
}

func (o *GatewayDeletionStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gateway_id",
		"external_reference",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayDeletionStatus := _GatewayDeletionStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayDeletionStatus)

	if err != nil {
		return err
	}

	*o = GatewayDeletionStatus(varGatewayDeletionStatus)

	return err
}

type NullableGatewayDeletionStatus struct {
	value *GatewayDeletionStatus
	isSet bool
}

func (v NullableGatewayDeletionStatus) Get() *GatewayDeletionStatus {
	return v.value
}

func (v *NullableGatewayDeletionStatus) Set(val *GatewayDeletionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayDeletionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayDeletionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayDeletionStatus(val *GatewayDeletionStatus) *NullableGatewayDeletionStatus {
	return &NullableGatewayDeletionStatus{value: val, isSet: true}
}

func (v NullableGatewayDeletionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayDeletionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
