/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GatewayNetworkPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayNetworkPatchRequest{}

// GatewayNetworkPatchRequest struct for GatewayNetworkPatchRequest
type GatewayNetworkPatchRequest struct {
	Name         *string `json:"name,omitempty"`
	Topology     *string `json:"topology,omitempty"`
	TunnelMode   *string `json:"tunnel_mode,omitempty"`
	HubGatewayId *string `json:"hub_gateway_id,omitempty"`
	Status       *string `json:"status,omitempty"`
}

// NewGatewayNetworkPatchRequest instantiates a new GatewayNetworkPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayNetworkPatchRequest() *GatewayNetworkPatchRequest {
	this := GatewayNetworkPatchRequest{}
	return &this
}

// NewGatewayNetworkPatchRequestWithDefaults instantiates a new GatewayNetworkPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayNetworkPatchRequestWithDefaults() *GatewayNetworkPatchRequest {
	this := GatewayNetworkPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GatewayNetworkPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GatewayNetworkPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GatewayNetworkPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetTopology returns the Topology field value if set, zero value otherwise.
func (o *GatewayNetworkPatchRequest) GetTopology() string {
	if o == nil || IsNil(o.Topology) {
		var ret string
		return ret
	}
	return *o.Topology
}

// GetTopologyOk returns a tuple with the Topology field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkPatchRequest) GetTopologyOk() (*string, bool) {
	if o == nil || IsNil(o.Topology) {
		return nil, false
	}
	return o.Topology, true
}

// HasTopology returns a boolean if a field has been set.
func (o *GatewayNetworkPatchRequest) HasTopology() bool {
	if o != nil && !IsNil(o.Topology) {
		return true
	}

	return false
}

// SetTopology gets a reference to the given string and assigns it to the Topology field.
func (o *GatewayNetworkPatchRequest) SetTopology(v string) {
	o.Topology = &v
}

// GetTunnelMode returns the TunnelMode field value if set, zero value otherwise.
func (o *GatewayNetworkPatchRequest) GetTunnelMode() string {
	if o == nil || IsNil(o.TunnelMode) {
		var ret string
		return ret
	}
	return *o.TunnelMode
}

// GetTunnelModeOk returns a tuple with the TunnelMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkPatchRequest) GetTunnelModeOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelMode) {
		return nil, false
	}
	return o.TunnelMode, true
}

// HasTunnelMode returns a boolean if a field has been set.
func (o *GatewayNetworkPatchRequest) HasTunnelMode() bool {
	if o != nil && !IsNil(o.TunnelMode) {
		return true
	}

	return false
}

// SetTunnelMode gets a reference to the given string and assigns it to the TunnelMode field.
func (o *GatewayNetworkPatchRequest) SetTunnelMode(v string) {
	o.TunnelMode = &v
}

// GetHubGatewayId returns the HubGatewayId field value if set, zero value otherwise.
func (o *GatewayNetworkPatchRequest) GetHubGatewayId() string {
	if o == nil || IsNil(o.HubGatewayId) {
		var ret string
		return ret
	}
	return *o.HubGatewayId
}

// GetHubGatewayIdOk returns a tuple with the HubGatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkPatchRequest) GetHubGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.HubGatewayId) {
		return nil, false
	}
	return o.HubGatewayId, true
}

// HasHubGatewayId returns a boolean if a field has been set.
func (o *GatewayNetworkPatchRequest) HasHubGatewayId() bool {
	if o != nil && !IsNil(o.HubGatewayId) {
		return true
	}

	return false
}

// SetHubGatewayId gets a reference to the given string and assigns it to the HubGatewayId field.
func (o *GatewayNetworkPatchRequest) SetHubGatewayId(v string) {
	o.HubGatewayId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayNetworkPatchRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayNetworkPatchRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayNetworkPatchRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GatewayNetworkPatchRequest) SetStatus(v string) {
	o.Status = &v
}

func (o GatewayNetworkPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayNetworkPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Topology) {
		toSerialize["topology"] = o.Topology
	}
	if !IsNil(o.TunnelMode) {
		toSerialize["tunnel_mode"] = o.TunnelMode
	}
	if !IsNil(o.HubGatewayId) {
		toSerialize["hub_gateway_id"] = o.HubGatewayId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGatewayNetworkPatchRequest struct {
	value *GatewayNetworkPatchRequest
	isSet bool
}

func (v NullableGatewayNetworkPatchRequest) Get() *GatewayNetworkPatchRequest {
	return v.value
}

func (v *NullableGatewayNetworkPatchRequest) Set(val *GatewayNetworkPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayNetworkPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayNetworkPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayNetworkPatchRequest(val *GatewayNetworkPatchRequest) *NullableGatewayNetworkPatchRequest {
	return &NullableGatewayNetworkPatchRequest{value: val, isSet: true}
}

func (v NullableGatewayNetworkPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayNetworkPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
