/*
HyperShell API

HyperShell fleet management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OpenShellGatewayServiceAccountCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenShellGatewayServiceAccountCreateRequest{}

// OpenShellGatewayServiceAccountCreateRequest struct for OpenShellGatewayServiceAccountCreateRequest
type OpenShellGatewayServiceAccountCreateRequest struct {
	Name           string                              `json:"name"`
	Description    NullableString                      `json:"description,omitempty"`
	CredentialType *string                             `json:"credential_type,omitempty"`
	Role           *OpenShellGatewayServiceAccountRole `json:"role,omitempty"`
	ExpiresAt      *time.Time                          `json:"expires_at,omitempty"`
}

type _OpenShellGatewayServiceAccountCreateRequest OpenShellGatewayServiceAccountCreateRequest

// NewOpenShellGatewayServiceAccountCreateRequest instantiates a new OpenShellGatewayServiceAccountCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenShellGatewayServiceAccountCreateRequest(name string) *OpenShellGatewayServiceAccountCreateRequest {
	this := OpenShellGatewayServiceAccountCreateRequest{}
	this.Name = name
	var credentialType string = "client_secret"
	this.CredentialType = &credentialType
	return &this
}

// NewOpenShellGatewayServiceAccountCreateRequestWithDefaults instantiates a new OpenShellGatewayServiceAccountCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenShellGatewayServiceAccountCreateRequestWithDefaults() *OpenShellGatewayServiceAccountCreateRequest {
	this := OpenShellGatewayServiceAccountCreateRequest{}
	var credentialType string = "client_secret"
	this.CredentialType = &credentialType
	return &this
}

// GetName returns the Name field value
func (o *OpenShellGatewayServiceAccountCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpenShellGatewayServiceAccountCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenShellGatewayServiceAccountCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenShellGatewayServiceAccountCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *OpenShellGatewayServiceAccountCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *OpenShellGatewayServiceAccountCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *OpenShellGatewayServiceAccountCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetCredentialType returns the CredentialType field value if set, zero value otherwise.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetCredentialType() string {
	if o == nil || IsNil(o.CredentialType) {
		var ret string
		return ret
	}
	return *o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetCredentialTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialType) {
		return nil, false
	}
	return o.CredentialType, true
}

// HasCredentialType returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) HasCredentialType() bool {
	if o != nil && !IsNil(o.CredentialType) {
		return true
	}

	return false
}

// SetCredentialType gets a reference to the given string and assigns it to the CredentialType field.
func (o *OpenShellGatewayServiceAccountCreateRequest) SetCredentialType(v string) {
	o.CredentialType = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetRole() OpenShellGatewayServiceAccountRole {
	if o == nil || IsNil(o.Role) {
		var ret OpenShellGatewayServiceAccountRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetRoleOk() (*OpenShellGatewayServiceAccountRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given OpenShellGatewayServiceAccountRole and assigns it to the Role field.
func (o *OpenShellGatewayServiceAccountCreateRequest) SetRole(v OpenShellGatewayServiceAccountRole) {
	o.Role = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountCreateRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *OpenShellGatewayServiceAccountCreateRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o OpenShellGatewayServiceAccountCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenShellGatewayServiceAccountCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.CredentialType) {
		toSerialize["credential_type"] = o.CredentialType
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

func (o *OpenShellGatewayServiceAccountCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenShellGatewayServiceAccountCreateRequest := _OpenShellGatewayServiceAccountCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenShellGatewayServiceAccountCreateRequest)

	if err != nil {
		return err
	}

	*o = OpenShellGatewayServiceAccountCreateRequest(varOpenShellGatewayServiceAccountCreateRequest)

	return err
}

type NullableOpenShellGatewayServiceAccountCreateRequest struct {
	value *OpenShellGatewayServiceAccountCreateRequest
	isSet bool
}

func (v NullableOpenShellGatewayServiceAccountCreateRequest) Get() *OpenShellGatewayServiceAccountCreateRequest {
	return v.value
}

func (v *NullableOpenShellGatewayServiceAccountCreateRequest) Set(val *OpenShellGatewayServiceAccountCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenShellGatewayServiceAccountCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenShellGatewayServiceAccountCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenShellGatewayServiceAccountCreateRequest(val *OpenShellGatewayServiceAccountCreateRequest) *NullableOpenShellGatewayServiceAccountCreateRequest {
	return &NullableOpenShellGatewayServiceAccountCreateRequest{value: val, isSet: true}
}

func (v NullableOpenShellGatewayServiceAccountCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenShellGatewayServiceAccountCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
