/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the GatewayAccessListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayAccessListItem{}

// GatewayAccessListItem struct for GatewayAccessListItem
type GatewayAccessListItem struct {
	RoleBindingId string            `json:"role_binding_id"`
	UserId        string            `json:"user_id"`
	Username      string            `json:"username"`
	Name          NullableString    `json:"name,omitempty"`
	Email         NullableString    `json:"email,omitempty"`
	Role          GatewayAccessRole `json:"role"`
	IsCreator     bool              `json:"is_creator"`
	GrantedAt     time.Time         `json:"granted_at"`
}

type _GatewayAccessListItem GatewayAccessListItem

// NewGatewayAccessListItem instantiates a new GatewayAccessListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayAccessListItem(roleBindingId string, userId string, username string, role GatewayAccessRole, isCreator bool, grantedAt time.Time) *GatewayAccessListItem {
	this := GatewayAccessListItem{}
	this.RoleBindingId = roleBindingId
	this.UserId = userId
	this.Username = username
	this.Role = role
	this.IsCreator = isCreator
	this.GrantedAt = grantedAt
	return &this
}

// NewGatewayAccessListItemWithDefaults instantiates a new GatewayAccessListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayAccessListItemWithDefaults() *GatewayAccessListItem {
	this := GatewayAccessListItem{}
	return &this
}

// GetRoleBindingId returns the RoleBindingId field value
func (o *GatewayAccessListItem) GetRoleBindingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleBindingId
}

// GetRoleBindingIdOk returns a tuple with the RoleBindingId field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetRoleBindingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleBindingId, true
}

// SetRoleBindingId sets field value
func (o *GatewayAccessListItem) SetRoleBindingId(v string) {
	o.RoleBindingId = v
}

// GetUserId returns the UserId field value
func (o *GatewayAccessListItem) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GatewayAccessListItem) SetUserId(v string) {
	o.UserId = v
}

// GetUsername returns the Username field value
func (o *GatewayAccessListItem) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *GatewayAccessListItem) SetUsername(v string) {
	o.Username = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayAccessListItem) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayAccessListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *GatewayAccessListItem) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *GatewayAccessListItem) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *GatewayAccessListItem) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *GatewayAccessListItem) UnsetName() {
	o.Name.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayAccessListItem) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayAccessListItem) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *GatewayAccessListItem) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *GatewayAccessListItem) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *GatewayAccessListItem) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *GatewayAccessListItem) UnsetEmail() {
	o.Email.Unset()
}

// GetRole returns the Role field value
func (o *GatewayAccessListItem) GetRole() GatewayAccessRole {
	if o == nil {
		var ret GatewayAccessRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetRoleOk() (*GatewayAccessRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GatewayAccessListItem) SetRole(v GatewayAccessRole) {
	o.Role = v
}

// GetIsCreator returns the IsCreator field value
func (o *GatewayAccessListItem) GetIsCreator() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCreator
}

// GetIsCreatorOk returns a tuple with the IsCreator field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetIsCreatorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCreator, true
}

// SetIsCreator sets field value
func (o *GatewayAccessListItem) SetIsCreator(v bool) {
	o.IsCreator = v
}

// GetGrantedAt returns the GrantedAt field value
func (o *GatewayAccessListItem) GetGrantedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GrantedAt
}

// GetGrantedAtOk returns a tuple with the GrantedAt field value
// and a boolean to check if the value has been set.
func (o *GatewayAccessListItem) GetGrantedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantedAt, true
}

// SetGrantedAt sets field value
func (o *GatewayAccessListItem) SetGrantedAt(v time.Time) {
	o.GrantedAt = v
}

func (o GatewayAccessListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayAccessListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role_binding_id"] = o.RoleBindingId
	toSerialize["user_id"] = o.UserId
	toSerialize["username"] = o.Username
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	toSerialize["role"] = o.Role
	toSerialize["is_creator"] = o.IsCreator
	toSerialize["granted_at"] = o.GrantedAt
	return toSerialize, nil
}

func (o *GatewayAccessListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role_binding_id",
		"user_id",
		"username",
		"role",
		"is_creator",
		"granted_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayAccessListItem := _GatewayAccessListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayAccessListItem)

	if err != nil {
		return err
	}

	*o = GatewayAccessListItem(varGatewayAccessListItem)

	return err
}

type NullableGatewayAccessListItem struct {
	value *GatewayAccessListItem
	isSet bool
}

func (v NullableGatewayAccessListItem) Get() *GatewayAccessListItem {
	return v.value
}

func (v *NullableGatewayAccessListItem) Set(val *GatewayAccessListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayAccessListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayAccessListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayAccessListItem(val *GatewayAccessListItem) *NullableGatewayAccessListItem {
	return &NullableGatewayAccessListItem{value: val, isSet: true}
}

func (v NullableGatewayAccessListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayAccessListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
