/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OpenShellGatewayServiceAccountGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenShellGatewayServiceAccountGetResponse{}

// OpenShellGatewayServiceAccountGetResponse struct for OpenShellGatewayServiceAccountGetResponse
type OpenShellGatewayServiceAccountGetResponse struct {
	Id              string                                   `json:"id"`
	GatewayId       string                                   `json:"gateway_id"`
	Name            string                                   `json:"name"`
	Description     NullableString                           `json:"description,omitempty"`
	CredentialType  string                                   `json:"credential_type"`
	Role            OpenShellGatewayServiceAccountRole       `json:"role"`
	Status          OpenShellGatewayServiceAccountStatus     `json:"status"`
	CreatedByUserId string                                   `json:"created_by_user_id"`
	ClientId        string                                   `json:"client_id"`
	Subject         string                                   `json:"subject"`
	ExpiresAt       time.Time                                `json:"expires_at"`
	RevokedAt       NullableTime                             `json:"revoked_at,omitempty"`
	LastError       NullableString                           `json:"last_error,omitempty"`
	CreatedAt       time.Time                                `json:"created_at"`
	UpdatedAt       time.Time                                `json:"updated_at"`
	Connection      OpenShellGatewayServiceAccountConnection `json:"connection"`
}

type _OpenShellGatewayServiceAccountGetResponse OpenShellGatewayServiceAccountGetResponse

// NewOpenShellGatewayServiceAccountGetResponse instantiates a new OpenShellGatewayServiceAccountGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenShellGatewayServiceAccountGetResponse(id string, gatewayId string, name string, credentialType string, role OpenShellGatewayServiceAccountRole, status OpenShellGatewayServiceAccountStatus, createdByUserId string, clientId string, subject string, expiresAt time.Time, createdAt time.Time, updatedAt time.Time, connection OpenShellGatewayServiceAccountConnection) *OpenShellGatewayServiceAccountGetResponse {
	this := OpenShellGatewayServiceAccountGetResponse{}
	this.Id = id
	this.GatewayId = gatewayId
	this.Name = name
	this.CredentialType = credentialType
	this.Role = role
	this.Status = status
	this.CreatedByUserId = createdByUserId
	this.ClientId = clientId
	this.Subject = subject
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Connection = connection
	return &this
}

// NewOpenShellGatewayServiceAccountGetResponseWithDefaults instantiates a new OpenShellGatewayServiceAccountGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenShellGatewayServiceAccountGetResponseWithDefaults() *OpenShellGatewayServiceAccountGetResponse {
	this := OpenShellGatewayServiceAccountGetResponse{}
	return &this
}

// GetId returns the Id field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetId(v string) {
	o.Id = v
}

// GetGatewayId returns the GatewayId field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetGatewayId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetGatewayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayId, true
}

// SetGatewayId sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetGatewayId(v string) {
	o.GatewayId = v
}

// GetName returns the Name field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenShellGatewayServiceAccountGetResponse) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenShellGatewayServiceAccountGetResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *OpenShellGatewayServiceAccountGetResponse) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetCredentialType returns the CredentialType field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetCredentialType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetCredentialTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetCredentialType(v string) {
	o.CredentialType = v
}

// GetRole returns the Role field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetRole() OpenShellGatewayServiceAccountRole {
	if o == nil {
		var ret OpenShellGatewayServiceAccountRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetRoleOk() (*OpenShellGatewayServiceAccountRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetRole(v OpenShellGatewayServiceAccountRole) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetStatus() OpenShellGatewayServiceAccountStatus {
	if o == nil {
		var ret OpenShellGatewayServiceAccountStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetStatusOk() (*OpenShellGatewayServiceAccountStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetStatus(v OpenShellGatewayServiceAccountStatus) {
	o.Status = v
}

// GetCreatedByUserId returns the CreatedByUserId field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetCreatedByUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByUserId, true
}

// SetCreatedByUserId sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetCreatedByUserId(v string) {
	o.CreatedByUserId = v
}

// GetClientId returns the ClientId field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetClientId(v string) {
	o.ClientId = v
}

// GetSubject returns the Subject field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetSubject(v string) {
	o.Subject = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenShellGatewayServiceAccountGetResponse) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenShellGatewayServiceAccountGetResponse) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableTime and assigns it to the RevokedAt field.
func (o *OpenShellGatewayServiceAccountGetResponse) SetRevokedAt(v time.Time) {
	o.RevokedAt.Set(&v)
}

// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

// GetLastError returns the LastError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenShellGatewayServiceAccountGetResponse) GetLastError() string {
	if o == nil || IsNil(o.LastError.Get()) {
		var ret string
		return ret
	}
	return *o.LastError.Get()
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenShellGatewayServiceAccountGetResponse) GetLastErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastError.Get(), o.LastError.IsSet()
}

// HasLastError returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) HasLastError() bool {
	if o != nil && o.LastError.IsSet() {
		return true
	}

	return false
}

// SetLastError gets a reference to the given NullableString and assigns it to the LastError field.
func (o *OpenShellGatewayServiceAccountGetResponse) SetLastError(v string) {
	o.LastError.Set(&v)
}

// SetLastErrorNil sets the value for LastError to be an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) SetLastErrorNil() {
	o.LastError.Set(nil)
}

// UnsetLastError ensures that no value is present for LastError, not even an explicit nil
func (o *OpenShellGatewayServiceAccountGetResponse) UnsetLastError() {
	o.LastError.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetConnection returns the Connection field value
func (o *OpenShellGatewayServiceAccountGetResponse) GetConnection() OpenShellGatewayServiceAccountConnection {
	if o == nil {
		var ret OpenShellGatewayServiceAccountConnection
		return ret
	}

	return o.Connection
}

// GetConnectionOk returns a tuple with the Connection field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountGetResponse) GetConnectionOk() (*OpenShellGatewayServiceAccountConnection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connection, true
}

// SetConnection sets field value
func (o *OpenShellGatewayServiceAccountGetResponse) SetConnection(v OpenShellGatewayServiceAccountConnection) {
	o.Connection = v
}

func (o OpenShellGatewayServiceAccountGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenShellGatewayServiceAccountGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["gateway_id"] = o.GatewayId
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["credential_type"] = o.CredentialType
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	toSerialize["created_by_user_id"] = o.CreatedByUserId
	toSerialize["client_id"] = o.ClientId
	toSerialize["subject"] = o.Subject
	toSerialize["expires_at"] = o.ExpiresAt
	if o.RevokedAt.IsSet() {
		toSerialize["revoked_at"] = o.RevokedAt.Get()
	}
	if o.LastError.IsSet() {
		toSerialize["last_error"] = o.LastError.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["connection"] = o.Connection
	return toSerialize, nil
}

func (o *OpenShellGatewayServiceAccountGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"gateway_id",
		"name",
		"credential_type",
		"role",
		"status",
		"created_by_user_id",
		"client_id",
		"subject",
		"expires_at",
		"created_at",
		"updated_at",
		"connection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenShellGatewayServiceAccountGetResponse := _OpenShellGatewayServiceAccountGetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenShellGatewayServiceAccountGetResponse)

	if err != nil {
		return err
	}

	*o = OpenShellGatewayServiceAccountGetResponse(varOpenShellGatewayServiceAccountGetResponse)

	return err
}

type NullableOpenShellGatewayServiceAccountGetResponse struct {
	value *OpenShellGatewayServiceAccountGetResponse
	isSet bool
}

func (v NullableOpenShellGatewayServiceAccountGetResponse) Get() *OpenShellGatewayServiceAccountGetResponse {
	return v.value
}

func (v *NullableOpenShellGatewayServiceAccountGetResponse) Set(val *OpenShellGatewayServiceAccountGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenShellGatewayServiceAccountGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenShellGatewayServiceAccountGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenShellGatewayServiceAccountGetResponse(val *OpenShellGatewayServiceAccountGetResponse) *NullableOpenShellGatewayServiceAccountGetResponse {
	return &NullableOpenShellGatewayServiceAccountGetResponse{value: val, isSet: true}
}

func (v NullableOpenShellGatewayServiceAccountGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenShellGatewayServiceAccountGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
