/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProviderBinding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBinding{}

// ProviderBinding struct for ProviderBinding
type ProviderBinding struct {
	Id             *string    `json:"id,omitempty"`
	Kind           *string    `json:"kind,omitempty"`
	Href           *string    `json:"href,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
	Name           string     `json:"name"`
	WorkspaceId    string     `json:"workspace_id"`
	ProviderSpecId string     `json:"provider_spec_id"`
	SecretSourceId *string    `json:"secret_source_id,omitempty"`
	// JSON-encoded credential refresh strategy configuration
	RefreshStrategy *string `json:"refresh_strategy,omitempty"`
	Status          *string `json:"status,omitempty"`
}

type _ProviderBinding ProviderBinding

// NewProviderBinding instantiates a new ProviderBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBinding(name string, workspaceId string, providerSpecId string) *ProviderBinding {
	this := ProviderBinding{}
	this.Name = name
	this.WorkspaceId = workspaceId
	this.ProviderSpecId = providerSpecId
	return &this
}

// NewProviderBindingWithDefaults instantiates a new ProviderBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBindingWithDefaults() *ProviderBinding {
	this := ProviderBinding{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProviderBinding) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProviderBinding) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProviderBinding) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ProviderBinding) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ProviderBinding) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ProviderBinding) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ProviderBinding) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ProviderBinding) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ProviderBinding) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProviderBinding) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProviderBinding) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ProviderBinding) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProviderBinding) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProviderBinding) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProviderBinding) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value
func (o *ProviderBinding) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProviderBinding) SetName(v string) {
	o.Name = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *ProviderBinding) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *ProviderBinding) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetProviderSpecId returns the ProviderSpecId field value
func (o *ProviderBinding) GetProviderSpecId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderSpecId
}

// GetProviderSpecIdOk returns a tuple with the ProviderSpecId field value
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetProviderSpecIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderSpecId, true
}

// SetProviderSpecId sets field value
func (o *ProviderBinding) SetProviderSpecId(v string) {
	o.ProviderSpecId = v
}

// GetSecretSourceId returns the SecretSourceId field value if set, zero value otherwise.
func (o *ProviderBinding) GetSecretSourceId() string {
	if o == nil || IsNil(o.SecretSourceId) {
		var ret string
		return ret
	}
	return *o.SecretSourceId
}

// GetSecretSourceIdOk returns a tuple with the SecretSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetSecretSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretSourceId) {
		return nil, false
	}
	return o.SecretSourceId, true
}

// HasSecretSourceId returns a boolean if a field has been set.
func (o *ProviderBinding) HasSecretSourceId() bool {
	if o != nil && !IsNil(o.SecretSourceId) {
		return true
	}

	return false
}

// SetSecretSourceId gets a reference to the given string and assigns it to the SecretSourceId field.
func (o *ProviderBinding) SetSecretSourceId(v string) {
	o.SecretSourceId = &v
}

// GetRefreshStrategy returns the RefreshStrategy field value if set, zero value otherwise.
func (o *ProviderBinding) GetRefreshStrategy() string {
	if o == nil || IsNil(o.RefreshStrategy) {
		var ret string
		return ret
	}
	return *o.RefreshStrategy
}

// GetRefreshStrategyOk returns a tuple with the RefreshStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetRefreshStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshStrategy) {
		return nil, false
	}
	return o.RefreshStrategy, true
}

// HasRefreshStrategy returns a boolean if a field has been set.
func (o *ProviderBinding) HasRefreshStrategy() bool {
	if o != nil && !IsNil(o.RefreshStrategy) {
		return true
	}

	return false
}

// SetRefreshStrategy gets a reference to the given string and assigns it to the RefreshStrategy field.
func (o *ProviderBinding) SetRefreshStrategy(v string) {
	o.RefreshStrategy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProviderBinding) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBinding) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProviderBinding) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProviderBinding) SetStatus(v string) {
	o.Status = &v
}

func (o ProviderBinding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBinding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["name"] = o.Name
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["provider_spec_id"] = o.ProviderSpecId
	if !IsNil(o.SecretSourceId) {
		toSerialize["secret_source_id"] = o.SecretSourceId
	}
	if !IsNil(o.RefreshStrategy) {
		toSerialize["refresh_strategy"] = o.RefreshStrategy
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *ProviderBinding) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"workspace_id",
		"provider_spec_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderBinding := _ProviderBinding{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProviderBinding)

	if err != nil {
		return err
	}

	*o = ProviderBinding(varProviderBinding)

	return err
}

type NullableProviderBinding struct {
	value *ProviderBinding
	isSet bool
}

func (v NullableProviderBinding) Get() *ProviderBinding {
	return v.value
}

func (v *NullableProviderBinding) Set(val *ProviderBinding) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBinding) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBinding(val *ProviderBinding) *NullableProviderBinding {
	return &NullableProviderBinding{value: val, isSet: true}
}

func (v NullableProviderBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
