/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GatewayDirectoryUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayDirectoryUser{}

// GatewayDirectoryUser struct for GatewayDirectoryUser
type GatewayDirectoryUser struct {
	Username string         `json:"username"`
	Name     NullableString `json:"name,omitempty"`
	Email    NullableString `json:"email,omitempty"`
	Subject  NullableString `json:"subject,omitempty"`
}

type _GatewayDirectoryUser GatewayDirectoryUser

// NewGatewayDirectoryUser instantiates a new GatewayDirectoryUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayDirectoryUser(username string) *GatewayDirectoryUser {
	this := GatewayDirectoryUser{}
	this.Username = username
	return &this
}

// NewGatewayDirectoryUserWithDefaults instantiates a new GatewayDirectoryUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayDirectoryUserWithDefaults() *GatewayDirectoryUser {
	this := GatewayDirectoryUser{}
	return &this
}

// GetUsername returns the Username field value
func (o *GatewayDirectoryUser) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *GatewayDirectoryUser) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *GatewayDirectoryUser) SetUsername(v string) {
	o.Username = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayDirectoryUser) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayDirectoryUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *GatewayDirectoryUser) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *GatewayDirectoryUser) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *GatewayDirectoryUser) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *GatewayDirectoryUser) UnsetName() {
	o.Name.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayDirectoryUser) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayDirectoryUser) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *GatewayDirectoryUser) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *GatewayDirectoryUser) SetEmail(v string) {
	o.Email.Set(&v)
}

// SetEmailNil sets the value for Email to be an explicit nil
func (o *GatewayDirectoryUser) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *GatewayDirectoryUser) UnsetEmail() {
	o.Email.Unset()
}

// GetSubject returns the Subject field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayDirectoryUser) GetSubject() string {
	if o == nil || IsNil(o.Subject.Get()) {
		var ret string
		return ret
	}
	return *o.Subject.Get()
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayDirectoryUser) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subject.Get(), o.Subject.IsSet()
}

// HasSubject returns a boolean if a field has been set.
func (o *GatewayDirectoryUser) HasSubject() bool {
	if o != nil && o.Subject.IsSet() {
		return true
	}

	return false
}

// SetSubject gets a reference to the given NullableString and assigns it to the Subject field.
func (o *GatewayDirectoryUser) SetSubject(v string) {
	o.Subject.Set(&v)
}

// SetSubjectNil sets the value for Subject to be an explicit nil
func (o *GatewayDirectoryUser) SetSubjectNil() {
	o.Subject.Set(nil)
}

// UnsetSubject ensures that no value is present for Subject, not even an explicit nil
func (o *GatewayDirectoryUser) UnsetSubject() {
	o.Subject.Unset()
}

func (o GatewayDirectoryUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayDirectoryUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.Subject.IsSet() {
		toSerialize["subject"] = o.Subject.Get()
	}
	return toSerialize, nil
}

func (o *GatewayDirectoryUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayDirectoryUser := _GatewayDirectoryUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayDirectoryUser)

	if err != nil {
		return err
	}

	*o = GatewayDirectoryUser(varGatewayDirectoryUser)

	return err
}

type NullableGatewayDirectoryUser struct {
	value *GatewayDirectoryUser
	isSet bool
}

func (v NullableGatewayDirectoryUser) Get() *GatewayDirectoryUser {
	return v.value
}

func (v *NullableGatewayDirectoryUser) Set(val *GatewayDirectoryUser) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayDirectoryUser) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayDirectoryUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayDirectoryUser(val *GatewayDirectoryUser) *NullableGatewayDirectoryUser {
	return &NullableGatewayDirectoryUser{value: val, isSet: true}
}

func (v NullableGatewayDirectoryUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayDirectoryUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
