/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProviderBindingPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBindingPatchRequest{}

// ProviderBindingPatchRequest struct for ProviderBindingPatchRequest
type ProviderBindingPatchRequest struct {
	Name            *string `json:"name,omitempty"`
	SecretSourceId  *string `json:"secret_source_id,omitempty"`
	RefreshStrategy *string `json:"refresh_strategy,omitempty"`
}

// NewProviderBindingPatchRequest instantiates a new ProviderBindingPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBindingPatchRequest() *ProviderBindingPatchRequest {
	this := ProviderBindingPatchRequest{}
	return &this
}

// NewProviderBindingPatchRequestWithDefaults instantiates a new ProviderBindingPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBindingPatchRequestWithDefaults() *ProviderBindingPatchRequest {
	this := ProviderBindingPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProviderBindingPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBindingPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProviderBindingPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProviderBindingPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetSecretSourceId returns the SecretSourceId field value if set, zero value otherwise.
func (o *ProviderBindingPatchRequest) GetSecretSourceId() string {
	if o == nil || IsNil(o.SecretSourceId) {
		var ret string
		return ret
	}
	return *o.SecretSourceId
}

// GetSecretSourceIdOk returns a tuple with the SecretSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBindingPatchRequest) GetSecretSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretSourceId) {
		return nil, false
	}
	return o.SecretSourceId, true
}

// HasSecretSourceId returns a boolean if a field has been set.
func (o *ProviderBindingPatchRequest) HasSecretSourceId() bool {
	if o != nil && !IsNil(o.SecretSourceId) {
		return true
	}

	return false
}

// SetSecretSourceId gets a reference to the given string and assigns it to the SecretSourceId field.
func (o *ProviderBindingPatchRequest) SetSecretSourceId(v string) {
	o.SecretSourceId = &v
}

// GetRefreshStrategy returns the RefreshStrategy field value if set, zero value otherwise.
func (o *ProviderBindingPatchRequest) GetRefreshStrategy() string {
	if o == nil || IsNil(o.RefreshStrategy) {
		var ret string
		return ret
	}
	return *o.RefreshStrategy
}

// GetRefreshStrategyOk returns a tuple with the RefreshStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBindingPatchRequest) GetRefreshStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshStrategy) {
		return nil, false
	}
	return o.RefreshStrategy, true
}

// HasRefreshStrategy returns a boolean if a field has been set.
func (o *ProviderBindingPatchRequest) HasRefreshStrategy() bool {
	if o != nil && !IsNil(o.RefreshStrategy) {
		return true
	}

	return false
}

// SetRefreshStrategy gets a reference to the given string and assigns it to the RefreshStrategy field.
func (o *ProviderBindingPatchRequest) SetRefreshStrategy(v string) {
	o.RefreshStrategy = &v
}

func (o ProviderBindingPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBindingPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SecretSourceId) {
		toSerialize["secret_source_id"] = o.SecretSourceId
	}
	if !IsNil(o.RefreshStrategy) {
		toSerialize["refresh_strategy"] = o.RefreshStrategy
	}
	return toSerialize, nil
}

type NullableProviderBindingPatchRequest struct {
	value *ProviderBindingPatchRequest
	isSet bool
}

func (v NullableProviderBindingPatchRequest) Get() *ProviderBindingPatchRequest {
	return v.value
}

func (v *NullableProviderBindingPatchRequest) Set(val *ProviderBindingPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBindingPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBindingPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBindingPatchRequest(val *ProviderBindingPatchRequest) *NullableProviderBindingPatchRequest {
	return &NullableProviderBindingPatchRequest{value: val, isSet: true}
}

func (v NullableProviderBindingPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBindingPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
