/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserDailyCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDailyCount{}

// UserDailyCount struct for UserDailyCount
type UserDailyCount struct {
	// UTC calendar day (YYYY-MM-DD)
	Date  string `json:"date"`
	Count int64  `json:"count"`
}

type _UserDailyCount UserDailyCount

// NewUserDailyCount instantiates a new UserDailyCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDailyCount(date string, count int64) *UserDailyCount {
	this := UserDailyCount{}
	this.Date = date
	this.Count = count
	return &this
}

// NewUserDailyCountWithDefaults instantiates a new UserDailyCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDailyCountWithDefaults() *UserDailyCount {
	this := UserDailyCount{}
	return &this
}

// GetDate returns the Date field value
func (o *UserDailyCount) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *UserDailyCount) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *UserDailyCount) SetDate(v string) {
	o.Date = v
}

// GetCount returns the Count field value
func (o *UserDailyCount) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *UserDailyCount) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *UserDailyCount) SetCount(v int64) {
	o.Count = v
}

func (o UserDailyCount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDailyCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *UserDailyCount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDailyCount := _UserDailyCount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDailyCount)

	if err != nil {
		return err
	}

	*o = UserDailyCount(varUserDailyCount)

	return err
}

type NullableUserDailyCount struct {
	value *UserDailyCount
	isSet bool
}

func (v NullableUserDailyCount) Get() *UserDailyCount {
	return v.value
}

func (v *NullableUserDailyCount) Set(val *UserDailyCount) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDailyCount) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDailyCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDailyCount(val *UserDailyCount) *NullableUserDailyCount {
	return &NullableUserDailyCount{value: val, isSet: true}
}

func (v NullableUserDailyCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDailyCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
