/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GatewayReleasePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayReleasePatchRequest{}

// GatewayReleasePatchRequest struct for GatewayReleasePatchRequest
type GatewayReleasePatchRequest struct {
	Name            *string `json:"name,omitempty"`
	Image           *string `json:"image,omitempty"`
	RolloutStrategy *string `json:"rollout_strategy,omitempty"`
	CanaryPercent   *int32  `json:"canary_percent,omitempty"`
	CanaryDuration  *string `json:"canary_duration,omitempty"`
	Status          *string `json:"status,omitempty"`
}

// NewGatewayReleasePatchRequest instantiates a new GatewayReleasePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayReleasePatchRequest() *GatewayReleasePatchRequest {
	this := GatewayReleasePatchRequest{}
	return &this
}

// NewGatewayReleasePatchRequestWithDefaults instantiates a new GatewayReleasePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayReleasePatchRequestWithDefaults() *GatewayReleasePatchRequest {
	this := GatewayReleasePatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GatewayReleasePatchRequest) SetName(v string) {
	o.Name = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *GatewayReleasePatchRequest) SetImage(v string) {
	o.Image = &v
}

// GetRolloutStrategy returns the RolloutStrategy field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetRolloutStrategy() string {
	if o == nil || IsNil(o.RolloutStrategy) {
		var ret string
		return ret
	}
	return *o.RolloutStrategy
}

// GetRolloutStrategyOk returns a tuple with the RolloutStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetRolloutStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.RolloutStrategy) {
		return nil, false
	}
	return o.RolloutStrategy, true
}

// HasRolloutStrategy returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasRolloutStrategy() bool {
	if o != nil && !IsNil(o.RolloutStrategy) {
		return true
	}

	return false
}

// SetRolloutStrategy gets a reference to the given string and assigns it to the RolloutStrategy field.
func (o *GatewayReleasePatchRequest) SetRolloutStrategy(v string) {
	o.RolloutStrategy = &v
}

// GetCanaryPercent returns the CanaryPercent field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetCanaryPercent() int32 {
	if o == nil || IsNil(o.CanaryPercent) {
		var ret int32
		return ret
	}
	return *o.CanaryPercent
}

// GetCanaryPercentOk returns a tuple with the CanaryPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetCanaryPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.CanaryPercent) {
		return nil, false
	}
	return o.CanaryPercent, true
}

// HasCanaryPercent returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasCanaryPercent() bool {
	if o != nil && !IsNil(o.CanaryPercent) {
		return true
	}

	return false
}

// SetCanaryPercent gets a reference to the given int32 and assigns it to the CanaryPercent field.
func (o *GatewayReleasePatchRequest) SetCanaryPercent(v int32) {
	o.CanaryPercent = &v
}

// GetCanaryDuration returns the CanaryDuration field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetCanaryDuration() string {
	if o == nil || IsNil(o.CanaryDuration) {
		var ret string
		return ret
	}
	return *o.CanaryDuration
}

// GetCanaryDurationOk returns a tuple with the CanaryDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetCanaryDurationOk() (*string, bool) {
	if o == nil || IsNil(o.CanaryDuration) {
		return nil, false
	}
	return o.CanaryDuration, true
}

// HasCanaryDuration returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasCanaryDuration() bool {
	if o != nil && !IsNil(o.CanaryDuration) {
		return true
	}

	return false
}

// SetCanaryDuration gets a reference to the given string and assigns it to the CanaryDuration field.
func (o *GatewayReleasePatchRequest) SetCanaryDuration(v string) {
	o.CanaryDuration = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayReleasePatchRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayReleasePatchRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayReleasePatchRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GatewayReleasePatchRequest) SetStatus(v string) {
	o.Status = &v
}

func (o GatewayReleasePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayReleasePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.RolloutStrategy) {
		toSerialize["rollout_strategy"] = o.RolloutStrategy
	}
	if !IsNil(o.CanaryPercent) {
		toSerialize["canary_percent"] = o.CanaryPercent
	}
	if !IsNil(o.CanaryDuration) {
		toSerialize["canary_duration"] = o.CanaryDuration
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGatewayReleasePatchRequest struct {
	value *GatewayReleasePatchRequest
	isSet bool
}

func (v NullableGatewayReleasePatchRequest) Get() *GatewayReleasePatchRequest {
	return v.value
}

func (v *NullableGatewayReleasePatchRequest) Set(val *GatewayReleasePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayReleasePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayReleasePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayReleasePatchRequest(val *GatewayReleasePatchRequest) *NullableGatewayReleasePatchRequest {
	return &NullableGatewayReleasePatchRequest{value: val, isSet: true}
}

func (v NullableGatewayReleasePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayReleasePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
