/*
HyperShell API

HyperShell gateway management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OpenShellGatewayServiceAccountCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenShellGatewayServiceAccountCredential{}

// OpenShellGatewayServiceAccountCredential struct for OpenShellGatewayServiceAccountCredential
type OpenShellGatewayServiceAccountCredential struct {
	GatewayName                string  `json:"gateway_name"`
	GatewayEndpoint            *string `json:"gateway_endpoint,omitempty"`
	Issuer                     string  `json:"issuer"`
	TokenEndpoint              string  `json:"token_endpoint"`
	GrantType                  string  `json:"grant_type"`
	ClientId                   string  `json:"client_id"`
	ClientSecret               string  `json:"client_secret"`
	Audience                   string  `json:"audience"`
	AccessTokenLifetimeSeconds int32   `json:"access_token_lifetime_seconds"`
}

type _OpenShellGatewayServiceAccountCredential OpenShellGatewayServiceAccountCredential

// NewOpenShellGatewayServiceAccountCredential instantiates a new OpenShellGatewayServiceAccountCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenShellGatewayServiceAccountCredential(gatewayName string, issuer string, tokenEndpoint string, grantType string, clientId string, clientSecret string, audience string, accessTokenLifetimeSeconds int32) *OpenShellGatewayServiceAccountCredential {
	this := OpenShellGatewayServiceAccountCredential{}
	this.GatewayName = gatewayName
	this.Issuer = issuer
	this.TokenEndpoint = tokenEndpoint
	this.GrantType = grantType
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.Audience = audience
	this.AccessTokenLifetimeSeconds = accessTokenLifetimeSeconds
	return &this
}

// NewOpenShellGatewayServiceAccountCredentialWithDefaults instantiates a new OpenShellGatewayServiceAccountCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenShellGatewayServiceAccountCredentialWithDefaults() *OpenShellGatewayServiceAccountCredential {
	this := OpenShellGatewayServiceAccountCredential{}
	return &this
}

// GetGatewayName returns the GatewayName field value
func (o *OpenShellGatewayServiceAccountCredential) GetGatewayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayName
}

// GetGatewayNameOk returns a tuple with the GatewayName field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetGatewayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayName, true
}

// SetGatewayName sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetGatewayName(v string) {
	o.GatewayName = v
}

// GetGatewayEndpoint returns the GatewayEndpoint field value if set, zero value otherwise.
func (o *OpenShellGatewayServiceAccountCredential) GetGatewayEndpoint() string {
	if o == nil || IsNil(o.GatewayEndpoint) {
		var ret string
		return ret
	}
	return *o.GatewayEndpoint
}

// GetGatewayEndpointOk returns a tuple with the GatewayEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetGatewayEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayEndpoint) {
		return nil, false
	}
	return o.GatewayEndpoint, true
}

// HasGatewayEndpoint returns a boolean if a field has been set.
func (o *OpenShellGatewayServiceAccountCredential) HasGatewayEndpoint() bool {
	if o != nil && !IsNil(o.GatewayEndpoint) {
		return true
	}

	return false
}

// SetGatewayEndpoint gets a reference to the given string and assigns it to the GatewayEndpoint field.
func (o *OpenShellGatewayServiceAccountCredential) SetGatewayEndpoint(v string) {
	o.GatewayEndpoint = &v
}

// GetIssuer returns the Issuer field value
func (o *OpenShellGatewayServiceAccountCredential) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetIssuer(v string) {
	o.Issuer = v
}

// GetTokenEndpoint returns the TokenEndpoint field value
func (o *OpenShellGatewayServiceAccountCredential) GetTokenEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenEndpoint
}

// GetTokenEndpointOk returns a tuple with the TokenEndpoint field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetTokenEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenEndpoint, true
}

// SetTokenEndpoint sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetTokenEndpoint(v string) {
	o.TokenEndpoint = v
}

// GetGrantType returns the GrantType field value
func (o *OpenShellGatewayServiceAccountCredential) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetGrantType(v string) {
	o.GrantType = v
}

// GetClientId returns the ClientId field value
func (o *OpenShellGatewayServiceAccountCredential) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *OpenShellGatewayServiceAccountCredential) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetAudience returns the Audience field value
func (o *OpenShellGatewayServiceAccountCredential) GetAudience() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetAudienceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audience, true
}

// SetAudience sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetAudience(v string) {
	o.Audience = v
}

// GetAccessTokenLifetimeSeconds returns the AccessTokenLifetimeSeconds field value
func (o *OpenShellGatewayServiceAccountCredential) GetAccessTokenLifetimeSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccessTokenLifetimeSeconds
}

// GetAccessTokenLifetimeSecondsOk returns a tuple with the AccessTokenLifetimeSeconds field value
// and a boolean to check if the value has been set.
func (o *OpenShellGatewayServiceAccountCredential) GetAccessTokenLifetimeSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenLifetimeSeconds, true
}

// SetAccessTokenLifetimeSeconds sets field value
func (o *OpenShellGatewayServiceAccountCredential) SetAccessTokenLifetimeSeconds(v int32) {
	o.AccessTokenLifetimeSeconds = v
}

func (o OpenShellGatewayServiceAccountCredential) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenShellGatewayServiceAccountCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gateway_name"] = o.GatewayName
	if !IsNil(o.GatewayEndpoint) {
		toSerialize["gateway_endpoint"] = o.GatewayEndpoint
	}
	toSerialize["issuer"] = o.Issuer
	toSerialize["token_endpoint"] = o.TokenEndpoint
	toSerialize["grant_type"] = o.GrantType
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["audience"] = o.Audience
	toSerialize["access_token_lifetime_seconds"] = o.AccessTokenLifetimeSeconds
	return toSerialize, nil
}

func (o *OpenShellGatewayServiceAccountCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gateway_name",
		"issuer",
		"token_endpoint",
		"grant_type",
		"client_id",
		"client_secret",
		"audience",
		"access_token_lifetime_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenShellGatewayServiceAccountCredential := _OpenShellGatewayServiceAccountCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenShellGatewayServiceAccountCredential)

	if err != nil {
		return err
	}

	*o = OpenShellGatewayServiceAccountCredential(varOpenShellGatewayServiceAccountCredential)

	return err
}

type NullableOpenShellGatewayServiceAccountCredential struct {
	value *OpenShellGatewayServiceAccountCredential
	isSet bool
}

func (v NullableOpenShellGatewayServiceAccountCredential) Get() *OpenShellGatewayServiceAccountCredential {
	return v.value
}

func (v *NullableOpenShellGatewayServiceAccountCredential) Set(val *OpenShellGatewayServiceAccountCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenShellGatewayServiceAccountCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenShellGatewayServiceAccountCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenShellGatewayServiceAccountCredential(val *OpenShellGatewayServiceAccountCredential) *NullableOpenShellGatewayServiceAccountCredential {
	return &NullableOpenShellGatewayServiceAccountCredential{value: val, isSet: true}
}

func (v NullableOpenShellGatewayServiceAccountCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenShellGatewayServiceAccountCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
