apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: hypershell-system
  labels:
    app: kube-state-metrics
    hypershell.redhat.io/prometheus-scrape: "true"
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
