apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - prometheus.yaml
  - servicemonitor.yaml
  - node-exporter.yaml
  - node-exporter-servicemonitor.yaml
  - kube-state-metrics.yaml
  - kube-state-metrics-servicemonitor.yaml
  - otel-collector.yaml
  - otel-collector-servicemonitor.yaml
