apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: hypershell
  namespace: hypershell-system
spec:
  serviceAccountName: prometheus
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
  serviceMonitorSelector:
    matchLabels:
      app: hypershell-api-server
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: hypershell-system
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  retention: 7d
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
