apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-https-tls
  namespace: hypershell-system
spec:
  secretName: hypershell-https-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
  dnsNames:
    - "*.hypershell.localhost"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-gw-tls
  namespace: hypershell-system
spec:
  secretName: hypershell-gw-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
  dnsNames:
    - "*.gw.localhost"
