apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - hypershell-db-cluster.yaml
  - api-server.yaml
  - controller.yaml
  - controller-rbac.yaml
  - web-console.yaml
  - certificates/
  - keycloak/
  - networkpolicies.yaml
