apiVersion: v1
kind: Secret
metadata:
  name: hypershell-db-app
  namespace: hypershell-system
  labels:
    app.kubernetes.io/name: hypershell
    app.kubernetes.io/component: database
type: Opaque
stringData:
  host: postgres.external-cloud-db.svc.cluster.local
  port: "5432"
  dbname: hypershell
  user: postgres
  password: hypershell-kind-admin-password
  sslmode: disable
