---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshell-gateway
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app.kubernetes.io/name: openshell
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: hypershell-control-plane
    hypershell.redhat.io/managed: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshell-gateway-sandbox
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app.kubernetes.io/name: openshell
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: hypershell-control-plane
    hypershell.redhat.io/managed: "true"
