apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hypershell-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-ca
  namespace: hypershell-system
spec:
  isCA: true
  commonName: hypershell-ca
  secretName: hypershell-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hypershell-ca-issuer
  namespace: hypershell-system
spec:
  ca:
    secretName: hypershell-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-https-tls
  namespace: hypershell-system
spec:
  secretName: hypershell-https-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
  dnsNames:
    - "*.hypershell.localhost"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-gw-tls
  namespace: hypershell-system
spec:
  secretName: hypershell-gw-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
  dnsNames:
    - "*.gw.localhost"
