# NEW ENDPOINT START
paths:
  /api/hypershell/v1/users:
    get:
      summary: List registered users
      operationId: listUsers
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/orderBy'
        - $ref: '#/components/parameters/fields'
      responses:
        '200':
          description: A list of registered users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        '401':
          $ref: 'openapi.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: 'openapi.yaml#/components/responses/ForbiddenError'
        '500':
          $ref: 'openapi.yaml#/components/responses/InternalServerError'
  /api/hypershell/v1/users/{id}:
    get:
      summary: Get a registered user by ID
      operationId: getUser
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: 'openapi.yaml#/components/responses/UnauthorizedError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          $ref: 'openapi.yaml#/components/responses/InternalServerError'
    parameters:
      - $ref: '#/components/parameters/id'
# NEW ENDPOINT END
components:
  schemas:
    # NEW SCHEMA START
    User:
      allOf:
        - $ref: 'openapi.yaml#/components/schemas/ObjectReference'
        - type: object
          required:
            - username
          properties:
            username:
              type: string
            email:
              type: string
            name:
              type: string
    # NEW SCHEMA END
    # NEW SCHEMA START
    UserList:
      allOf:
        - $ref: 'openapi.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/User'
    # NEW SCHEMA END
  parameters:
    id:
      name: id
      in: path
      description: The id of record
      required: true
      schema:
        type: string
    page:
      name: page
      in: query
      description: Page number of record list when record list exceeds specified page size
      schema:
        type: integer
        default: 1
        minimum: 1
      required: false
    size:
      name: size
      in: query
      description: Maximum number of records to return
      schema:
        type: integer
        default: 100
        minimum: 0
      required: false
    search:
      name: search
      in: query
      required: false
      description: Specifies the search criteria
      schema:
        type: string
    orderBy:
      name: orderBy
      in: query
      required: false
      description: Specifies the order by criteria
      schema:
        type: string
    fields:
      name: fields
      in: query
      required: false
      description: Supplies a comma-separated list of fields to be returned
      schema:
        type: string
