apiVersion: v1
kind: Service
metadata:
  name: hypershell-control-plane
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: provisioner
      port: 9443
      targetPort: provisioner
  selector:
    app: hypershell-control-plane
