apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-service-account-provisioner-server
  namespace: hypershell-system
spec:
  secretName: hypershell-service-account-provisioner-server-tls
  commonName: hypershell-controller
  dnsNames:
    - hypershell-controller
    - hypershell-controller.hypershell-system
    - hypershell-controller.hypershell-system.svc
    - hypershell-controller.hypershell-system.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-service-account-provisioner-client
  namespace: hypershell-system
spec:
  secretName: hypershell-service-account-provisioner-client-tls
  commonName: hypershell-api-server
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - client auth
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
