// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/fleets.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_GetFleet_FullMethodName    = "/hypershell.v1.FleetService/GetFleet"
	FleetService_CreateFleet_FullMethodName = "/hypershell.v1.FleetService/CreateFleet"
	FleetService_UpdateFleet_FullMethodName = "/hypershell.v1.FleetService/UpdateFleet"
	FleetService_DeleteFleet_FullMethodName = "/hypershell.v1.FleetService/DeleteFleet"
	FleetService_ListFleets_FullMethodName  = "/hypershell.v1.FleetService/ListFleets"
	FleetService_WatchFleets_FullMethodName = "/hypershell.v1.FleetService/WatchFleets"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetServiceClient interface {
	GetFleet(ctx context.Context, in *GetFleetRequest, opts ...grpc.CallOption) (*GetFleetResponse, error)
	CreateFleet(ctx context.Context, in *CreateFleetRequest, opts ...grpc.CallOption) (*CreateFleetResponse, error)
	UpdateFleet(ctx context.Context, in *UpdateFleetRequest, opts ...grpc.CallOption) (*UpdateFleetResponse, error)
	DeleteFleet(ctx context.Context, in *DeleteFleetRequest, opts ...grpc.CallOption) (*DeleteFleetResponse, error)
	ListFleets(ctx context.Context, in *ListFleetsRequest, opts ...grpc.CallOption) (*ListFleetsResponse, error)
	WatchFleets(ctx context.Context, in *WatchFleetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchFleetsResponse], error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) GetFleet(ctx context.Context, in *GetFleetRequest, opts ...grpc.CallOption) (*GetFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFleetResponse)
	err := c.cc.Invoke(ctx, FleetService_GetFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateFleet(ctx context.Context, in *CreateFleetRequest, opts ...grpc.CallOption) (*CreateFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFleetResponse)
	err := c.cc.Invoke(ctx, FleetService_CreateFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) UpdateFleet(ctx context.Context, in *UpdateFleetRequest, opts ...grpc.CallOption) (*UpdateFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFleetResponse)
	err := c.cc.Invoke(ctx, FleetService_UpdateFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteFleet(ctx context.Context, in *DeleteFleetRequest, opts ...grpc.CallOption) (*DeleteFleetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFleetResponse)
	err := c.cc.Invoke(ctx, FleetService_DeleteFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListFleets(ctx context.Context, in *ListFleetsRequest, opts ...grpc.CallOption) (*ListFleetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFleetsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListFleets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) WatchFleets(ctx context.Context, in *WatchFleetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchFleetsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[0], FleetService_WatchFleets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchFleetsRequest, WatchFleetsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_WatchFleetsClient = grpc.ServerStreamingClient[WatchFleetsResponse]

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
type FleetServiceServer interface {
	GetFleet(context.Context, *GetFleetRequest) (*GetFleetResponse, error)
	CreateFleet(context.Context, *CreateFleetRequest) (*CreateFleetResponse, error)
	UpdateFleet(context.Context, *UpdateFleetRequest) (*UpdateFleetResponse, error)
	DeleteFleet(context.Context, *DeleteFleetRequest) (*DeleteFleetResponse, error)
	ListFleets(context.Context, *ListFleetsRequest) (*ListFleetsResponse, error)
	WatchFleets(*WatchFleetsRequest, grpc.ServerStreamingServer[WatchFleetsResponse]) error
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) GetFleet(context.Context, *GetFleetRequest) (*GetFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFleet not implemented")
}
func (UnimplementedFleetServiceServer) CreateFleet(context.Context, *CreateFleetRequest) (*CreateFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFleet not implemented")
}
func (UnimplementedFleetServiceServer) UpdateFleet(context.Context, *UpdateFleetRequest) (*UpdateFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFleet not implemented")
}
func (UnimplementedFleetServiceServer) DeleteFleet(context.Context, *DeleteFleetRequest) (*DeleteFleetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFleet not implemented")
}
func (UnimplementedFleetServiceServer) ListFleets(context.Context, *ListFleetsRequest) (*ListFleetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFleets not implemented")
}
func (UnimplementedFleetServiceServer) WatchFleets(*WatchFleetsRequest, grpc.ServerStreamingServer[WatchFleetsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchFleets not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_GetFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetFleet(ctx, req.(*GetFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateFleet(ctx, req.(*CreateFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_UpdateFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).UpdateFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_UpdateFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).UpdateFleet(ctx, req.(*UpdateFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFleetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteFleet(ctx, req.(*DeleteFleetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListFleets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFleetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListFleets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListFleets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListFleets(ctx, req.(*ListFleetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_WatchFleets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchFleetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).WatchFleets(m, &grpc.GenericServerStream[WatchFleetsRequest, WatchFleetsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_WatchFleetsServer = grpc.ServerStreamingServer[WatchFleetsResponse]

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFleet",
			Handler:    _FleetService_GetFleet_Handler,
		},
		{
			MethodName: "CreateFleet",
			Handler:    _FleetService_CreateFleet_Handler,
		},
		{
			MethodName: "UpdateFleet",
			Handler:    _FleetService_UpdateFleet_Handler,
		},
		{
			MethodName: "DeleteFleet",
			Handler:    _FleetService_DeleteFleet_Handler,
		},
		{
			MethodName: "ListFleets",
			Handler:    _FleetService_ListFleets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchFleets",
			Handler:       _FleetService_WatchFleets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypershell/v1/fleets.proto",
}
