// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/gateway_profiles.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayProfileService_GetGatewayProfile_FullMethodName    = "/hypershell.v1.GatewayProfileService/GetGatewayProfile"
	GatewayProfileService_CreateGatewayProfile_FullMethodName = "/hypershell.v1.GatewayProfileService/CreateGatewayProfile"
	GatewayProfileService_UpdateGatewayProfile_FullMethodName = "/hypershell.v1.GatewayProfileService/UpdateGatewayProfile"
	GatewayProfileService_DeleteGatewayProfile_FullMethodName = "/hypershell.v1.GatewayProfileService/DeleteGatewayProfile"
	GatewayProfileService_ListGatewayProfiles_FullMethodName  = "/hypershell.v1.GatewayProfileService/ListGatewayProfiles"
)

// GatewayProfileServiceClient is the client API for GatewayProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayProfileService intentionally exposes no Watch RPC: the control plane
// does not reconcile GatewayProfile changes. A gateway's quota changes only when
// its profile_id is reassigned (a gateway update, delivered through the existing
// gateway watch stream). The control plane fetches profiles on demand via the
// unary GetGatewayProfile RPC while reconciling a gateway.
type GatewayProfileServiceClient interface {
	GetGatewayProfile(ctx context.Context, in *GetGatewayProfileRequest, opts ...grpc.CallOption) (*GetGatewayProfileResponse, error)
	CreateGatewayProfile(ctx context.Context, in *CreateGatewayProfileRequest, opts ...grpc.CallOption) (*CreateGatewayProfileResponse, error)
	UpdateGatewayProfile(ctx context.Context, in *UpdateGatewayProfileRequest, opts ...grpc.CallOption) (*UpdateGatewayProfileResponse, error)
	DeleteGatewayProfile(ctx context.Context, in *DeleteGatewayProfileRequest, opts ...grpc.CallOption) (*DeleteGatewayProfileResponse, error)
	ListGatewayProfiles(ctx context.Context, in *ListGatewayProfilesRequest, opts ...grpc.CallOption) (*ListGatewayProfilesResponse, error)
}

type gatewayProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayProfileServiceClient(cc grpc.ClientConnInterface) GatewayProfileServiceClient {
	return &gatewayProfileServiceClient{cc}
}

func (c *gatewayProfileServiceClient) GetGatewayProfile(ctx context.Context, in *GetGatewayProfileRequest, opts ...grpc.CallOption) (*GetGatewayProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayProfileResponse)
	err := c.cc.Invoke(ctx, GatewayProfileService_GetGatewayProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayProfileServiceClient) CreateGatewayProfile(ctx context.Context, in *CreateGatewayProfileRequest, opts ...grpc.CallOption) (*CreateGatewayProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGatewayProfileResponse)
	err := c.cc.Invoke(ctx, GatewayProfileService_CreateGatewayProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayProfileServiceClient) UpdateGatewayProfile(ctx context.Context, in *UpdateGatewayProfileRequest, opts ...grpc.CallOption) (*UpdateGatewayProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGatewayProfileResponse)
	err := c.cc.Invoke(ctx, GatewayProfileService_UpdateGatewayProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayProfileServiceClient) DeleteGatewayProfile(ctx context.Context, in *DeleteGatewayProfileRequest, opts ...grpc.CallOption) (*DeleteGatewayProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGatewayProfileResponse)
	err := c.cc.Invoke(ctx, GatewayProfileService_DeleteGatewayProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayProfileServiceClient) ListGatewayProfiles(ctx context.Context, in *ListGatewayProfilesRequest, opts ...grpc.CallOption) (*ListGatewayProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewayProfilesResponse)
	err := c.cc.Invoke(ctx, GatewayProfileService_ListGatewayProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayProfileServiceServer is the server API for GatewayProfileService service.
// All implementations must embed UnimplementedGatewayProfileServiceServer
// for forward compatibility.
//
// GatewayProfileService intentionally exposes no Watch RPC: the control plane
// does not reconcile GatewayProfile changes. A gateway's quota changes only when
// its profile_id is reassigned (a gateway update, delivered through the existing
// gateway watch stream). The control plane fetches profiles on demand via the
// unary GetGatewayProfile RPC while reconciling a gateway.
type GatewayProfileServiceServer interface {
	GetGatewayProfile(context.Context, *GetGatewayProfileRequest) (*GetGatewayProfileResponse, error)
	CreateGatewayProfile(context.Context, *CreateGatewayProfileRequest) (*CreateGatewayProfileResponse, error)
	UpdateGatewayProfile(context.Context, *UpdateGatewayProfileRequest) (*UpdateGatewayProfileResponse, error)
	DeleteGatewayProfile(context.Context, *DeleteGatewayProfileRequest) (*DeleteGatewayProfileResponse, error)
	ListGatewayProfiles(context.Context, *ListGatewayProfilesRequest) (*ListGatewayProfilesResponse, error)
	mustEmbedUnimplementedGatewayProfileServiceServer()
}

// UnimplementedGatewayProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayProfileServiceServer struct{}

func (UnimplementedGatewayProfileServiceServer) GetGatewayProfile(context.Context, *GetGatewayProfileRequest) (*GetGatewayProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGatewayProfile not implemented")
}
func (UnimplementedGatewayProfileServiceServer) CreateGatewayProfile(context.Context, *CreateGatewayProfileRequest) (*CreateGatewayProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGatewayProfile not implemented")
}
func (UnimplementedGatewayProfileServiceServer) UpdateGatewayProfile(context.Context, *UpdateGatewayProfileRequest) (*UpdateGatewayProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGatewayProfile not implemented")
}
func (UnimplementedGatewayProfileServiceServer) DeleteGatewayProfile(context.Context, *DeleteGatewayProfileRequest) (*DeleteGatewayProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGatewayProfile not implemented")
}
func (UnimplementedGatewayProfileServiceServer) ListGatewayProfiles(context.Context, *ListGatewayProfilesRequest) (*ListGatewayProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGatewayProfiles not implemented")
}
func (UnimplementedGatewayProfileServiceServer) mustEmbedUnimplementedGatewayProfileServiceServer() {}
func (UnimplementedGatewayProfileServiceServer) testEmbeddedByValue()                               {}

// UnsafeGatewayProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayProfileServiceServer will
// result in compilation errors.
type UnsafeGatewayProfileServiceServer interface {
	mustEmbedUnimplementedGatewayProfileServiceServer()
}

func RegisterGatewayProfileServiceServer(s grpc.ServiceRegistrar, srv GatewayProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayProfileService_ServiceDesc, srv)
}

func _GatewayProfileService_GetGatewayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProfileServiceServer).GetGatewayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayProfileService_GetGatewayProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProfileServiceServer).GetGatewayProfile(ctx, req.(*GetGatewayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayProfileService_CreateGatewayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProfileServiceServer).CreateGatewayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayProfileService_CreateGatewayProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProfileServiceServer).CreateGatewayProfile(ctx, req.(*CreateGatewayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayProfileService_UpdateGatewayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProfileServiceServer).UpdateGatewayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayProfileService_UpdateGatewayProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProfileServiceServer).UpdateGatewayProfile(ctx, req.(*UpdateGatewayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayProfileService_DeleteGatewayProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProfileServiceServer).DeleteGatewayProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayProfileService_DeleteGatewayProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProfileServiceServer).DeleteGatewayProfile(ctx, req.(*DeleteGatewayProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayProfileService_ListGatewayProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayProfileServiceServer).ListGatewayProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayProfileService_ListGatewayProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayProfileServiceServer).ListGatewayProfiles(ctx, req.(*ListGatewayProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayProfileService_ServiceDesc is the grpc.ServiceDesc for GatewayProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.GatewayProfileService",
	HandlerType: (*GatewayProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayProfile",
			Handler:    _GatewayProfileService_GetGatewayProfile_Handler,
		},
		{
			MethodName: "CreateGatewayProfile",
			Handler:    _GatewayProfileService_CreateGatewayProfile_Handler,
		},
		{
			MethodName: "UpdateGatewayProfile",
			Handler:    _GatewayProfileService_UpdateGatewayProfile_Handler,
		},
		{
			MethodName: "DeleteGatewayProfile",
			Handler:    _GatewayProfileService_DeleteGatewayProfile_Handler,
		},
		{
			MethodName: "ListGatewayProfiles",
			Handler:    _GatewayProfileService_ListGatewayProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypershell/v1/gateway_profiles.proto",
}
