// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/gateway_networks.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayNetworkService_GetGatewayNetwork_FullMethodName    = "/hypershell.v1.GatewayNetworkService/GetGatewayNetwork"
	GatewayNetworkService_CreateGatewayNetwork_FullMethodName = "/hypershell.v1.GatewayNetworkService/CreateGatewayNetwork"
	GatewayNetworkService_UpdateGatewayNetwork_FullMethodName = "/hypershell.v1.GatewayNetworkService/UpdateGatewayNetwork"
	GatewayNetworkService_DeleteGatewayNetwork_FullMethodName = "/hypershell.v1.GatewayNetworkService/DeleteGatewayNetwork"
	GatewayNetworkService_ListGatewayNetworks_FullMethodName  = "/hypershell.v1.GatewayNetworkService/ListGatewayNetworks"
	GatewayNetworkService_WatchGatewayNetworks_FullMethodName = "/hypershell.v1.GatewayNetworkService/WatchGatewayNetworks"
)

// GatewayNetworkServiceClient is the client API for GatewayNetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayNetworkServiceClient interface {
	GetGatewayNetwork(ctx context.Context, in *GetGatewayNetworkRequest, opts ...grpc.CallOption) (*GetGatewayNetworkResponse, error)
	CreateGatewayNetwork(ctx context.Context, in *CreateGatewayNetworkRequest, opts ...grpc.CallOption) (*CreateGatewayNetworkResponse, error)
	UpdateGatewayNetwork(ctx context.Context, in *UpdateGatewayNetworkRequest, opts ...grpc.CallOption) (*UpdateGatewayNetworkResponse, error)
	DeleteGatewayNetwork(ctx context.Context, in *DeleteGatewayNetworkRequest, opts ...grpc.CallOption) (*DeleteGatewayNetworkResponse, error)
	ListGatewayNetworks(ctx context.Context, in *ListGatewayNetworksRequest, opts ...grpc.CallOption) (*ListGatewayNetworksResponse, error)
	WatchGatewayNetworks(ctx context.Context, in *WatchGatewayNetworksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayNetworksResponse], error)
}

type gatewayNetworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNetworkServiceClient(cc grpc.ClientConnInterface) GatewayNetworkServiceClient {
	return &gatewayNetworkServiceClient{cc}
}

func (c *gatewayNetworkServiceClient) GetGatewayNetwork(ctx context.Context, in *GetGatewayNetworkRequest, opts ...grpc.CallOption) (*GetGatewayNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayNetworkResponse)
	err := c.cc.Invoke(ctx, GatewayNetworkService_GetGatewayNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkServiceClient) CreateGatewayNetwork(ctx context.Context, in *CreateGatewayNetworkRequest, opts ...grpc.CallOption) (*CreateGatewayNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGatewayNetworkResponse)
	err := c.cc.Invoke(ctx, GatewayNetworkService_CreateGatewayNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkServiceClient) UpdateGatewayNetwork(ctx context.Context, in *UpdateGatewayNetworkRequest, opts ...grpc.CallOption) (*UpdateGatewayNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGatewayNetworkResponse)
	err := c.cc.Invoke(ctx, GatewayNetworkService_UpdateGatewayNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkServiceClient) DeleteGatewayNetwork(ctx context.Context, in *DeleteGatewayNetworkRequest, opts ...grpc.CallOption) (*DeleteGatewayNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGatewayNetworkResponse)
	err := c.cc.Invoke(ctx, GatewayNetworkService_DeleteGatewayNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkServiceClient) ListGatewayNetworks(ctx context.Context, in *ListGatewayNetworksRequest, opts ...grpc.CallOption) (*ListGatewayNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewayNetworksResponse)
	err := c.cc.Invoke(ctx, GatewayNetworkService_ListGatewayNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayNetworkServiceClient) WatchGatewayNetworks(ctx context.Context, in *WatchGatewayNetworksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayNetworksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayNetworkService_ServiceDesc.Streams[0], GatewayNetworkService_WatchGatewayNetworks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchGatewayNetworksRequest, WatchGatewayNetworksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayNetworkService_WatchGatewayNetworksClient = grpc.ServerStreamingClient[WatchGatewayNetworksResponse]

// GatewayNetworkServiceServer is the server API for GatewayNetworkService service.
// All implementations must embed UnimplementedGatewayNetworkServiceServer
// for forward compatibility.
type GatewayNetworkServiceServer interface {
	GetGatewayNetwork(context.Context, *GetGatewayNetworkRequest) (*GetGatewayNetworkResponse, error)
	CreateGatewayNetwork(context.Context, *CreateGatewayNetworkRequest) (*CreateGatewayNetworkResponse, error)
	UpdateGatewayNetwork(context.Context, *UpdateGatewayNetworkRequest) (*UpdateGatewayNetworkResponse, error)
	DeleteGatewayNetwork(context.Context, *DeleteGatewayNetworkRequest) (*DeleteGatewayNetworkResponse, error)
	ListGatewayNetworks(context.Context, *ListGatewayNetworksRequest) (*ListGatewayNetworksResponse, error)
	WatchGatewayNetworks(*WatchGatewayNetworksRequest, grpc.ServerStreamingServer[WatchGatewayNetworksResponse]) error
	mustEmbedUnimplementedGatewayNetworkServiceServer()
}

// UnimplementedGatewayNetworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayNetworkServiceServer struct{}

func (UnimplementedGatewayNetworkServiceServer) GetGatewayNetwork(context.Context, *GetGatewayNetworkRequest) (*GetGatewayNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGatewayNetwork not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) CreateGatewayNetwork(context.Context, *CreateGatewayNetworkRequest) (*CreateGatewayNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGatewayNetwork not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) UpdateGatewayNetwork(context.Context, *UpdateGatewayNetworkRequest) (*UpdateGatewayNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGatewayNetwork not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) DeleteGatewayNetwork(context.Context, *DeleteGatewayNetworkRequest) (*DeleteGatewayNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGatewayNetwork not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) ListGatewayNetworks(context.Context, *ListGatewayNetworksRequest) (*ListGatewayNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGatewayNetworks not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) WatchGatewayNetworks(*WatchGatewayNetworksRequest, grpc.ServerStreamingServer[WatchGatewayNetworksResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchGatewayNetworks not implemented")
}
func (UnimplementedGatewayNetworkServiceServer) mustEmbedUnimplementedGatewayNetworkServiceServer() {}
func (UnimplementedGatewayNetworkServiceServer) testEmbeddedByValue()                               {}

// UnsafeGatewayNetworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNetworkServiceServer will
// result in compilation errors.
type UnsafeGatewayNetworkServiceServer interface {
	mustEmbedUnimplementedGatewayNetworkServiceServer()
}

func RegisterGatewayNetworkServiceServer(s grpc.ServiceRegistrar, srv GatewayNetworkServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayNetworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayNetworkService_ServiceDesc, srv)
}

func _GatewayNetworkService_GetGatewayNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServiceServer).GetGatewayNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNetworkService_GetGatewayNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServiceServer).GetGatewayNetwork(ctx, req.(*GetGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetworkService_CreateGatewayNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServiceServer).CreateGatewayNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNetworkService_CreateGatewayNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServiceServer).CreateGatewayNetwork(ctx, req.(*CreateGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetworkService_UpdateGatewayNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServiceServer).UpdateGatewayNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNetworkService_UpdateGatewayNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServiceServer).UpdateGatewayNetwork(ctx, req.(*UpdateGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetworkService_DeleteGatewayNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServiceServer).DeleteGatewayNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNetworkService_DeleteGatewayNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServiceServer).DeleteGatewayNetwork(ctx, req.(*DeleteGatewayNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetworkService_ListGatewayNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNetworkServiceServer).ListGatewayNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNetworkService_ListGatewayNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNetworkServiceServer).ListGatewayNetworks(ctx, req.(*ListGatewayNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayNetworkService_WatchGatewayNetworks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchGatewayNetworksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayNetworkServiceServer).WatchGatewayNetworks(m, &grpc.GenericServerStream[WatchGatewayNetworksRequest, WatchGatewayNetworksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayNetworkService_WatchGatewayNetworksServer = grpc.ServerStreamingServer[WatchGatewayNetworksResponse]

// GatewayNetworkService_ServiceDesc is the grpc.ServiceDesc for GatewayNetworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNetworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.GatewayNetworkService",
	HandlerType: (*GatewayNetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayNetwork",
			Handler:    _GatewayNetworkService_GetGatewayNetwork_Handler,
		},
		{
			MethodName: "CreateGatewayNetwork",
			Handler:    _GatewayNetworkService_CreateGatewayNetwork_Handler,
		},
		{
			MethodName: "UpdateGatewayNetwork",
			Handler:    _GatewayNetworkService_UpdateGatewayNetwork_Handler,
		},
		{
			MethodName: "DeleteGatewayNetwork",
			Handler:    _GatewayNetworkService_DeleteGatewayNetwork_Handler,
		},
		{
			MethodName: "ListGatewayNetworks",
			Handler:    _GatewayNetworkService_ListGatewayNetworks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGatewayNetworks",
			Handler:       _GatewayNetworkService_WatchGatewayNetworks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypershell/v1/gateway_networks.proto",
}
