// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/gateway_releases.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayReleaseService_GetGatewayRelease_FullMethodName    = "/hypershell.v1.GatewayReleaseService/GetGatewayRelease"
	GatewayReleaseService_CreateGatewayRelease_FullMethodName = "/hypershell.v1.GatewayReleaseService/CreateGatewayRelease"
	GatewayReleaseService_UpdateGatewayRelease_FullMethodName = "/hypershell.v1.GatewayReleaseService/UpdateGatewayRelease"
	GatewayReleaseService_DeleteGatewayRelease_FullMethodName = "/hypershell.v1.GatewayReleaseService/DeleteGatewayRelease"
	GatewayReleaseService_ListGatewayReleases_FullMethodName  = "/hypershell.v1.GatewayReleaseService/ListGatewayReleases"
	GatewayReleaseService_WatchGatewayReleases_FullMethodName = "/hypershell.v1.GatewayReleaseService/WatchGatewayReleases"
)

// GatewayReleaseServiceClient is the client API for GatewayReleaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayReleaseServiceClient interface {
	GetGatewayRelease(ctx context.Context, in *GetGatewayReleaseRequest, opts ...grpc.CallOption) (*GetGatewayReleaseResponse, error)
	CreateGatewayRelease(ctx context.Context, in *CreateGatewayReleaseRequest, opts ...grpc.CallOption) (*CreateGatewayReleaseResponse, error)
	UpdateGatewayRelease(ctx context.Context, in *UpdateGatewayReleaseRequest, opts ...grpc.CallOption) (*UpdateGatewayReleaseResponse, error)
	DeleteGatewayRelease(ctx context.Context, in *DeleteGatewayReleaseRequest, opts ...grpc.CallOption) (*DeleteGatewayReleaseResponse, error)
	ListGatewayReleases(ctx context.Context, in *ListGatewayReleasesRequest, opts ...grpc.CallOption) (*ListGatewayReleasesResponse, error)
	WatchGatewayReleases(ctx context.Context, in *WatchGatewayReleasesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayReleasesResponse], error)
}

type gatewayReleaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayReleaseServiceClient(cc grpc.ClientConnInterface) GatewayReleaseServiceClient {
	return &gatewayReleaseServiceClient{cc}
}

func (c *gatewayReleaseServiceClient) GetGatewayRelease(ctx context.Context, in *GetGatewayReleaseRequest, opts ...grpc.CallOption) (*GetGatewayReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayReleaseResponse)
	err := c.cc.Invoke(ctx, GatewayReleaseService_GetGatewayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayReleaseServiceClient) CreateGatewayRelease(ctx context.Context, in *CreateGatewayReleaseRequest, opts ...grpc.CallOption) (*CreateGatewayReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGatewayReleaseResponse)
	err := c.cc.Invoke(ctx, GatewayReleaseService_CreateGatewayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayReleaseServiceClient) UpdateGatewayRelease(ctx context.Context, in *UpdateGatewayReleaseRequest, opts ...grpc.CallOption) (*UpdateGatewayReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGatewayReleaseResponse)
	err := c.cc.Invoke(ctx, GatewayReleaseService_UpdateGatewayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayReleaseServiceClient) DeleteGatewayRelease(ctx context.Context, in *DeleteGatewayReleaseRequest, opts ...grpc.CallOption) (*DeleteGatewayReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGatewayReleaseResponse)
	err := c.cc.Invoke(ctx, GatewayReleaseService_DeleteGatewayRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayReleaseServiceClient) ListGatewayReleases(ctx context.Context, in *ListGatewayReleasesRequest, opts ...grpc.CallOption) (*ListGatewayReleasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewayReleasesResponse)
	err := c.cc.Invoke(ctx, GatewayReleaseService_ListGatewayReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayReleaseServiceClient) WatchGatewayReleases(ctx context.Context, in *WatchGatewayReleasesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGatewayReleasesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayReleaseService_ServiceDesc.Streams[0], GatewayReleaseService_WatchGatewayReleases_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchGatewayReleasesRequest, WatchGatewayReleasesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayReleaseService_WatchGatewayReleasesClient = grpc.ServerStreamingClient[WatchGatewayReleasesResponse]

// GatewayReleaseServiceServer is the server API for GatewayReleaseService service.
// All implementations must embed UnimplementedGatewayReleaseServiceServer
// for forward compatibility.
type GatewayReleaseServiceServer interface {
	GetGatewayRelease(context.Context, *GetGatewayReleaseRequest) (*GetGatewayReleaseResponse, error)
	CreateGatewayRelease(context.Context, *CreateGatewayReleaseRequest) (*CreateGatewayReleaseResponse, error)
	UpdateGatewayRelease(context.Context, *UpdateGatewayReleaseRequest) (*UpdateGatewayReleaseResponse, error)
	DeleteGatewayRelease(context.Context, *DeleteGatewayReleaseRequest) (*DeleteGatewayReleaseResponse, error)
	ListGatewayReleases(context.Context, *ListGatewayReleasesRequest) (*ListGatewayReleasesResponse, error)
	WatchGatewayReleases(*WatchGatewayReleasesRequest, grpc.ServerStreamingServer[WatchGatewayReleasesResponse]) error
	mustEmbedUnimplementedGatewayReleaseServiceServer()
}

// UnimplementedGatewayReleaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayReleaseServiceServer struct{}

func (UnimplementedGatewayReleaseServiceServer) GetGatewayRelease(context.Context, *GetGatewayReleaseRequest) (*GetGatewayReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGatewayRelease not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) CreateGatewayRelease(context.Context, *CreateGatewayReleaseRequest) (*CreateGatewayReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGatewayRelease not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) UpdateGatewayRelease(context.Context, *UpdateGatewayReleaseRequest) (*UpdateGatewayReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGatewayRelease not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) DeleteGatewayRelease(context.Context, *DeleteGatewayReleaseRequest) (*DeleteGatewayReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGatewayRelease not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) ListGatewayReleases(context.Context, *ListGatewayReleasesRequest) (*ListGatewayReleasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGatewayReleases not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) WatchGatewayReleases(*WatchGatewayReleasesRequest, grpc.ServerStreamingServer[WatchGatewayReleasesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchGatewayReleases not implemented")
}
func (UnimplementedGatewayReleaseServiceServer) mustEmbedUnimplementedGatewayReleaseServiceServer() {}
func (UnimplementedGatewayReleaseServiceServer) testEmbeddedByValue()                               {}

// UnsafeGatewayReleaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayReleaseServiceServer will
// result in compilation errors.
type UnsafeGatewayReleaseServiceServer interface {
	mustEmbedUnimplementedGatewayReleaseServiceServer()
}

func RegisterGatewayReleaseServiceServer(s grpc.ServiceRegistrar, srv GatewayReleaseServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayReleaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayReleaseService_ServiceDesc, srv)
}

func _GatewayReleaseService_GetGatewayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayReleaseServiceServer).GetGatewayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayReleaseService_GetGatewayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayReleaseServiceServer).GetGatewayRelease(ctx, req.(*GetGatewayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayReleaseService_CreateGatewayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGatewayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayReleaseServiceServer).CreateGatewayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayReleaseService_CreateGatewayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayReleaseServiceServer).CreateGatewayRelease(ctx, req.(*CreateGatewayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayReleaseService_UpdateGatewayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGatewayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayReleaseServiceServer).UpdateGatewayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayReleaseService_UpdateGatewayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayReleaseServiceServer).UpdateGatewayRelease(ctx, req.(*UpdateGatewayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayReleaseService_DeleteGatewayRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayReleaseServiceServer).DeleteGatewayRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayReleaseService_DeleteGatewayRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayReleaseServiceServer).DeleteGatewayRelease(ctx, req.(*DeleteGatewayReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayReleaseService_ListGatewayReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewayReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayReleaseServiceServer).ListGatewayReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayReleaseService_ListGatewayReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayReleaseServiceServer).ListGatewayReleases(ctx, req.(*ListGatewayReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayReleaseService_WatchGatewayReleases_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchGatewayReleasesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayReleaseServiceServer).WatchGatewayReleases(m, &grpc.GenericServerStream[WatchGatewayReleasesRequest, WatchGatewayReleasesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayReleaseService_WatchGatewayReleasesServer = grpc.ServerStreamingServer[WatchGatewayReleasesResponse]

// GatewayReleaseService_ServiceDesc is the grpc.ServiceDesc for GatewayReleaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayReleaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.GatewayReleaseService",
	HandlerType: (*GatewayReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayRelease",
			Handler:    _GatewayReleaseService_GetGatewayRelease_Handler,
		},
		{
			MethodName: "CreateGatewayRelease",
			Handler:    _GatewayReleaseService_CreateGatewayRelease_Handler,
		},
		{
			MethodName: "UpdateGatewayRelease",
			Handler:    _GatewayReleaseService_UpdateGatewayRelease_Handler,
		},
		{
			MethodName: "DeleteGatewayRelease",
			Handler:    _GatewayReleaseService_DeleteGatewayRelease_Handler,
		},
		{
			MethodName: "ListGatewayReleases",
			Handler:    _GatewayReleaseService_ListGatewayReleases_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGatewayReleases",
			Handler:       _GatewayReleaseService_WatchGatewayReleases_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypershell/v1/gateway_releases.proto",
}
