// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hypershell/v1/managed_clusters.proto

package hypershell_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagedCluster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider         string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Region           *string                `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	KubeconfigSecret string                 `protobuf:"bytes,6,opt,name=kubeconfig_secret,json=kubeconfigSecret,proto3" json:"kubeconfig_secret,omitempty"`
	Status           *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ApiServerUrl     *string                `protobuf:"bytes,8,opt,name=api_server_url,json=apiServerUrl,proto3,oneof" json:"api_server_url,omitempty"`
	ProfileId        *string                `protobuf:"bytes,9,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	DatabaseId       *string                `protobuf:"bytes,10,opt,name=database_id,json=databaseId,proto3,oneof" json:"database_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManagedCluster) Reset() {
	*x = ManagedCluster{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCluster) ProtoMessage() {}

func (x *ManagedCluster) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCluster.ProtoReflect.Descriptor instead.
func (*ManagedCluster) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedCluster) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ManagedCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedCluster) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ManagedCluster) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *ManagedCluster) GetKubeconfigSecret() string {
	if x != nil {
		return x.KubeconfigSecret
	}
	return ""
}

func (x *ManagedCluster) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ManagedCluster) GetApiServerUrl() string {
	if x != nil && x.ApiServerUrl != nil {
		return *x.ApiServerUrl
	}
	return ""
}

func (x *ManagedCluster) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *ManagedCluster) GetDatabaseId() string {
	if x != nil && x.DatabaseId != nil {
		return *x.DatabaseId
	}
	return ""
}

type CreateManagedClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider         string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Region           *string                `protobuf:"bytes,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	KubeconfigSecret string                 `protobuf:"bytes,5,opt,name=kubeconfig_secret,json=kubeconfigSecret,proto3" json:"kubeconfig_secret,omitempty"`
	Status           *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ApiServerUrl     *string                `protobuf:"bytes,7,opt,name=api_server_url,json=apiServerUrl,proto3,oneof" json:"api_server_url,omitempty"`
	ProfileId        *string                `protobuf:"bytes,8,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	DatabaseId       *string                `protobuf:"bytes,9,opt,name=database_id,json=databaseId,proto3,oneof" json:"database_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateManagedClusterRequest) Reset() {
	*x = CreateManagedClusterRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManagedClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManagedClusterRequest) ProtoMessage() {}

func (x *CreateManagedClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManagedClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateManagedClusterRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{1}
}

func (x *CreateManagedClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetKubeconfigSecret() string {
	if x != nil {
		return x.KubeconfigSecret
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetApiServerUrl() string {
	if x != nil && x.ApiServerUrl != nil {
		return *x.ApiServerUrl
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *CreateManagedClusterRequest) GetDatabaseId() string {
	if x != nil && x.DatabaseId != nil {
		return *x.DatabaseId
	}
	return ""
}

type CreateManagedClusterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManagedCluster *ManagedCluster        `protobuf:"bytes,1,opt,name=managed_cluster,json=managedCluster,proto3" json:"managed_cluster,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateManagedClusterResponse) Reset() {
	*x = CreateManagedClusterResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManagedClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManagedClusterResponse) ProtoMessage() {}

func (x *CreateManagedClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManagedClusterResponse.ProtoReflect.Descriptor instead.
func (*CreateManagedClusterResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{2}
}

func (x *CreateManagedClusterResponse) GetManagedCluster() *ManagedCluster {
	if x != nil {
		return x.ManagedCluster
	}
	return nil
}

type GetManagedClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedClusterRequest) Reset() {
	*x = GetManagedClusterRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedClusterRequest) ProtoMessage() {}

func (x *GetManagedClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedClusterRequest.ProtoReflect.Descriptor instead.
func (*GetManagedClusterRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{3}
}

func (x *GetManagedClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetManagedClusterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManagedCluster *ManagedCluster        `protobuf:"bytes,1,opt,name=managed_cluster,json=managedCluster,proto3" json:"managed_cluster,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetManagedClusterResponse) Reset() {
	*x = GetManagedClusterResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedClusterResponse) ProtoMessage() {}

func (x *GetManagedClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedClusterResponse.ProtoReflect.Descriptor instead.
func (*GetManagedClusterResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{4}
}

func (x *GetManagedClusterResponse) GetManagedCluster() *ManagedCluster {
	if x != nil {
		return x.ManagedCluster
	}
	return nil
}

type UpdateManagedClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Provider         *string                `protobuf:"bytes,4,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Region           *string                `protobuf:"bytes,5,opt,name=region,proto3,oneof" json:"region,omitempty"`
	KubeconfigSecret *string                `protobuf:"bytes,6,opt,name=kubeconfig_secret,json=kubeconfigSecret,proto3,oneof" json:"kubeconfig_secret,omitempty"`
	Status           *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ApiServerUrl     *string                `protobuf:"bytes,8,opt,name=api_server_url,json=apiServerUrl,proto3,oneof" json:"api_server_url,omitempty"`
	ProfileId        *string                `protobuf:"bytes,9,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	DatabaseId       *string                `protobuf:"bytes,10,opt,name=database_id,json=databaseId,proto3,oneof" json:"database_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateManagedClusterRequest) Reset() {
	*x = UpdateManagedClusterRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManagedClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManagedClusterRequest) ProtoMessage() {}

func (x *UpdateManagedClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManagedClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateManagedClusterRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateManagedClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetKubeconfigSecret() string {
	if x != nil && x.KubeconfigSecret != nil {
		return *x.KubeconfigSecret
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetApiServerUrl() string {
	if x != nil && x.ApiServerUrl != nil {
		return *x.ApiServerUrl
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *UpdateManagedClusterRequest) GetDatabaseId() string {
	if x != nil && x.DatabaseId != nil {
		return *x.DatabaseId
	}
	return ""
}

type UpdateManagedClusterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManagedCluster *ManagedCluster        `protobuf:"bytes,1,opt,name=managed_cluster,json=managedCluster,proto3" json:"managed_cluster,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateManagedClusterResponse) Reset() {
	*x = UpdateManagedClusterResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManagedClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManagedClusterResponse) ProtoMessage() {}

func (x *UpdateManagedClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManagedClusterResponse.ProtoReflect.Descriptor instead.
func (*UpdateManagedClusterResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateManagedClusterResponse) GetManagedCluster() *ManagedCluster {
	if x != nil {
		return x.ManagedCluster
	}
	return nil
}

type DeleteManagedClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManagedClusterRequest) Reset() {
	*x = DeleteManagedClusterRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManagedClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManagedClusterRequest) ProtoMessage() {}

func (x *DeleteManagedClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManagedClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteManagedClusterRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteManagedClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListManagedClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedClustersRequest) Reset() {
	*x = ListManagedClustersRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedClustersRequest) ProtoMessage() {}

func (x *ListManagedClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedClustersRequest.ProtoReflect.Descriptor instead.
func (*ListManagedClustersRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{8}
}

func (x *ListManagedClustersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListManagedClustersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListManagedClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ManagedCluster      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedClustersResponse) Reset() {
	*x = ListManagedClustersResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedClustersResponse) ProtoMessage() {}

func (x *ListManagedClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedClustersResponse.ProtoReflect.Descriptor instead.
func (*ListManagedClustersResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{9}
}

func (x *ListManagedClustersResponse) GetItems() []*ManagedCluster {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListManagedClustersResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteManagedClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManagedClusterResponse) Reset() {
	*x = DeleteManagedClusterResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManagedClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManagedClusterResponse) ProtoMessage() {}

func (x *DeleteManagedClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManagedClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteManagedClusterResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{10}
}

type WatchManagedClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchManagedClustersRequest) Reset() {
	*x = WatchManagedClustersRequest{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchManagedClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchManagedClustersRequest) ProtoMessage() {}

func (x *WatchManagedClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchManagedClustersRequest.ProtoReflect.Descriptor instead.
func (*WatchManagedClustersRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{11}
}

type WatchManagedClustersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=hypershell.v1.EventType" json:"type,omitempty"`
	ManagedCluster *ManagedCluster        `protobuf:"bytes,2,opt,name=managed_cluster,json=managedCluster,proto3" json:"managed_cluster,omitempty"`
	ResourceId     string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchManagedClustersResponse) Reset() {
	*x = WatchManagedClustersResponse{}
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchManagedClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchManagedClustersResponse) ProtoMessage() {}

func (x *WatchManagedClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_managed_clusters_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchManagedClustersResponse.ProtoReflect.Descriptor instead.
func (*WatchManagedClustersResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_managed_clusters_proto_rawDescGZIP(), []int{12}
}

func (x *WatchManagedClustersResponse) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchManagedClustersResponse) GetManagedCluster() *ManagedCluster {
	if x != nil {
		return x.ManagedCluster
	}
	return nil
}

func (x *WatchManagedClustersResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_hypershell_v1_managed_clusters_proto protoreflect.FileDescriptor

const file_hypershell_v1_managed_clusters_proto_rawDesc = "" +
	"\n" +
	"$hypershell/v1/managed_clusters.proto\x12\rhypershell.v1\x1a\x1ahypershell/v1/common.proto\"\xb0\x03\n" +
	"\x0eManagedCluster\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.hypershell.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x00R\x06region\x88\x01\x01\x12+\n" +
	"\x11kubeconfig_secret\x18\x06 \x01(\tR\x10kubeconfigSecret\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x01R\x06status\x88\x01\x01\x12)\n" +
	"\x0eapi_server_url\x18\b \x01(\tH\x02R\fapiServerUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"profile_id\x18\t \x01(\tH\x03R\tprofileId\x88\x01\x01\x12$\n" +
	"\vdatabase_id\x18\n" +
	" \x01(\tH\x04R\n" +
	"databaseId\x88\x01\x01B\t\n" +
	"\a_regionB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_api_server_urlB\r\n" +
	"\v_profile_idB\x0e\n" +
	"\f_database_idJ\x04\b\x03\x10\x04R\bfleet_id\"\x81\x03\n" +
	"\x1bCreateManagedClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\tH\x00R\x06region\x88\x01\x01\x12+\n" +
	"\x11kubeconfig_secret\x18\x05 \x01(\tR\x10kubeconfigSecret\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x01R\x06status\x88\x01\x01\x12)\n" +
	"\x0eapi_server_url\x18\a \x01(\tH\x02R\fapiServerUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"profile_id\x18\b \x01(\tH\x03R\tprofileId\x88\x01\x01\x12$\n" +
	"\vdatabase_id\x18\t \x01(\tH\x04R\n" +
	"databaseId\x88\x01\x01B\t\n" +
	"\a_regionB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_api_server_urlB\r\n" +
	"\v_profile_idB\x0e\n" +
	"\f_database_idJ\x04\b\x02\x10\x03R\bfleet_id\"f\n" +
	"\x1cCreateManagedClusterResponse\x12F\n" +
	"\x0fmanaged_cluster\x18\x01 \x01(\v2\x1d.hypershell.v1.ManagedClusterR\x0emanagedCluster\"*\n" +
	"\x18GetManagedClusterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x19GetManagedClusterResponse\x12F\n" +
	"\x0fmanaged_cluster\x18\x01 \x01(\v2\x1d.hypershell.v1.ManagedClusterR\x0emanagedCluster\"\xcc\x03\n" +
	"\x1bUpdateManagedClusterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x04 \x01(\tH\x01R\bprovider\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x05 \x01(\tH\x02R\x06region\x88\x01\x01\x120\n" +
	"\x11kubeconfig_secret\x18\x06 \x01(\tH\x03R\x10kubeconfigSecret\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x04R\x06status\x88\x01\x01\x12)\n" +
	"\x0eapi_server_url\x18\b \x01(\tH\x05R\fapiServerUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"profile_id\x18\t \x01(\tH\x06R\tprofileId\x88\x01\x01\x12$\n" +
	"\vdatabase_id\x18\n" +
	" \x01(\tH\aR\n" +
	"databaseId\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_providerB\t\n" +
	"\a_regionB\x14\n" +
	"\x12_kubeconfig_secretB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_api_server_urlB\r\n" +
	"\v_profile_idB\x0e\n" +
	"\f_database_idJ\x04\b\x03\x10\x04R\bfleet_id\"f\n" +
	"\x1cUpdateManagedClusterResponse\x12F\n" +
	"\x0fmanaged_cluster\x18\x01 \x01(\v2\x1d.hypershell.v1.ManagedClusterR\x0emanagedCluster\"-\n" +
	"\x1bDeleteManagedClusterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x1aListManagedClustersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x87\x01\n" +
	"\x1bListManagedClustersResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.hypershell.v1.ManagedClusterR\x05items\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.hypershell.v1.ListMetaR\bmetadata\"\x1e\n" +
	"\x1cDeleteManagedClusterResponse\"\x1d\n" +
	"\x1bWatchManagedClustersRequest\"\xb5\x01\n" +
	"\x1cWatchManagedClustersResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.hypershell.v1.EventTypeR\x04type\x12F\n" +
	"\x0fmanaged_cluster\x18\x02 \x01(\v2\x1d.hypershell.v1.ManagedClusterR\x0emanagedCluster\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xb3\x05\n" +
	"\x15ManagedClusterService\x12f\n" +
	"\x11GetManagedCluster\x12'.hypershell.v1.GetManagedClusterRequest\x1a(.hypershell.v1.GetManagedClusterResponse\x12o\n" +
	"\x14CreateManagedCluster\x12*.hypershell.v1.CreateManagedClusterRequest\x1a+.hypershell.v1.CreateManagedClusterResponse\x12o\n" +
	"\x14UpdateManagedCluster\x12*.hypershell.v1.UpdateManagedClusterRequest\x1a+.hypershell.v1.UpdateManagedClusterResponse\x12o\n" +
	"\x14DeleteManagedCluster\x12*.hypershell.v1.DeleteManagedClusterRequest\x1a+.hypershell.v1.DeleteManagedClusterResponse\x12l\n" +
	"\x13ListManagedClusters\x12).hypershell.v1.ListManagedClustersRequest\x1a*.hypershell.v1.ListManagedClustersResponse\x12q\n" +
	"\x14WatchManagedClusters\x12*.hypershell.v1.WatchManagedClustersRequest\x1a+.hypershell.v1.WatchManagedClustersResponse0\x01BgZegithub.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1b\x06proto3"

var (
	file_hypershell_v1_managed_clusters_proto_rawDescOnce sync.Once
	file_hypershell_v1_managed_clusters_proto_rawDescData []byte
)

func file_hypershell_v1_managed_clusters_proto_rawDescGZIP() []byte {
	file_hypershell_v1_managed_clusters_proto_rawDescOnce.Do(func() {
		file_hypershell_v1_managed_clusters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypershell_v1_managed_clusters_proto_rawDesc), len(file_hypershell_v1_managed_clusters_proto_rawDesc)))
	})
	return file_hypershell_v1_managed_clusters_proto_rawDescData
}

var file_hypershell_v1_managed_clusters_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_hypershell_v1_managed_clusters_proto_goTypes = []any{
	(*ManagedCluster)(nil),               // 0: hypershell.v1.ManagedCluster
	(*CreateManagedClusterRequest)(nil),  // 1: hypershell.v1.CreateManagedClusterRequest
	(*CreateManagedClusterResponse)(nil), // 2: hypershell.v1.CreateManagedClusterResponse
	(*GetManagedClusterRequest)(nil),     // 3: hypershell.v1.GetManagedClusterRequest
	(*GetManagedClusterResponse)(nil),    // 4: hypershell.v1.GetManagedClusterResponse
	(*UpdateManagedClusterRequest)(nil),  // 5: hypershell.v1.UpdateManagedClusterRequest
	(*UpdateManagedClusterResponse)(nil), // 6: hypershell.v1.UpdateManagedClusterResponse
	(*DeleteManagedClusterRequest)(nil),  // 7: hypershell.v1.DeleteManagedClusterRequest
	(*ListManagedClustersRequest)(nil),   // 8: hypershell.v1.ListManagedClustersRequest
	(*ListManagedClustersResponse)(nil),  // 9: hypershell.v1.ListManagedClustersResponse
	(*DeleteManagedClusterResponse)(nil), // 10: hypershell.v1.DeleteManagedClusterResponse
	(*WatchManagedClustersRequest)(nil),  // 11: hypershell.v1.WatchManagedClustersRequest
	(*WatchManagedClustersResponse)(nil), // 12: hypershell.v1.WatchManagedClustersResponse
	(*ObjectReference)(nil),              // 13: hypershell.v1.ObjectReference
	(*ListMeta)(nil),                     // 14: hypershell.v1.ListMeta
	(EventType)(0),                       // 15: hypershell.v1.EventType
}
var file_hypershell_v1_managed_clusters_proto_depIdxs = []int32{
	13, // 0: hypershell.v1.ManagedCluster.metadata:type_name -> hypershell.v1.ObjectReference
	0,  // 1: hypershell.v1.CreateManagedClusterResponse.managed_cluster:type_name -> hypershell.v1.ManagedCluster
	0,  // 2: hypershell.v1.GetManagedClusterResponse.managed_cluster:type_name -> hypershell.v1.ManagedCluster
	0,  // 3: hypershell.v1.UpdateManagedClusterResponse.managed_cluster:type_name -> hypershell.v1.ManagedCluster
	0,  // 4: hypershell.v1.ListManagedClustersResponse.items:type_name -> hypershell.v1.ManagedCluster
	14, // 5: hypershell.v1.ListManagedClustersResponse.metadata:type_name -> hypershell.v1.ListMeta
	15, // 6: hypershell.v1.WatchManagedClustersResponse.type:type_name -> hypershell.v1.EventType
	0,  // 7: hypershell.v1.WatchManagedClustersResponse.managed_cluster:type_name -> hypershell.v1.ManagedCluster
	3,  // 8: hypershell.v1.ManagedClusterService.GetManagedCluster:input_type -> hypershell.v1.GetManagedClusterRequest
	1,  // 9: hypershell.v1.ManagedClusterService.CreateManagedCluster:input_type -> hypershell.v1.CreateManagedClusterRequest
	5,  // 10: hypershell.v1.ManagedClusterService.UpdateManagedCluster:input_type -> hypershell.v1.UpdateManagedClusterRequest
	7,  // 11: hypershell.v1.ManagedClusterService.DeleteManagedCluster:input_type -> hypershell.v1.DeleteManagedClusterRequest
	8,  // 12: hypershell.v1.ManagedClusterService.ListManagedClusters:input_type -> hypershell.v1.ListManagedClustersRequest
	11, // 13: hypershell.v1.ManagedClusterService.WatchManagedClusters:input_type -> hypershell.v1.WatchManagedClustersRequest
	4,  // 14: hypershell.v1.ManagedClusterService.GetManagedCluster:output_type -> hypershell.v1.GetManagedClusterResponse
	2,  // 15: hypershell.v1.ManagedClusterService.CreateManagedCluster:output_type -> hypershell.v1.CreateManagedClusterResponse
	6,  // 16: hypershell.v1.ManagedClusterService.UpdateManagedCluster:output_type -> hypershell.v1.UpdateManagedClusterResponse
	10, // 17: hypershell.v1.ManagedClusterService.DeleteManagedCluster:output_type -> hypershell.v1.DeleteManagedClusterResponse
	9,  // 18: hypershell.v1.ManagedClusterService.ListManagedClusters:output_type -> hypershell.v1.ListManagedClustersResponse
	12, // 19: hypershell.v1.ManagedClusterService.WatchManagedClusters:output_type -> hypershell.v1.WatchManagedClustersResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hypershell_v1_managed_clusters_proto_init() }
func file_hypershell_v1_managed_clusters_proto_init() {
	if File_hypershell_v1_managed_clusters_proto != nil {
		return
	}
	file_hypershell_v1_common_proto_init()
	file_hypershell_v1_managed_clusters_proto_msgTypes[0].OneofWrappers = []any{}
	file_hypershell_v1_managed_clusters_proto_msgTypes[1].OneofWrappers = []any{}
	file_hypershell_v1_managed_clusters_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypershell_v1_managed_clusters_proto_rawDesc), len(file_hypershell_v1_managed_clusters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypershell_v1_managed_clusters_proto_goTypes,
		DependencyIndexes: file_hypershell_v1_managed_clusters_proto_depIdxs,
		MessageInfos:      file_hypershell_v1_managed_clusters_proto_msgTypes,
	}.Build()
	File_hypershell_v1_managed_clusters_proto = out.File
	file_hypershell_v1_managed_clusters_proto_goTypes = nil
	file_hypershell_v1_managed_clusters_proto_depIdxs = nil
}
