// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/managed_clusters.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagedClusterService_GetManagedCluster_FullMethodName    = "/hypershell.v1.ManagedClusterService/GetManagedCluster"
	ManagedClusterService_CreateManagedCluster_FullMethodName = "/hypershell.v1.ManagedClusterService/CreateManagedCluster"
	ManagedClusterService_UpdateManagedCluster_FullMethodName = "/hypershell.v1.ManagedClusterService/UpdateManagedCluster"
	ManagedClusterService_DeleteManagedCluster_FullMethodName = "/hypershell.v1.ManagedClusterService/DeleteManagedCluster"
	ManagedClusterService_ListManagedClusters_FullMethodName  = "/hypershell.v1.ManagedClusterService/ListManagedClusters"
	ManagedClusterService_WatchManagedClusters_FullMethodName = "/hypershell.v1.ManagedClusterService/WatchManagedClusters"
)

// ManagedClusterServiceClient is the client API for ManagedClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagedClusterServiceClient interface {
	GetManagedCluster(ctx context.Context, in *GetManagedClusterRequest, opts ...grpc.CallOption) (*GetManagedClusterResponse, error)
	CreateManagedCluster(ctx context.Context, in *CreateManagedClusterRequest, opts ...grpc.CallOption) (*CreateManagedClusterResponse, error)
	UpdateManagedCluster(ctx context.Context, in *UpdateManagedClusterRequest, opts ...grpc.CallOption) (*UpdateManagedClusterResponse, error)
	DeleteManagedCluster(ctx context.Context, in *DeleteManagedClusterRequest, opts ...grpc.CallOption) (*DeleteManagedClusterResponse, error)
	ListManagedClusters(ctx context.Context, in *ListManagedClustersRequest, opts ...grpc.CallOption) (*ListManagedClustersResponse, error)
	WatchManagedClusters(ctx context.Context, in *WatchManagedClustersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchManagedClustersResponse], error)
}

type managedClusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagedClusterServiceClient(cc grpc.ClientConnInterface) ManagedClusterServiceClient {
	return &managedClusterServiceClient{cc}
}

func (c *managedClusterServiceClient) GetManagedCluster(ctx context.Context, in *GetManagedClusterRequest, opts ...grpc.CallOption) (*GetManagedClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagedClusterResponse)
	err := c.cc.Invoke(ctx, ManagedClusterService_GetManagedCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedClusterServiceClient) CreateManagedCluster(ctx context.Context, in *CreateManagedClusterRequest, opts ...grpc.CallOption) (*CreateManagedClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateManagedClusterResponse)
	err := c.cc.Invoke(ctx, ManagedClusterService_CreateManagedCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedClusterServiceClient) UpdateManagedCluster(ctx context.Context, in *UpdateManagedClusterRequest, opts ...grpc.CallOption) (*UpdateManagedClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManagedClusterResponse)
	err := c.cc.Invoke(ctx, ManagedClusterService_UpdateManagedCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedClusterServiceClient) DeleteManagedCluster(ctx context.Context, in *DeleteManagedClusterRequest, opts ...grpc.CallOption) (*DeleteManagedClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManagedClusterResponse)
	err := c.cc.Invoke(ctx, ManagedClusterService_DeleteManagedCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedClusterServiceClient) ListManagedClusters(ctx context.Context, in *ListManagedClustersRequest, opts ...grpc.CallOption) (*ListManagedClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedClustersResponse)
	err := c.cc.Invoke(ctx, ManagedClusterService_ListManagedClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedClusterServiceClient) WatchManagedClusters(ctx context.Context, in *WatchManagedClustersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchManagedClustersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagedClusterService_ServiceDesc.Streams[0], ManagedClusterService_WatchManagedClusters_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchManagedClustersRequest, WatchManagedClustersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagedClusterService_WatchManagedClustersClient = grpc.ServerStreamingClient[WatchManagedClustersResponse]

// ManagedClusterServiceServer is the server API for ManagedClusterService service.
// All implementations must embed UnimplementedManagedClusterServiceServer
// for forward compatibility.
type ManagedClusterServiceServer interface {
	GetManagedCluster(context.Context, *GetManagedClusterRequest) (*GetManagedClusterResponse, error)
	CreateManagedCluster(context.Context, *CreateManagedClusterRequest) (*CreateManagedClusterResponse, error)
	UpdateManagedCluster(context.Context, *UpdateManagedClusterRequest) (*UpdateManagedClusterResponse, error)
	DeleteManagedCluster(context.Context, *DeleteManagedClusterRequest) (*DeleteManagedClusterResponse, error)
	ListManagedClusters(context.Context, *ListManagedClustersRequest) (*ListManagedClustersResponse, error)
	WatchManagedClusters(*WatchManagedClustersRequest, grpc.ServerStreamingServer[WatchManagedClustersResponse]) error
	mustEmbedUnimplementedManagedClusterServiceServer()
}

// UnimplementedManagedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagedClusterServiceServer struct{}

func (UnimplementedManagedClusterServiceServer) GetManagedCluster(context.Context, *GetManagedClusterRequest) (*GetManagedClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManagedCluster not implemented")
}
func (UnimplementedManagedClusterServiceServer) CreateManagedCluster(context.Context, *CreateManagedClusterRequest) (*CreateManagedClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManagedCluster not implemented")
}
func (UnimplementedManagedClusterServiceServer) UpdateManagedCluster(context.Context, *UpdateManagedClusterRequest) (*UpdateManagedClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManagedCluster not implemented")
}
func (UnimplementedManagedClusterServiceServer) DeleteManagedCluster(context.Context, *DeleteManagedClusterRequest) (*DeleteManagedClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManagedCluster not implemented")
}
func (UnimplementedManagedClusterServiceServer) ListManagedClusters(context.Context, *ListManagedClustersRequest) (*ListManagedClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagedClusters not implemented")
}
func (UnimplementedManagedClusterServiceServer) WatchManagedClusters(*WatchManagedClustersRequest, grpc.ServerStreamingServer[WatchManagedClustersResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchManagedClusters not implemented")
}
func (UnimplementedManagedClusterServiceServer) mustEmbedUnimplementedManagedClusterServiceServer() {}
func (UnimplementedManagedClusterServiceServer) testEmbeddedByValue()                               {}

// UnsafeManagedClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagedClusterServiceServer will
// result in compilation errors.
type UnsafeManagedClusterServiceServer interface {
	mustEmbedUnimplementedManagedClusterServiceServer()
}

func RegisterManagedClusterServiceServer(s grpc.ServiceRegistrar, srv ManagedClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedManagedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagedClusterService_ServiceDesc, srv)
}

func _ManagedClusterService_GetManagedCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagedClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedClusterServiceServer).GetManagedCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedClusterService_GetManagedCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedClusterServiceServer).GetManagedCluster(ctx, req.(*GetManagedClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedClusterService_CreateManagedCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagedClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedClusterServiceServer).CreateManagedCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedClusterService_CreateManagedCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedClusterServiceServer).CreateManagedCluster(ctx, req.(*CreateManagedClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedClusterService_UpdateManagedCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManagedClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedClusterServiceServer).UpdateManagedCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedClusterService_UpdateManagedCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedClusterServiceServer).UpdateManagedCluster(ctx, req.(*UpdateManagedClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedClusterService_DeleteManagedCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManagedClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedClusterServiceServer).DeleteManagedCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedClusterService_DeleteManagedCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedClusterServiceServer).DeleteManagedCluster(ctx, req.(*DeleteManagedClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedClusterService_ListManagedClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedClusterServiceServer).ListManagedClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedClusterService_ListManagedClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedClusterServiceServer).ListManagedClusters(ctx, req.(*ListManagedClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedClusterService_WatchManagedClusters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchManagedClustersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagedClusterServiceServer).WatchManagedClusters(m, &grpc.GenericServerStream[WatchManagedClustersRequest, WatchManagedClustersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagedClusterService_WatchManagedClustersServer = grpc.ServerStreamingServer[WatchManagedClustersResponse]

// ManagedClusterService_ServiceDesc is the grpc.ServiceDesc for ManagedClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagedClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.ManagedClusterService",
	HandlerType: (*ManagedClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManagedCluster",
			Handler:    _ManagedClusterService_GetManagedCluster_Handler,
		},
		{
			MethodName: "CreateManagedCluster",
			Handler:    _ManagedClusterService_CreateManagedCluster_Handler,
		},
		{
			MethodName: "UpdateManagedCluster",
			Handler:    _ManagedClusterService_UpdateManagedCluster_Handler,
		},
		{
			MethodName: "DeleteManagedCluster",
			Handler:    _ManagedClusterService_DeleteManagedCluster_Handler,
		},
		{
			MethodName: "ListManagedClusters",
			Handler:    _ManagedClusterService_ListManagedClusters_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchManagedClusters",
			Handler:       _ManagedClusterService_WatchManagedClusters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypershell/v1/managed_clusters.proto",
}
