// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hypershell/v1/managed_databases.proto

package hypershell_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagedDatabaseService_GetManagedDatabase_FullMethodName    = "/hypershell.v1.ManagedDatabaseService/GetManagedDatabase"
	ManagedDatabaseService_CreateManagedDatabase_FullMethodName = "/hypershell.v1.ManagedDatabaseService/CreateManagedDatabase"
	ManagedDatabaseService_UpdateManagedDatabase_FullMethodName = "/hypershell.v1.ManagedDatabaseService/UpdateManagedDatabase"
	ManagedDatabaseService_DeleteManagedDatabase_FullMethodName = "/hypershell.v1.ManagedDatabaseService/DeleteManagedDatabase"
	ManagedDatabaseService_ListManagedDatabases_FullMethodName  = "/hypershell.v1.ManagedDatabaseService/ListManagedDatabases"
	ManagedDatabaseService_WatchManagedDatabases_FullMethodName = "/hypershell.v1.ManagedDatabaseService/WatchManagedDatabases"
)

// ManagedDatabaseServiceClient is the client API for ManagedDatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagedDatabaseServiceClient interface {
	GetManagedDatabase(ctx context.Context, in *GetManagedDatabaseRequest, opts ...grpc.CallOption) (*GetManagedDatabaseResponse, error)
	CreateManagedDatabase(ctx context.Context, in *CreateManagedDatabaseRequest, opts ...grpc.CallOption) (*CreateManagedDatabaseResponse, error)
	UpdateManagedDatabase(ctx context.Context, in *UpdateManagedDatabaseRequest, opts ...grpc.CallOption) (*UpdateManagedDatabaseResponse, error)
	DeleteManagedDatabase(ctx context.Context, in *DeleteManagedDatabaseRequest, opts ...grpc.CallOption) (*DeleteManagedDatabaseResponse, error)
	ListManagedDatabases(ctx context.Context, in *ListManagedDatabasesRequest, opts ...grpc.CallOption) (*ListManagedDatabasesResponse, error)
	WatchManagedDatabases(ctx context.Context, in *WatchManagedDatabasesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchManagedDatabasesResponse], error)
}

type managedDatabaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagedDatabaseServiceClient(cc grpc.ClientConnInterface) ManagedDatabaseServiceClient {
	return &managedDatabaseServiceClient{cc}
}

func (c *managedDatabaseServiceClient) GetManagedDatabase(ctx context.Context, in *GetManagedDatabaseRequest, opts ...grpc.CallOption) (*GetManagedDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagedDatabaseResponse)
	err := c.cc.Invoke(ctx, ManagedDatabaseService_GetManagedDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedDatabaseServiceClient) CreateManagedDatabase(ctx context.Context, in *CreateManagedDatabaseRequest, opts ...grpc.CallOption) (*CreateManagedDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateManagedDatabaseResponse)
	err := c.cc.Invoke(ctx, ManagedDatabaseService_CreateManagedDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedDatabaseServiceClient) UpdateManagedDatabase(ctx context.Context, in *UpdateManagedDatabaseRequest, opts ...grpc.CallOption) (*UpdateManagedDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManagedDatabaseResponse)
	err := c.cc.Invoke(ctx, ManagedDatabaseService_UpdateManagedDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedDatabaseServiceClient) DeleteManagedDatabase(ctx context.Context, in *DeleteManagedDatabaseRequest, opts ...grpc.CallOption) (*DeleteManagedDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManagedDatabaseResponse)
	err := c.cc.Invoke(ctx, ManagedDatabaseService_DeleteManagedDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedDatabaseServiceClient) ListManagedDatabases(ctx context.Context, in *ListManagedDatabasesRequest, opts ...grpc.CallOption) (*ListManagedDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedDatabasesResponse)
	err := c.cc.Invoke(ctx, ManagedDatabaseService_ListManagedDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managedDatabaseServiceClient) WatchManagedDatabases(ctx context.Context, in *WatchManagedDatabasesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchManagedDatabasesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagedDatabaseService_ServiceDesc.Streams[0], ManagedDatabaseService_WatchManagedDatabases_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchManagedDatabasesRequest, WatchManagedDatabasesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagedDatabaseService_WatchManagedDatabasesClient = grpc.ServerStreamingClient[WatchManagedDatabasesResponse]

// ManagedDatabaseServiceServer is the server API for ManagedDatabaseService service.
// All implementations must embed UnimplementedManagedDatabaseServiceServer
// for forward compatibility.
type ManagedDatabaseServiceServer interface {
	GetManagedDatabase(context.Context, *GetManagedDatabaseRequest) (*GetManagedDatabaseResponse, error)
	CreateManagedDatabase(context.Context, *CreateManagedDatabaseRequest) (*CreateManagedDatabaseResponse, error)
	UpdateManagedDatabase(context.Context, *UpdateManagedDatabaseRequest) (*UpdateManagedDatabaseResponse, error)
	DeleteManagedDatabase(context.Context, *DeleteManagedDatabaseRequest) (*DeleteManagedDatabaseResponse, error)
	ListManagedDatabases(context.Context, *ListManagedDatabasesRequest) (*ListManagedDatabasesResponse, error)
	WatchManagedDatabases(*WatchManagedDatabasesRequest, grpc.ServerStreamingServer[WatchManagedDatabasesResponse]) error
	mustEmbedUnimplementedManagedDatabaseServiceServer()
}

// UnimplementedManagedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagedDatabaseServiceServer struct{}

func (UnimplementedManagedDatabaseServiceServer) GetManagedDatabase(context.Context, *GetManagedDatabaseRequest) (*GetManagedDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManagedDatabase not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) CreateManagedDatabase(context.Context, *CreateManagedDatabaseRequest) (*CreateManagedDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManagedDatabase not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) UpdateManagedDatabase(context.Context, *UpdateManagedDatabaseRequest) (*UpdateManagedDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManagedDatabase not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) DeleteManagedDatabase(context.Context, *DeleteManagedDatabaseRequest) (*DeleteManagedDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManagedDatabase not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) ListManagedDatabases(context.Context, *ListManagedDatabasesRequest) (*ListManagedDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagedDatabases not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) WatchManagedDatabases(*WatchManagedDatabasesRequest, grpc.ServerStreamingServer[WatchManagedDatabasesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchManagedDatabases not implemented")
}
func (UnimplementedManagedDatabaseServiceServer) mustEmbedUnimplementedManagedDatabaseServiceServer() {
}
func (UnimplementedManagedDatabaseServiceServer) testEmbeddedByValue() {}

// UnsafeManagedDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagedDatabaseServiceServer will
// result in compilation errors.
type UnsafeManagedDatabaseServiceServer interface {
	mustEmbedUnimplementedManagedDatabaseServiceServer()
}

func RegisterManagedDatabaseServiceServer(s grpc.ServiceRegistrar, srv ManagedDatabaseServiceServer) {
	// If the following call panics, it indicates UnimplementedManagedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagedDatabaseService_ServiceDesc, srv)
}

func _ManagedDatabaseService_GetManagedDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagedDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedDatabaseServiceServer).GetManagedDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedDatabaseService_GetManagedDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedDatabaseServiceServer).GetManagedDatabase(ctx, req.(*GetManagedDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedDatabaseService_CreateManagedDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagedDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedDatabaseServiceServer).CreateManagedDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedDatabaseService_CreateManagedDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedDatabaseServiceServer).CreateManagedDatabase(ctx, req.(*CreateManagedDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedDatabaseService_UpdateManagedDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManagedDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedDatabaseServiceServer).UpdateManagedDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedDatabaseService_UpdateManagedDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedDatabaseServiceServer).UpdateManagedDatabase(ctx, req.(*UpdateManagedDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedDatabaseService_DeleteManagedDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManagedDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedDatabaseServiceServer).DeleteManagedDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedDatabaseService_DeleteManagedDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedDatabaseServiceServer).DeleteManagedDatabase(ctx, req.(*DeleteManagedDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedDatabaseService_ListManagedDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagedDatabaseServiceServer).ListManagedDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagedDatabaseService_ListManagedDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagedDatabaseServiceServer).ListManagedDatabases(ctx, req.(*ListManagedDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagedDatabaseService_WatchManagedDatabases_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchManagedDatabasesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagedDatabaseServiceServer).WatchManagedDatabases(m, &grpc.GenericServerStream[WatchManagedDatabasesRequest, WatchManagedDatabasesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagedDatabaseService_WatchManagedDatabasesServer = grpc.ServerStreamingServer[WatchManagedDatabasesResponse]

// ManagedDatabaseService_ServiceDesc is the grpc.ServiceDesc for ManagedDatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagedDatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypershell.v1.ManagedDatabaseService",
	HandlerType: (*ManagedDatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManagedDatabase",
			Handler:    _ManagedDatabaseService_GetManagedDatabase_Handler,
		},
		{
			MethodName: "CreateManagedDatabase",
			Handler:    _ManagedDatabaseService_CreateManagedDatabase_Handler,
		},
		{
			MethodName: "UpdateManagedDatabase",
			Handler:    _ManagedDatabaseService_UpdateManagedDatabase_Handler,
		},
		{
			MethodName: "DeleteManagedDatabase",
			Handler:    _ManagedDatabaseService_DeleteManagedDatabase_Handler,
		},
		{
			MethodName: "ListManagedDatabases",
			Handler:    _ManagedDatabaseService_ListManagedDatabases_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchManagedDatabases",
			Handler:       _ManagedDatabaseService_WatchManagedDatabases_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypershell/v1/managed_databases.proto",
}
