// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hypershell/v1/role_bindings.proto

package hypershell_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	UserId        *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	GatewayId     *string                `protobuf:"bytes,5,opt,name=gateway_id,json=gatewayId,proto3,oneof" json:"gateway_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_role_bindings_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBinding) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoleBinding) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleBinding) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RoleBinding) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *RoleBinding) GetGatewayId() string {
	if x != nil && x.GatewayId != nil {
		return *x.GatewayId
	}
	return ""
}

func (x *RoleBinding) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleBinding) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type WatchRoleBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoleBindingsRequest) Reset() {
	*x = WatchRoleBindingsRequest{}
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoleBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoleBindingsRequest) ProtoMessage() {}

func (x *WatchRoleBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoleBindingsRequest.ProtoReflect.Descriptor instead.
func (*WatchRoleBindingsRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_role_bindings_proto_rawDescGZIP(), []int{1}
}

type WatchRoleBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=hypershell.v1.EventType" json:"type,omitempty"`
	RoleBinding   *RoleBinding           `protobuf:"bytes,2,opt,name=role_binding,json=roleBinding,proto3" json:"role_binding,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoleBindingsResponse) Reset() {
	*x = WatchRoleBindingsResponse{}
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoleBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoleBindingsResponse) ProtoMessage() {}

func (x *WatchRoleBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoleBindingsResponse.ProtoReflect.Descriptor instead.
func (*WatchRoleBindingsResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_role_bindings_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRoleBindingsResponse) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchRoleBindingsResponse) GetRoleBinding() *RoleBinding {
	if x != nil {
		return x.RoleBinding
	}
	return nil
}

func (x *WatchRoleBindingsResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListRoleBindingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters to the active role bindings for this user. Required: the control
	// plane uses this to recompute a user's effective Keycloak roles on a gateway.
	UserId *string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	// Optional additional filter to a single gateway.
	GatewayId     *string `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3,oneof" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleBindingsRequest) Reset() {
	*x = ListRoleBindingsRequest{}
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleBindingsRequest) ProtoMessage() {}

func (x *ListRoleBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListRoleBindingsRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_role_bindings_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoleBindingsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListRoleBindingsRequest) GetGatewayId() string {
	if x != nil && x.GatewayId != nil {
		return *x.GatewayId
	}
	return ""
}

type ListRoleBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RoleBinding         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleBindingsResponse) Reset() {
	*x = ListRoleBindingsResponse{}
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleBindingsResponse) ProtoMessage() {}

func (x *ListRoleBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_role_bindings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListRoleBindingsResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_role_bindings_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoleBindingsResponse) GetItems() []*RoleBinding {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_hypershell_v1_role_bindings_proto protoreflect.FileDescriptor

const file_hypershell_v1_role_bindings_proto_rawDesc = "" +
	"\n" +
	"!hypershell/v1/role_bindings.proto\x12\rhypershell.v1\x1a\x1ahypershell/v1/common.proto\"\x8e\x02\n" +
	"\vRoleBinding\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.hypershell.v1.ObjectReferenceR\bmetadata\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"gateway_id\x18\x05 \x01(\tH\x01R\tgatewayId\x88\x01\x01\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busernameB\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_gateway_id\"\x1a\n" +
	"\x18WatchRoleBindingsRequest\"\xa9\x01\n" +
	"\x19WatchRoleBindingsResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.hypershell.v1.EventTypeR\x04type\x12=\n" +
	"\frole_binding\x18\x02 \x01(\v2\x1a.hypershell.v1.RoleBindingR\vroleBinding\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"v\n" +
	"\x17ListRoleBindingsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tH\x01R\tgatewayId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_gateway_id\"L\n" +
	"\x18ListRoleBindingsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.hypershell.v1.RoleBindingR\x05items2\xe3\x01\n" +
	"\x12RoleBindingService\x12h\n" +
	"\x11WatchRoleBindings\x12'.hypershell.v1.WatchRoleBindingsRequest\x1a(.hypershell.v1.WatchRoleBindingsResponse0\x01\x12c\n" +
	"\x10ListRoleBindings\x12&.hypershell.v1.ListRoleBindingsRequest\x1a'.hypershell.v1.ListRoleBindingsResponseBgZegithub.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1b\x06proto3"

var (
	file_hypershell_v1_role_bindings_proto_rawDescOnce sync.Once
	file_hypershell_v1_role_bindings_proto_rawDescData []byte
)

func file_hypershell_v1_role_bindings_proto_rawDescGZIP() []byte {
	file_hypershell_v1_role_bindings_proto_rawDescOnce.Do(func() {
		file_hypershell_v1_role_bindings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypershell_v1_role_bindings_proto_rawDesc), len(file_hypershell_v1_role_bindings_proto_rawDesc)))
	})
	return file_hypershell_v1_role_bindings_proto_rawDescData
}

var file_hypershell_v1_role_bindings_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hypershell_v1_role_bindings_proto_goTypes = []any{
	(*RoleBinding)(nil),               // 0: hypershell.v1.RoleBinding
	(*WatchRoleBindingsRequest)(nil),  // 1: hypershell.v1.WatchRoleBindingsRequest
	(*WatchRoleBindingsResponse)(nil), // 2: hypershell.v1.WatchRoleBindingsResponse
	(*ListRoleBindingsRequest)(nil),   // 3: hypershell.v1.ListRoleBindingsRequest
	(*ListRoleBindingsResponse)(nil),  // 4: hypershell.v1.ListRoleBindingsResponse
	(*ObjectReference)(nil),           // 5: hypershell.v1.ObjectReference
	(EventType)(0),                    // 6: hypershell.v1.EventType
}
var file_hypershell_v1_role_bindings_proto_depIdxs = []int32{
	5, // 0: hypershell.v1.RoleBinding.metadata:type_name -> hypershell.v1.ObjectReference
	6, // 1: hypershell.v1.WatchRoleBindingsResponse.type:type_name -> hypershell.v1.EventType
	0, // 2: hypershell.v1.WatchRoleBindingsResponse.role_binding:type_name -> hypershell.v1.RoleBinding
	0, // 3: hypershell.v1.ListRoleBindingsResponse.items:type_name -> hypershell.v1.RoleBinding
	1, // 4: hypershell.v1.RoleBindingService.WatchRoleBindings:input_type -> hypershell.v1.WatchRoleBindingsRequest
	3, // 5: hypershell.v1.RoleBindingService.ListRoleBindings:input_type -> hypershell.v1.ListRoleBindingsRequest
	2, // 6: hypershell.v1.RoleBindingService.WatchRoleBindings:output_type -> hypershell.v1.WatchRoleBindingsResponse
	4, // 7: hypershell.v1.RoleBindingService.ListRoleBindings:output_type -> hypershell.v1.ListRoleBindingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hypershell_v1_role_bindings_proto_init() }
func file_hypershell_v1_role_bindings_proto_init() {
	if File_hypershell_v1_role_bindings_proto != nil {
		return
	}
	file_hypershell_v1_common_proto_init()
	file_hypershell_v1_role_bindings_proto_msgTypes[0].OneofWrappers = []any{}
	file_hypershell_v1_role_bindings_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypershell_v1_role_bindings_proto_rawDesc), len(file_hypershell_v1_role_bindings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypershell_v1_role_bindings_proto_goTypes,
		DependencyIndexes: file_hypershell_v1_role_bindings_proto_depIdxs,
		MessageInfos:      file_hypershell_v1_role_bindings_proto_msgTypes,
	}.Build()
	File_hypershell_v1_role_bindings_proto = out.File
	file_hypershell_v1_role_bindings_proto_goTypes = nil
	file_hypershell_v1_role_bindings_proto_depIdxs = nil
}
