{
 "title": "HyperShell Metrics",
 "tags": [ "hypershell" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running Gateways",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hypershell_gateways_total{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Running Gateways Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (phase) (hypershell_gateways_total)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Running Pods (hypershell-*)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"hypershell-.*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Running Pods Over Time (hypershell-*)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_phase{namespace=~\"hypershell-.*\", phase=\"Running\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}