apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypershell-api-server
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: password
      containers:
        - name: api-server
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypershell-controller
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hypershell-db-app
                  key: password
