apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hypershell-web-console-oidc
  labels:
    app.kubernetes.io/name: hypershell
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-cluster-store
  target:
    name: hypershell-web-console-oidc
    creationPolicy: Owner
  data:
  - secretKey: SESSION_SECRET
    remoteRef:
      key: hypershell/shared
      property: SESSION_SECRET
