apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../hub
  - servicemonitor.yaml
  - external-secrets.yaml
  - network-policies.yaml
  - allow-controller-to-api.yaml
  - allow-console-to-api.yaml

configurations:
  - name-references.yaml

patches:
  - target:
      kind: Deployment
      name: hypershell-api-server
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hypershell-api-server
        annotations:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Deployment
      name: hypershell-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hypershell-controller
        annotations:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Deployment
      name: hypershell-web-console
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hypershell-web-console
        annotations:
          argocd.argoproj.io/sync-wave: "1"
