// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: e8f024e88b195e2a32ea7e42534fc438e250c5f4b9f11e7ea9c9e802488c74c8

package types

import "time"

type GatewayAccessCapabilities struct {
	CallerRole      GatewayAccessRole `json:"caller_role,omitempty"`
	CanManageAccess bool              `json:"can_manage_access"`
	CanManageOwners bool              `json:"can_manage_owners"`
}

type GatewayAccessChangeRoleRequest struct {
	Role GatewayAccessRole `json:"role"`
}

type GatewayAccessGrantRequest struct {
	Role     GatewayAccessRole `json:"role"`
	Subject  string            `json:"subject,omitempty"`
	Username string            `json:"username"`
}

type GatewayAccessGrantResponse struct {
	Email         *string           `json:"email,omitempty"`
	GrantedAt     time.Time         `json:"granted_at"`
	IsCreator     bool              `json:"is_creator"`
	Name          *string           `json:"name,omitempty"`
	Role          GatewayAccessRole `json:"role"`
	RoleBindingID string            `json:"role_binding_id"`
	UserID        string            `json:"user_id"`
	Username      string            `json:"username"`
}

type GatewayAccessList struct {
	Capabilities GatewayAccessCapabilities `json:"capabilities"`
	Items        []GatewayAccessListItem   `json:"items"`
	Page         int                       `json:"page"`
	Size         int                       `json:"size"`
	Total        int                       `json:"total"`
}

type GatewayAccessListItem struct {
	Email         *string           `json:"email,omitempty"`
	GrantedAt     time.Time         `json:"granted_at"`
	IsCreator     bool              `json:"is_creator"`
	Name          *string           `json:"name,omitempty"`
	Role          GatewayAccessRole `json:"role"`
	RoleBindingID string            `json:"role_binding_id"`
	UserID        string            `json:"user_id"`
	Username      string            `json:"username"`
}

type GatewayAccessRole string

const (
	GatewayAccessRoleOwner GatewayAccessRole = "owner"
	GatewayAccessRoleAdmin GatewayAccessRole = "admin"
	GatewayAccessRoleUser  GatewayAccessRole = "user"
)

type GatewayDirectoryUser struct {
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Subject  *string `json:"subject,omitempty"`
	Username string  `json:"username"`
}

type GatewayDirectoryUserList struct {
	Items []GatewayDirectoryUser `json:"items"`
}

func (l *GatewayAccessList) GetItems() []GatewayAccessListItem { return l.Items }
func (l *GatewayAccessList) GetTotal() int                     { return l.Total }
func (l *GatewayAccessList) GetPage() int                      { return l.Page }
func (l *GatewayAccessList) GetSize() int                      { return l.Size }

type GatewayAccessListOptions struct {
	Page   int
	Size   int
	Role   GatewayAccessRole
	Search string
	Sort   string
	Order  string
}

type GatewayAccessListOptionsBuilder struct {
	opts GatewayAccessListOptions
}

func NewGatewayAccessListOptions() *GatewayAccessListOptionsBuilder {
	return &GatewayAccessListOptionsBuilder{opts: GatewayAccessListOptions{Page: 1, Size: 20}}
}

func (b *GatewayAccessListOptionsBuilder) Page(value int) *GatewayAccessListOptionsBuilder {
	b.opts.Page = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Size(value int) *GatewayAccessListOptionsBuilder {
	if value > 100 {
		value = 100
	}
	b.opts.Size = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Role(value GatewayAccessRole) *GatewayAccessListOptionsBuilder {
	b.opts.Role = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Search(value string) *GatewayAccessListOptionsBuilder {
	b.opts.Search = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Sort(value string) *GatewayAccessListOptionsBuilder {
	b.opts.Sort = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Order(value string) *GatewayAccessListOptionsBuilder {
	b.opts.Order = value
	return b
}

func (b *GatewayAccessListOptionsBuilder) Build() *GatewayAccessListOptions {
	return &b.opts
}
