// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: e8f024e88b195e2a32ea7e42534fc438e250c5f4b9f11e7ea9c9e802488c74c8

package types

import (
	"errors"
	"fmt"
)

type InferenceRoute struct {
	ObjectReference

	Model             string `json:"model"`
	ProviderBindingID string `json:"provider_binding_id"`
	WorkspaceID       string `json:"workspace_id"`
}

type InferenceRouteList struct {
	ListMeta
	Items []InferenceRoute `json:"items"`
}

func (l *InferenceRouteList) GetItems() []InferenceRoute { return l.Items }
func (l *InferenceRouteList) GetTotal() int              { return l.Total }
func (l *InferenceRouteList) GetPage() int               { return l.Page }
func (l *InferenceRouteList) GetSize() int               { return l.Size }

type InferenceRouteBuilder struct {
	resource InferenceRoute
	errors   []error
}

func NewInferenceRouteBuilder() *InferenceRouteBuilder {
	return &InferenceRouteBuilder{}
}

func (b *InferenceRouteBuilder) Model(v string) *InferenceRouteBuilder {
	b.resource.Model = v
	return b
}

func (b *InferenceRouteBuilder) ProviderBindingID(v string) *InferenceRouteBuilder {
	b.resource.ProviderBindingID = v
	return b
}

func (b *InferenceRouteBuilder) WorkspaceID(v string) *InferenceRouteBuilder {
	b.resource.WorkspaceID = v
	return b
}

func (b *InferenceRouteBuilder) Build() (*InferenceRoute, error) {
	if b.resource.Model == "" {
		b.errors = append(b.errors, fmt.Errorf("model is required"))
	}
	if b.resource.ProviderBindingID == "" {
		b.errors = append(b.errors, fmt.Errorf("provider_binding_id is required"))
	}
	if b.resource.WorkspaceID == "" {
		b.errors = append(b.errors, fmt.Errorf("workspace_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type InferenceRoutePatchBuilder struct {
	patch map[string]any
}

func NewInferenceRoutePatchBuilder() *InferenceRoutePatchBuilder {
	return &InferenceRoutePatchBuilder{patch: make(map[string]any)}
}

func (b *InferenceRoutePatchBuilder) Build() map[string]any {
	return b.patch
}
