// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/openshift-online/hypershell-wk-2/components/api-server/openapi/openapi.yaml
// Spec SHA256: db26dc317d17c6621c5f070f33e57b38975b3ed3228dcbe94857d09c5888f8d3
// Generated: 1970-01-01T00:00:00Z

package types

import (
	"errors"
	"fmt"
)

type ManagedDatabase struct {
	ObjectReference

	ConnectionSecret string `json:"connection_secret,omitempty"`
	Engine string `json:"engine,omitempty"`
	EngineVersion string `json:"engine_version,omitempty"`
	FleetID string `json:"fleet_id"`
	InstanceClass string `json:"instance_class,omitempty"`
	Name string `json:"name"`
	Provider string `json:"provider"`
	Region string `json:"region,omitempty"`
	Status string `json:"status,omitempty"`
}

type ManagedDatabaseList struct {
	ListMeta
	Items []ManagedDatabase `json:"items"`
}

func (l *ManagedDatabaseList) GetItems() []ManagedDatabase { return l.Items }
func (l *ManagedDatabaseList) GetTotal() int                  { return l.Total }
func (l *ManagedDatabaseList) GetPage() int                   { return l.Page }
func (l *ManagedDatabaseList) GetSize() int                   { return l.Size }

type ManagedDatabaseBuilder struct {
	resource ManagedDatabase
	errors   []error
}

func NewManagedDatabaseBuilder() *ManagedDatabaseBuilder {
	return &ManagedDatabaseBuilder{}
}


func (b *ManagedDatabaseBuilder) ConnectionSecret(v string) *ManagedDatabaseBuilder {
	b.resource.ConnectionSecret = v
	return b
}

func (b *ManagedDatabaseBuilder) Engine(v string) *ManagedDatabaseBuilder {
	b.resource.Engine = v
	return b
}

func (b *ManagedDatabaseBuilder) EngineVersion(v string) *ManagedDatabaseBuilder {
	b.resource.EngineVersion = v
	return b
}

func (b *ManagedDatabaseBuilder) FleetID(v string) *ManagedDatabaseBuilder {
	b.resource.FleetID = v
	return b
}

func (b *ManagedDatabaseBuilder) InstanceClass(v string) *ManagedDatabaseBuilder {
	b.resource.InstanceClass = v
	return b
}

func (b *ManagedDatabaseBuilder) Name(v string) *ManagedDatabaseBuilder {
	b.resource.Name = v
	return b
}

func (b *ManagedDatabaseBuilder) Provider(v string) *ManagedDatabaseBuilder {
	b.resource.Provider = v
	return b
}

func (b *ManagedDatabaseBuilder) Region(v string) *ManagedDatabaseBuilder {
	b.resource.Region = v
	return b
}

func (b *ManagedDatabaseBuilder) Status(v string) *ManagedDatabaseBuilder {
	b.resource.Status = v
	return b
}


func (b *ManagedDatabaseBuilder) Build() (*ManagedDatabase, error) {
	if b.resource.FleetID == "" {
		b.errors = append(b.errors, fmt.Errorf("fleet_id is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Provider == "" {
		b.errors = append(b.errors, fmt.Errorf("provider is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ManagedDatabasePatchBuilder struct {
	patch map[string]any
}

func NewManagedDatabasePatchBuilder() *ManagedDatabasePatchBuilder {
	return &ManagedDatabasePatchBuilder{patch: make(map[string]any)}
}


func (b *ManagedDatabasePatchBuilder) ConnectionSecret(v string) *ManagedDatabasePatchBuilder {
	b.patch["connection_secret"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) Engine(v string) *ManagedDatabasePatchBuilder {
	b.patch["engine"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) EngineVersion(v string) *ManagedDatabasePatchBuilder {
	b.patch["engine_version"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) FleetID(v string) *ManagedDatabasePatchBuilder {
	b.patch["fleet_id"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) InstanceClass(v string) *ManagedDatabasePatchBuilder {
	b.patch["instance_class"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) Name(v string) *ManagedDatabasePatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) Provider(v string) *ManagedDatabasePatchBuilder {
	b.patch["provider"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) Region(v string) *ManagedDatabasePatchBuilder {
	b.patch["region"] = v
	return b
}

func (b *ManagedDatabasePatchBuilder) Status(v string) *ManagedDatabasePatchBuilder {
	b.patch["status"] = v
	return b
}


func (b *ManagedDatabasePatchBuilder) Build() map[string]any {
	return b.patch
}

