// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 362a6e78860ff6da7343d12732c5e76e48d2bf479e176535f39bf8bb8fc4d389

package types

import (
	"errors"
	"fmt"
)

type ProviderSpec struct {
	ObjectReference

	Capability string `json:"capability,omitempty"`
	Category   string `json:"category"`
	Name       string `json:"name"`
	Profile    string `json:"profile,omitempty"`
	Status     string `json:"status,omitempty"`
}

type ProviderSpecList struct {
	ListMeta
	Items []ProviderSpec `json:"items"`
}

func (l *ProviderSpecList) GetItems() []ProviderSpec { return l.Items }
func (l *ProviderSpecList) GetTotal() int            { return l.Total }
func (l *ProviderSpecList) GetPage() int             { return l.Page }
func (l *ProviderSpecList) GetSize() int             { return l.Size }

type ProviderSpecBuilder struct {
	resource ProviderSpec
	errors   []error
}

func NewProviderSpecBuilder() *ProviderSpecBuilder {
	return &ProviderSpecBuilder{}
}

func (b *ProviderSpecBuilder) Capability(v string) *ProviderSpecBuilder {
	b.resource.Capability = v
	return b
}

func (b *ProviderSpecBuilder) Category(v string) *ProviderSpecBuilder {
	b.resource.Category = v
	return b
}

func (b *ProviderSpecBuilder) Name(v string) *ProviderSpecBuilder {
	b.resource.Name = v
	return b
}

func (b *ProviderSpecBuilder) Profile(v string) *ProviderSpecBuilder {
	b.resource.Profile = v
	return b
}

func (b *ProviderSpecBuilder) Build() (*ProviderSpec, error) {
	if b.resource.Category == "" {
		b.errors = append(b.errors, fmt.Errorf("category is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProviderSpecPatchBuilder struct {
	patch map[string]any
}

func NewProviderSpecPatchBuilder() *ProviderSpecPatchBuilder {
	return &ProviderSpecPatchBuilder{patch: make(map[string]any)}
}

func (b *ProviderSpecPatchBuilder) Capability(v string) *ProviderSpecPatchBuilder {
	b.patch["capability"] = v
	return b
}

func (b *ProviderSpecPatchBuilder) Name(v string) *ProviderSpecPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ProviderSpecPatchBuilder) Profile(v string) *ProviderSpecPatchBuilder {
	b.patch["profile"] = v
	return b
}

func (b *ProviderSpecPatchBuilder) Build() map[string]any {
	return b.patch
}
