// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: f167deec2ad52601ab466f825250c536e29bab9f99ad0d3c4cb69cfe4c554028

package types

import (
	"errors"
	"fmt"
)

type SecretSource struct {
	ObjectReference

	AgentRuntimeID string `json:"agent_runtime_id"`
	Backend        string `json:"backend"`
	KeyMappings    string `json:"key_mappings,omitempty"`
	Name           string `json:"name"`
	Path           string `json:"path"`
	Purpose        string `json:"purpose"`
}

type SecretSourceList struct {
	ListMeta
	Items []SecretSource `json:"items"`
}

func (l *SecretSourceList) GetItems() []SecretSource { return l.Items }
func (l *SecretSourceList) GetTotal() int            { return l.Total }
func (l *SecretSourceList) GetPage() int             { return l.Page }
func (l *SecretSourceList) GetSize() int             { return l.Size }

type SecretSourceBuilder struct {
	resource SecretSource
	errors   []error
}

func NewSecretSourceBuilder() *SecretSourceBuilder {
	return &SecretSourceBuilder{}
}

func (b *SecretSourceBuilder) AgentRuntimeID(v string) *SecretSourceBuilder {
	b.resource.AgentRuntimeID = v
	return b
}

func (b *SecretSourceBuilder) Backend(v string) *SecretSourceBuilder {
	b.resource.Backend = v
	return b
}

func (b *SecretSourceBuilder) KeyMappings(v string) *SecretSourceBuilder {
	b.resource.KeyMappings = v
	return b
}

func (b *SecretSourceBuilder) Name(v string) *SecretSourceBuilder {
	b.resource.Name = v
	return b
}

func (b *SecretSourceBuilder) Path(v string) *SecretSourceBuilder {
	b.resource.Path = v
	return b
}

func (b *SecretSourceBuilder) Purpose(v string) *SecretSourceBuilder {
	b.resource.Purpose = v
	return b
}

func (b *SecretSourceBuilder) Build() (*SecretSource, error) {
	if b.resource.AgentRuntimeID == "" {
		b.errors = append(b.errors, fmt.Errorf("agent_runtime_id is required"))
	}
	if b.resource.Backend == "" {
		b.errors = append(b.errors, fmt.Errorf("backend is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Path == "" {
		b.errors = append(b.errors, fmt.Errorf("path is required"))
	}
	if b.resource.Purpose == "" {
		b.errors = append(b.errors, fmt.Errorf("purpose is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SecretSourcePatchBuilder struct {
	patch map[string]any
}

func NewSecretSourcePatchBuilder() *SecretSourcePatchBuilder {
	return &SecretSourcePatchBuilder{patch: make(map[string]any)}
}

func (b *SecretSourcePatchBuilder) Backend(v string) *SecretSourcePatchBuilder {
	b.patch["backend"] = v
	return b
}

func (b *SecretSourcePatchBuilder) KeyMappings(v string) *SecretSourcePatchBuilder {
	b.patch["key_mappings"] = v
	return b
}

func (b *SecretSourcePatchBuilder) Name(v string) *SecretSourcePatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *SecretSourcePatchBuilder) Path(v string) *SecretSourcePatchBuilder {
	b.patch["path"] = v
	return b
}

func (b *SecretSourcePatchBuilder) Purpose(v string) *SecretSourcePatchBuilder {
	b.patch["purpose"] = v
	return b
}

func (b *SecretSourcePatchBuilder) Build() map[string]any {
	return b.patch
}
