// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: b39c23e44eaf38276f86232577bc206efc3fdc7b998da9c074d87f66c7b4f61d

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type AgentRuntimeAPI struct {
	client *Client
}

func (c *Client) AgentRuntimes() *AgentRuntimeAPI {
	return &AgentRuntimeAPI{client: c}
}

func (a *AgentRuntimeAPI) Create(ctx context.Context, resource *types.AgentRuntime) (*types.AgentRuntime, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal agent_runtime: %w", err)
	}
	var result types.AgentRuntime
	if err := a.client.do(ctx, http.MethodPost, "/api/hypershell/ext/agent_runtimes", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentRuntimeAPI) Get(ctx context.Context, id string) (*types.AgentRuntime, error) {
	var result types.AgentRuntime
	if err := a.client.do(ctx, http.MethodGet, "/api/hypershell/ext/agent_runtimes/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentRuntimeAPI) List(ctx context.Context, opts *types.ListOptions) (*types.AgentRuntimeList, error) {
	var result types.AgentRuntimeList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/api/hypershell/ext/agent_runtimes", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentRuntimeAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.AgentRuntime, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.AgentRuntime
	if err := a.client.do(ctx, http.MethodPatch, "/api/hypershell/ext/agent_runtimes/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentRuntimeAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/api/hypershell/ext/agent_runtimes/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *AgentRuntimeAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.AgentRuntime] {
	return NewIterator(func(page int) (*types.AgentRuntimeList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
