// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 54fcf6567b2eac5f76528e2fb8cbf0061a64ebd1cc6db65881e3413025ff270f

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type FleetAPI struct {
	client *Client
}

func (c *Client) Fleets() *FleetAPI {
	return &FleetAPI{client: c}
}

func (a *FleetAPI) Create(ctx context.Context, resource *types.Fleet) (*types.Fleet, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal fleet: %w", err)
	}
	var result types.Fleet
	if err := a.client.do(ctx, http.MethodPost, "/fleets", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *FleetAPI) Get(ctx context.Context, id string) (*types.Fleet, error) {
	var result types.Fleet
	if err := a.client.do(ctx, http.MethodGet, "/fleets/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *FleetAPI) List(ctx context.Context, opts *types.ListOptions) (*types.FleetList, error) {
	var result types.FleetList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/fleets", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *FleetAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Fleet, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Fleet
	if err := a.client.do(ctx, http.MethodPatch, "/fleets/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *FleetAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/fleets/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *FleetAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Fleet] {
	return NewIterator(func(page int) (*types.FleetList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
