// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: /home/mturansk/projects/src/github.com/openshift-online/hypershell/components/api-server/openapi/openapi.yaml
// Spec SHA256: 300e25bd78ab5a10ddac513022a9b1cf8a214c26cfb75c3bd73b2d05e648508e
// Generated: 1970-01-01T00:00:00Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type GatewayAPI struct {
	client *Client
}

func (c *Client) Gateways() *GatewayAPI {
	return &GatewayAPI{client: c}
}

func (a *GatewayAPI) Create(ctx context.Context, resource *types.Gateway) (*types.Gateway, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal gateway: %w", err)
	}
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodPost, "/gateways", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) Get(ctx context.Context, id string) (*types.Gateway, error) {
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodGet, "/gateways/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) List(ctx context.Context, opts *types.ListOptions) (*types.GatewayList, error) {
	var result types.GatewayList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/gateways", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Gateway, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodPatch, "/gateways/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}


func (a *GatewayAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/gateways/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}


func (a *GatewayAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Gateway] {
	return NewIterator(func(page int) (*types.GatewayList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
