// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: /home/jsell/code/hypershell-3-openshell-console/components/api-server/openapi/openapi.yaml
// Spec SHA256: 0be59c10f6391994c1751978ea5642e22f00581cb501c883700b7d31ef0fe4e7
// Generated: 1970-01-01T00:00:00Z

package client

type Listable[T any] interface {
	GetItems() []T
	GetTotal() int
	GetPage() int
	GetSize() int
}

type Iterator[T any] struct {
	fetchPage func(page int) (Listable[T], error)
	items     []T
	index     int
	page      int
	total     int
	done      bool
	err       error
}

func NewIterator[T any, L Listable[T]](fetchPage func(page int) (L, error)) *Iterator[T] {
	return &Iterator[T]{
		fetchPage: func(page int) (Listable[T], error) {
			return fetchPage(page)
		},
		page:  0,
		index: -1,
	}
}

func (it *Iterator[T]) Next() bool {
	if it.done || it.err != nil {
		return false
	}
	it.index++
	if it.index < len(it.items) {
		return true
	}
	it.page++
	result, err := it.fetchPage(it.page)
	if err != nil {
		it.err = err
		return false
	}
	it.items = result.GetItems()
	it.index = 0
	it.total = result.GetTotal()
	if len(it.items) == 0 {
		it.done = true
		return false
	}
	return true
}

func (it *Iterator[T]) Item() T {
	return it.items[it.index]
}

func (it *Iterator[T]) Err() error {
	return it.err
}
