// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: fd713a2fb735709ef162219f27fd1c446e1a93df60adc5d06ba060a653d20414

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type ManagedDatabaseAPI struct {
	client *Client
}

func (c *Client) ManagedDatabases() *ManagedDatabaseAPI {
	return &ManagedDatabaseAPI{client: c}
}

func (a *ManagedDatabaseAPI) Create(ctx context.Context, resource *types.ManagedDatabase) (*types.ManagedDatabase, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal managed_database: %w", err)
	}
	var result types.ManagedDatabase
	if err := a.client.do(ctx, http.MethodPost, "/managed_databases", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedDatabaseAPI) Get(ctx context.Context, id string) (*types.ManagedDatabase, error) {
	var result types.ManagedDatabase
	if err := a.client.do(ctx, http.MethodGet, "/managed_databases/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedDatabaseAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ManagedDatabaseList, error) {
	var result types.ManagedDatabaseList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/managed_databases", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedDatabaseAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ManagedDatabase, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ManagedDatabase
	if err := a.client.do(ctx, http.MethodPatch, "/managed_databases/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ManagedDatabaseAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/managed_databases/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ManagedDatabaseAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ManagedDatabase] {
	return NewIterator(func(page int) (*types.ManagedDatabaseList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
