// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: ce3feb60a99096507bfa0aa1a79117785686cd1c21fc58cec8bbe36e4de1f27a

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type RepositoryAPI struct {
	client *Client
}

func (c *Client) Repositories() *RepositoryAPI {
	return &RepositoryAPI{client: c}
}

func (a *RepositoryAPI) Create(ctx context.Context, resource *types.Repository) (*types.Repository, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal repository: %w", err)
	}
	var result types.Repository
	if err := a.client.do(ctx, http.MethodPost, "/api/hypershell/ext/repositories", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryAPI) Get(ctx context.Context, id string) (*types.Repository, error) {
	var result types.Repository
	if err := a.client.do(ctx, http.MethodGet, "/api/hypershell/ext/repositories/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryAPI) List(ctx context.Context, opts *types.ListOptions) (*types.RepositoryList, error) {
	var result types.RepositoryList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/api/hypershell/ext/repositories", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Repository, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Repository
	if err := a.client.do(ctx, http.MethodPatch, "/api/hypershell/ext/repositories/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RepositoryAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/api/hypershell/ext/repositories/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *RepositoryAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Repository] {
	return NewIterator(func(page int) (*types.RepositoryList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
