// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: components/api-server/openapi/openapi.yaml
// Spec SHA256: 4baf5c692945496c1ba8a1c195d838e0f028eb1471cf283b226daf69880cdc1d

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type SandboxTemplateAPI struct {
	client *Client
}

func (c *Client) SandboxTemplates() *SandboxTemplateAPI {
	return &SandboxTemplateAPI{client: c}
}

func (a *SandboxTemplateAPI) Create(ctx context.Context, resource *types.SandboxTemplate) (*types.SandboxTemplate, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal sandbox_template: %w", err)
	}
	var result types.SandboxTemplate
	if err := a.client.do(ctx, http.MethodPost, "/api/hypershell/ext/sandbox_templates", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SandboxTemplateAPI) Get(ctx context.Context, id string) (*types.SandboxTemplate, error) {
	var result types.SandboxTemplate
	if err := a.client.do(ctx, http.MethodGet, "/api/hypershell/ext/sandbox_templates/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SandboxTemplateAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SandboxTemplateList, error) {
	var result types.SandboxTemplateList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/api/hypershell/ext/sandbox_templates", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SandboxTemplateAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.SandboxTemplate, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.SandboxTemplate
	if err := a.client.do(ctx, http.MethodPatch, "/api/hypershell/ext/sandbox_templates/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SandboxTemplateAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/api/hypershell/ext/sandbox_templates/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *SandboxTemplateAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.SandboxTemplate] {
	return NewIterator(func(page int) (*types.SandboxTemplateList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
