apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-server
  namespace: hypershell-system
spec:
  secretName: hypershell-server-tls
  commonName: hypershell-api-server
  dnsNames:
    - hypershell-api-server.hypershell-system.svc.cluster.local
    - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypershell-client
  namespace: hypershell-system
spec:
  secretName: hypershell-client-tls
  commonName: hypershell-client
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: hypershell-ca-issuer
    kind: Issuer
