apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - api-server.yaml
  - controller.yaml
  - controller-gateway-rbac.yaml
  - route.yaml
